### ISSUE TITLE
Your license should be the same as Det3D, that is, Apache 2.0

### ISSUE THREAD

**Issue by poodarchu** [tianweiy/CenterPoint#10]
https://github.com/poodarchu/Det3D/blob/master/LICENSE

**Comment by tianweiy** [comment]
@poodarchu  I am not an expert about the difference between apache 2.0 or MIT. But I think it is allowed to use a different license for a repo with Apache 2.0 [URL](https://resources.whitesourcesoftware.com/blog-whitesource/top-10-apache-license-questions-answered) given that we have included the Det3D's license in the [NOTICE](https://raw.githubusercontent.com/tianweiy/CenterPoint/master/docs/NOTICE) files. Please correct me if I am wrong and I will change the license

**Comment by poodarchu** [comment]
If you want to use another license, you need to add Apache LICENSE to every unmodified file, and state the modifications in your own file. Or you can use the same license as Det3D.

https://en.wikipedia.org/wiki/Apache_License

**Comment by philkr** [comment]
Thank you for your interest in our repo. I think there is a misunderstanding here. We did not build this repo on your apache licensed version of the repo. The code is forked from the MIT licensed part: https://github.com/poodarchu/Det3D/tree/56402d4761a5b73acd23080f537599b0888cce07
As a curtesy we indicated your change of license in the NOTICE file. We understand that this was a mistake and will change the notice file accordingly to indicate that this repo is solely build on MIT licensed code.

**Comment by poodarchu** [comment]
I use the wrong license at the beginning, so it needs to change to Apache now.

**Comment by philkr** [comment]
We understand that you changed the license in your repo after we cloned it. However, this does not oblige anybody to do the same. The MIT license clearly grants that "rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software". However, if there were any files that were copied from already licensed repos under a different license, MIT might not apply to those. If this is the case, please let us know which files and from where, and we'll take appropriate action. However, all files that you were legally allowed to license under MIT will be kept under MIT in this repo.
