### ISSUE TITLE
Any instructions for visualization on cam image?

### ISSUE THREAD

**Issue by as3382246** [tianweiy/CenterPoint#100]
hello, @tianweiy, thanks for your work.
I just want to realize visualization on camera image, so i try to modified `tools/demo.py`, but i got in trouble.
Firstly, I downloaded the driving sequence clip you provided in `README.MD`. 
And in the `info` below:
https://github.com/tianweiy/CenterPoint/blob/1ecebf980f75cfe7f53cc52032b184192891c9b9/tools/demo.py#L83
I found the keys `ref_from_car`, `car_from_global` and `cam_intrinsic`. For `cam_intrinsic`, I think it's the camera intrinsic matrix. But what's the meaning of the other two keys?
How can I transform the `lidar_3d_boxes` to `image_2d_boxes`?

**Comment by tianweiy** [comment]
The other two are lidar and car pose matrix. I can add an example to visualize boxes on images in a few days.

**Comment by tianweiy** [comment]
it is a little specific than I thought so maybe you should refer to the exact dataset you are working on and then check their documentations. For nuScenes, I remembered there are related functions to plot boxes on cameras. For Waymo, there is a projection module https://github.com/waymo-research/waymo-open-dataset/tree/master/third_party/camera but I haven't used yet. Sorry that I am too busy to add any code any time soon. This should do the 3d visualization if you only want to do some checking https://github.com/tianweiy/CenterPoint/blob/master/tools/visual.py

**Comment by as3382246** [comment]
@tianweiy hello, thank you very much.
I am trying to do this work. There still has some little problems. I think I can do it. Thanks for the information you told me before.
Hope you have some great work in the future.
