### ISSUE TITLE
camera  lidar fusion

### ISSUE THREAD

**Issue by pigtigger** [tianweiy/CenterPoint#101]
i find the modalities of centerpoint on Nuscenes dataset shows " Lidar Camera Radar" ,does centerpoint use camera&lidar fusion strategy?

**Comment by tianweiy** [comment]
not in the main paper. For the challenge, we use pointpainting to do some camera lidar fusion. For radar, we only use it to filter empty boxes. Please see the appendix for details

**Comment by pratikkayal** [comment]
Hi Tienweiy, Would it be possible for you to provide your code with pointpainting?

**Comment by tianweiy** [comment]
check this https://github.com/tianweiy/CenterPoint/issues/56#issuecomment-761717909 

It may not work with current codebase but it is slow. But it can give you some idea how to implement pointpainting

**Comment by tianweiy** [comment]
close due to inactivity. Reopen if you get any other problems. For fusion techniques, there are multiple approaches that we can explore but it is out of the scope of this project
