### ISSUE TITLE
an error when running train.py.

### ISSUE THREAD

**Issue by as3382246** [tianweiy/CenterPoint#102]
My environment: Python3.6, cuda 10.2, pytorch 1.6.
And when I ran train.py, an ImportError libcudart.so.9.0: No such file or directory.
why it need cuda 9.0？ Is there any problems in my environment？

**Comment by as3382246** [comment]
and the system cuda version is 10.2.

**Comment by tianweiy** [comment]
it doesn't need cuda 9.0. when do you get this import error? Import which library?

**Comment by as3382246** [comment]
> it doesn't need cuda 9.0. when do you get this import error? Import which library?

in the file det3d/ops/iou3d_nms/__init__.py,  after this sentence `from det3d.ops.iou3d_nms import iou3d_nms_cuda, iou3d_nms_utils`, the importerror occured.

**Comment by tianweiy** [comment]
ic, seem to be some compilation error for the nms.

```
export PATH=/usr/local/cuda-10.0/bin:$PATH
export CUDA_PATH=/usr/local/cuda-10.0
export CUDA_HOME=/usr/local/cuda-10.0
export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64:$LD_LIBRARY_PATH
bash setup.sh 
```
could you change this path information to your specific Cuda version and then recompile the nms function?

**Comment by as3382246** [comment]
> ic, seem to be some compilation error for the nms.
> 
> ```
> export PATH=/usr/local/cuda-10.0/bin:$PATH
> export CUDA_PATH=/usr/local/cuda-10.0
> export CUDA_HOME=/usr/local/cuda-10.0
> export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64:$LD_LIBRARY_PATH
> bash setup.sh 
> ```
> 
> could you change this path information to your specific Cuda version and then recompile the nms function?

yes, you are right. I changed the cuda version after compiling cuda extension.
Recompile the cuda extension, it works! Thank you!
