### ISSUE TITLE
Inference for own test data

### ISSUE THREAD

**Issue by FantineFu** [tianweiy/CenterPoint#103]
Hi, thanks for your wonderful work! I want to know which file can I use for my own data to test. I only have .bin or .pcd file, could you please give some hints if I have to prepare database tables in .json format according to the nuscenes specifications? I found that if I use dict_test.py to do inference, I have to prepare these tables. Is it necessary to generate .pkl for my own test data by create_data.py?

**Comment by tianweiy** [comment]
I will add an inference file by this weekend. For the first step of support custom dataset training/inference, I will add a function that takes a numpy point cloud array and outputs a numpy box list. I will also provide some visualization utility. Please stay tuned

**Comment by tianweiy** [comment]
> I only have .bin or .pcd file, could you please give some hints if I have to prepare database tables in .json format according to the nuscenes specifications? I found that if I use dict_test.py to do inference, I have to prepare these tables. Is it necessary to generate .pkl for my own test data by create_data.py

All of these are required for training (and not required for single frame testing).

**Comment by FantineFu** [comment]
Thanks! I'm looking forward to your update!
