### ISSUE TITLE
What does the "dist" mean in the plot?

### ISSUE THREAD

**Issue by yaxi333** [tianweiy/CenterPoint#104]
![image](https://user-images.githubusercontent.com/57478405/112553364-a7028a00-8dc4-11eb-808a-6d454b7bea25.png)

Hi,

We are now studying on this CenterPoint Algorithms. And we want to ask want this Dist(0.5,1.0,2.0,4.0) means in the plot.

Does it mean the central distance between ground truth boxes and candidate boxes or  it means the central distances between candidate boxes?

**Comment by tianweiy** [comment]
nuScenes uses its own way to compute mAP that is based on the 2D center distance. Here, it means that at 0.5-meter distance threshold, it gets 75 mAP, 1.0 meter it gets 85.1, etc..
