### ISSUE TITLE
offical releaes

### ISSUE THREAD

**Issue by BrianJiang8688** [tianweiy/CenterPoint#105]
Dear Sir
Thanks a lot for your great work! 
Our research team have been following this project for a long time, btw, would you consider to publish an offical release tag ?
Sothat we may able to have distinctions for different versions in the future.

**Comment by tianweiy** [comment]
Thanks for the interest. I still have some stuff to add in this or next week. And then I can add a release tag.

**Comment by tianweiy** [comment]
I just added a tag. I still get some documentation / demo improvement in plans but there won't be large change to the code before next paper's code release.
