### ISSUE TITLE
Unable to replicate detection results

### ISSUE THREAD

**Issue by triple-tam** [tianweiy/CenterPoint#107]
Hi Tianweiy, I am unable to replicate the detection results on `nuScenes v1.0-trainval`. I run the following command:

`python ./tools/dist_test.py ./configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_dcn.py --work_dir work_dirs/nusc_0075_dcn_verifydet --checkpoint work_dirs/nusc_0075_dcn_verifydet/voxelnet_converted.pth --speed_test`

I expect a mAP 57.1 and NDS 65.4 on the validation split. However, I instead get mAP 42.59 and NDS 57.82, which is quite a difference from the published results. The code and .zip files I downloaded clean (i.e. no edits made). Could you help me with this? Thank you.

Below is my output (sorry only have img version):
![Screen Shot 2021-03-31 at 17 36 58](https://user-images.githubusercontent.com/28011103/113172618-ddb72500-9248-11eb-9b73-00c13d4eea57.png)
![Screen Shot 2021-03-31 at 17 37 16](https://user-images.githubusercontent.com/28011103/113172632-e1e34280-9248-11eb-897e-85d7f2242f1e.png)

**Comment by tianweiy** [comment]
not sure what went wrong but I just run the model again and the result is attached

![Screenshot from 2021-03-31 11-33-09](https://user-images.githubusercontent.com/38497390/113179092-e42ba980-9214-11eb-9a26-92be489903a6.png)

**Comment by triple-tam** [comment]
I just ran it again, and still the same results. I notice that my # of predicted boxes is much higher than yours (878146 vs. 778367) and that could be a sign of why the results are off. What could be causing the difference in # of predicted boxes?

**Comment by tianweiy** [comment]
yeah, I noticed this. But I don't get much idea. Could you try other model ? like the VoxelNet 0.1 voxel size, or PointPillars. I can take a deeper look if these models also don't work

**Comment by triple-tam** [comment]
Ok I just tried the other models and again was not able to replicate the published results.

For the model nusc_0075_dcn_flip:
`python ./tools/dist_test.py ./configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_dcn_flip.py --work_dir work_dirs/nusc_0075_dcn_flip-20210401 --checkpoint work_dirs/nusc_0075_dcn_flip-20210401/voxelnet_converted.pth --speed_test`

![Screen Shot 2021-04-01 at 14 30 26](https://user-images.githubusercontent.com/28011103/113399517-9fcd1480-93a0-11eb-8a5d-bb44ff9b9ce5.png)
![Screen Shot 2021-04-01 at 14 30 37](https://user-images.githubusercontent.com/28011103/113399535-a52a5f00-93a0-11eb-8a13-c06932c99423.png)


For the model nusc_01:
`python ./tools/dist_test.py ./configs/nusc/voxelnet/nusc_centerpoint_voxelnet_01voxel.py --work_dir work_dirs/nusc_01-20210401 --checkpoint work_dirs/nusc_01-20210401/voxelnet_converted.pth --speed_test`
<img width="1016" alt="Screen Shot 2021-04-02 at 10 42 58" src="https://user-images.githubusercontent.com/28011103/113399607-c7bc7800-93a0-11eb-9a19-6b6a2ce7ef70.png">
<img width="1022" alt="Screen Shot 2021-04-02 at 10 43 09" src="https://user-images.githubusercontent.com/28011103/113399619-cbe89580-93a0-11eb-9981-901a39b8a672.png">

**Comment by tianweiy** [comment]
ok, thanks for the experiments. Could you send me the generated info file? Here or through email. I could compare the output and see

**Comment by triple-tam** [comment]
Sounds good, the output infos.json files for each model experiment are attached [in this URL.](https://drive.google.com/file/d/1M1ZEFDRolT6BrWSdyqhWE_czIzG8BfUX/view?usp=sharing)

I also ran the PointPillars model:
`python ./tools/dist_test.py ./configs/nusc/pp/nusc_centerpoint_pp_02voxel_two_pfn_10sweep.py --work_dir work_dirs/nusc_02_pp-20210402 --checkpoint work_dirs/nusc_02_pp-20210402/latest.pth --speed_test`

<img width="913" alt="Screen Shot 2021-04-02 at 22 17 14" src="https://user-images.githubusercontent.com/28011103/113451129-a0e25e00-9401-11eb-8662-c09fe155e856.png">
<img width="912" alt="Screen Shot 2021-04-02 at 22 17 23" src="https://user-images.githubusercontent.com/28011103/113451137-a50e7b80-9401-11eb-9eed-c9376776dc91.png">

**Comment by tianweiy** [comment]
I took a look but still don't get any idea. I run the pointpillars again and the output is here 

```
WARNING:tensorflow:From /home/tianweiy/CenterPoint/det3d/datasets/waymo/waymo_common.py:17: The name tf.enable_eager_execution is deprecated. Please use tf.compat.v1.enable_eager_execution instead.

Deformable Convolution not built!
No APEX!
2021-04-03 20:41:21,670 - INFO - Distributed testing: False
2021-04-03 20:41:21,670 - INFO - torch.backends.cudnn.benchmark: False
2021-04-03 20:41:21,699 - INFO - Finish RPN Initialization
2021-04-03 20:41:21,699 - INFO - num_classes: [1, 2, 2, 1, 2, 2]
Use HM Bias:  -2.19
2021-04-03 20:41:21,730 - INFO - Finish CenterHead Initialization
Use Val Set
10
2021-04-03 20:41:24,030 - INFO - work dir: .
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 6019/6019, 12.3 task/s, elapsed: 491s, ETA:     0s
 Total time per frame:  0.0
======
Loading NuScenes tables for version v1.0-trainval...
23 category,
8 attribute,
4 visibility,
64386 instance,
12 sensor,
10200 calibrated_sensor,
2631083 ego_pose,
68 log,
850 scene,
34149 sample,
2631083 sample_data,
1166187 sample_annotation,
4 map,
Done loading in 20.6 seconds.
======
Reverse indexing ...
Done reverse indexing in 6.4 seconds.
======
Finish generate predictions for testset, save to infos_val_10sweeps_withvelo_filter_True.json
Initializing nuScenes detection evaluation
Loaded results from infos_val_10sweeps_withvelo_filter_True.json. Found detections for 6019 samples.
Loading annotations for val split from nuScenes version: v1.0-trainval
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6019/6019 [00:08<00:00, 724.59it/s]
Loaded ground truth annotations for 6019 samples.
Filtering predictions
=> Original number of boxes: 1037839
=> After distance based filtering: 784270
=> After LIDAR points based filtering: 784270
=> After bike rack filtering: 783533
Filtering ground truth annotations
=> Original number of boxes: 187528
=> After distance based filtering: 134565
=> After LIDAR points based filtering: 121871
=> After bike rack filtering: 121861
Rendering sample token 5376e3a2874542d8b440faa899e52b97
Rendering sample token 14f665de1fa34d0a9d12838a5b77d687
Rendering sample token c428be7e072c4c2489b90a6dcefcae4c
Rendering sample token d6d3eac48860468aa0eba1ae2896b5ea
Rendering sample token 67aad7ad948f44f8af668ea8389bdd52
Rendering sample token 9c9f22a58fdc45f2b8a119cda3554f1f
Rendering sample token e30f071748cc49eb85babe49265a4eda
Rendering sample token f4550267cd0240e1a1ceb844e33e97d4
Rendering sample token 93fdce35d7db4764ad5f822f57ab49e2
Rendering sample token 22186f4894ab46b481a9e1ee31d7734e
Accumulating metric data...
Calculating metrics...
Rendering PR and TP curves
Saving metrics to: .
mAP: 0.5026
mATE: 0.3138
mASE: 0.2593
mAOE: 0.3948
mAVE: 0.3295
mAAE: 0.1981
NDS: 0.6018
Eval time: 93.3s

Per-class results:
Object Class	AP	ATE	ASE	AOE	AVE	AAE
car	0.840	0.189	0.156	0.154	0.306	0.198
truck	0.534	0.335	0.190	0.157	0.279	0.248
bus	0.643	0.345	0.183	0.054	0.597	0.320
trailer	0.319	0.589	0.217	0.600	0.197	0.127
construction_vehicle	0.125	0.619	0.425	1.149	0.138	0.368
pedestrian	0.789	0.164	0.277	0.415	0.230	0.096
motorcycle	0.440	0.230	0.239	0.401	0.668	0.188
bicycle	0.183	0.207	0.271	0.530	0.220	0.040
traffic_cone	0.548	0.185	0.344	nan	nan	nan
barrier	0.604	0.274	0.291	0.093	nan	nan
Evaluation nusc: Nusc v1.0-trainval Evaluation
car Nusc dist AP@0.5, 1.0, 2.0, 4.0
73.40, 84.90, 88.26, 89.61 mean AP: 0.8404224342290673
truck Nusc dist AP@0.5, 1.0, 2.0, 4.0
34.87, 53.81, 60.85, 64.25 mean AP: 0.5344373426876957
construction_vehicle Nusc dist AP@0.5, 1.0, 2.0, 4.0
1.83, 9.58, 16.46, 22.00 mean AP: 0.12465727099637769
bus Nusc dist AP@0.5, 1.0, 2.0, 4.0
40.54, 63.92, 74.45, 78.31 mean AP: 0.6430431846156155
trailer Nusc dist AP@0.5, 1.0, 2.0, 4.0
6.66, 25.91, 42.75, 52.31 mean AP: 0.3190663405379586
barrier Nusc dist AP@0.5, 1.0, 2.0, 4.0
46.48, 61.16, 66.15, 67.86 mean AP: 0.6041071659402619
motorcycle Nusc dist AP@0.5, 1.0, 2.0, 4.0
38.31, 45.10, 45.93, 46.58 mean AP: 0.43981988013604023
bicycle Nusc dist AP@0.5, 1.0, 2.0, 4.0
17.53, 18.35, 18.42, 19.02 mean AP: 0.18327804959942118
pedestrian Nusc dist AP@0.5, 1.0, 2.0, 4.0
75.86, 78.02, 79.94, 81.77 mean AP: 0.7889614725132579
traffic_cone Nusc dist AP@0.5, 1.0, 2.0, 4.0
50.56, 53.31, 55.61, 59.84 mean AP: 0.5483157552855971
```

I also looked into the predictions. The first few are exactly the same  
```
{'sample_token': 'fd8420396768425eabec9bdddf7e64b6',
 'translation': [238.5336649820913, 913.5811561943419, 0.8178466555858235],
 'size': [1.941047191619873, 4.686219692230225, 1.695513367652893],
 'rotation': [-0.05642427875393288,
  -0.01451897126186833,
  -0.005060293211819714,
  -0.9982884821899968],
 'velocity': [-0.003885525449341362, 0.0011442948418105496],
 'detection_name': 'car',
 'detection_score': 0.9006239771842957,
 'attribute_name': 'vehicle.parked'}

{'sample_token': 'fd8420396768425eabec9bdddf7e64b6',
 'translation': [238.5336649820913, 913.5811561943419, 0.8178466555858235],
 'size': [1.941047191619873, 4.686219692230225, 1.695513367652893],
 'rotation': [-0.05642427875393288,
  -0.01451897126186833,
  -0.005060293211819713,
  -0.9982884821899968],
 'velocity': [-0.0038855254493413613, 0.0011442948418105496],
 'detection_name': 'car',
 'detection_score': 0.9006239771842957,
 'attribute_name': 'vehicle.parked'}
```

But later one are quite different 

```
{'sample_token': 'fd8420396768425eabec9bdddf7e64b6',
 'translation': [234.2726240440502, 940.5348704883771, 1.4279969817978069],
 'size': [1.9032458066940308, 4.423369884490967, 1.6396597623825073],
 'rotation': [0.6590264216996125,
  -0.013906298109727714,
  0.006559113261404357,
  -0.7519626110438695],
 'velocity': [1.9240300060300094e-09, -9.99591698491402e-09],
 'detection_name': 'car',
 'detection_score': 0.2936813235282898,
 'attribute_name': 'vehicle.parked'}

{'sample_token': 'fd8420396768425eabec9bdddf7e64b6',
 'translation': [217.04610062119278, 942.5473745122483, 1.1620993524755705],
 'size': [1.9314839839935303, 4.393193244934082, 1.6663353443145752],
 'rotation': [0.7750769363095061,
  -0.012619429571072645,
  0.008783910928127876,
  -0.6316797730711176],
 'velocity': [1.924030006030008e-09, -9.995916984914021e-09],
 'detection_name': 'car',
 'detection_score': 0.30032822489738464,
 'attribute_name': 'vehicle.parked'}
```
