### ISSUE TITLE
Not sure about which part to download in nuScenes dataset

### ISSUE THREAD

**Issue by G4V1Nn** [tianweiy/CenterPoint#108]
Hi, Tianwei! Nice work! I'm a novice in point cloud object tracking, and I'm going to run your code. However, I'm not quite sure about which part of the dataset should I download. Should I download all the part or just 'Keyframe blobs'? I've just download the 'Keyframe blobs', but find only the 'samples' folder in it, where can i get the 'sweeps', 'maps' and 'v1.0-trainval' folders? I really appreciate your help！
![( S`L}$ (C`S0Q9JQZ44E7H](https://user-images.githubusercontent.com/59501059/113184944-643f2700-9288-11eb-988c-d7c2c19f8655.png)
![JY3L)7TIS4{TEPG1(@YH1 I](https://user-images.githubusercontent.com/59501059/113185153-ab2d1c80-9288-11eb-9883-a02cc063f0a2.png)

**Comment by tianweiy** [comment]
you need all lidar blobs

**Comment by G4V1Nn** [comment]
> you need all lidar blobs

Thanks!
