### ISSUE TITLE
Why circular nms is deprecated

### ISSUE THREAD

**Issue by turboxin** [tianweiy/CenterPoint#111]
Hi @tianweiy, thanks for sharing this great work~

I noticed that the first version of CenterPoint used circular nms, which speeds up by ∼ 7ms with minor performance drop. But in the second version,  circular nms seems to be deprecated. I'm wondering why.

Looking forward to your reply~ Thanks a lot!

**Comment by xavidzo** [comment]
I was also wondering about it. Could it be possible that you @tianweiy enable an option to build the center head again with circular nms?

**Comment by tianweiy** [comment]
@turboxin  for some reason, the circle nms is slow in my Waymo experiments. I guess it is because it is now implemented with for loops in numpy. Implementing it in cuda will be faster but I don't get like to look at this recently. 

@xavidzo  I will add an option today

**Comment by tianweiy** [comment]
https://github.com/tianweiy/CenterPoint/commit/cb25e870b271fe8259e91c5d17dcd429d74abc91 here
