### ISSUE TITLE
Can I get the test result of train set with the centerpoint_voxel_1440_dcn(flip)? 

### ISSUE THREAD

**Issue by ChenWenming1995** [tianweiy/CenterPoint#112]
Hi, thaks for your great work!

My own PC is too slow. and I want to use the detect result of train set for my tracking , but I realized that there only are result of val set in the google driver. So can you just put it in google driver by any chance:)

Thanks a lot!!

**Comment by tianweiy** [comment]
Yes, I will add this asap

**Comment by tianweiy** [comment]
I am generating it. I will post a link tomorrow morning

**Comment by ChenWenming1995** [comment]
> I am generating it. I will post a link tomorrow morning

Thank you very much!

**Comment by tianweiy** [comment]
https://drive.google.com/file/d/1TkopDPnTzOvO5JvHscCVlmPFMcd0NrK8/view?usp=sharing

**Comment by ChenWenming1995** [comment]
> https://drive.google.com/file/d/1TkopDPnTzOvO5JvHscCVlmPFMcd0NrK8/view?usp=sharing

Thanks:)
