### ISSUE TITLE
num_input_features when inference by custom dataset

### ISSUE THREAD

**Issue by shallowdream-x** [tianweiy/CenterPoint#113]
Thank you for sharing the wonderful project! I have one question when I try to use the pretrained weight to inference on my own dataset.  I notice in the train config file the num_input_features is 5, maybe is ring_num? But my own pointcloud data only has 4 feature:x, y, z, intensity. If I want to inference by my data, do I need to train the weight by the config file num_input_feature from from scratch? Thanks again.

**Comment by tianweiy** [comment]
> the num_input_features is 5
For nuScenes, it is x,y,z, intensity, timestamp. You can set the timestamp to be 0. You also want to make sure that the scale of the intensity match nuScenes's value (0-255). 

After these changes, it should be ok to run the model without retraining

**Comment by hughlee815** [comment]
What if I just want to train my dataset without intensity and elongation?
Can I just set the `num_input_features` to be 3(x, y, z) from 6 and train the model from scratch?

**Comment by tianweiy** [comment]
yes this should be enough, and then you may also need to adapt the loading function a bit https://github.com/tianweiy/CenterPoint/blob/400ae24bb4e8f4ccabd46757738bb0304bfa2681/det3d/datasets/pipelines/loading.py#L61 if you meet any errors.
