### ISSUE TITLE
Can I get the pre-trained model?

### ISSUE THREAD

**Issue by ZhangYu1ing** [tianweiy/CenterPoint#114]
Hi,

since our computer does not have enough space for the entire trainval nuScenes dataset. And train the CenterPoint model is not the main purpose of our master thesis. Therefore, would you mind sharing your pre-trained model with traninval nuScenes dataset for object detection? Then, we could directly use the trained lastest.pth for our next step.

Thanks in advance :D

**Comment by tianweiy** [comment]
I am a little confused. What do you need? All pretrained model is available here https://github.com/tianweiy/CenterPoint/blob/master/configs/nusc/README.md

**Comment by ZhangYu1ing** [comment]
Since I first ran the tools/dist_test.py with your shared URL link, however, there was a traceback showed it needed the prediction.pkl file which was not in your shared link. 

After I added our prediction.pkl file into the folder, it could work properly with mAP=50.65 and NDS=54.22. So I am wondering if the prediction.pkl file is important for testing or not? 

Thanks a lot.

**Comment by tianweiy** [comment]
> After I added our prediction.pkl file into the folder, it could work properly with mAP=50.65 and NDS=54.22. So I am wondering if the prediction.pkl file is important for testing or not?

oh, the prediction.pkl is just an intermediate file. The info_val_XXX.json is the detection output. You can just this for downstream tasks ?

**Comment by hughlee815** [comment]
> oh, the prediction.pkl is just an intermediate file. The info_val_XXX.json is the detection output. You can just this for downstream tasks ?
Hi, tianwei, for some unknown reason, i didn't see the info_val_XXX.json file, there are only xxx.log/xxx.log.json/xxx.pth/prediction.pkl/detection_pred.bin in the corresponding dirs.

**Comment by tianweiy** [comment]
For waymo, there is no infos_val_json, it is only for nuScenes

**Comment by hughlee815** [comment]
> For waymo, there is no infos_val_json, it is only for nuScenes.
in that case, how can obtain the final detection results? by parsing the xxx.bin file?

**Comment by tianweiy** [comment]
Yes, detailed instructions here https://github.com/waymo-research/waymo-open-dataset/blob/master/docs/quick_start.md

**Comment by hughlee815** [comment]
Thanks for your soon reply.
parsing the bin file is a little complex for me. Can I just do nms operation on the prediction.pkl to get the final results?

**Comment by tianweiy** [comment]
The prediction contains all detection output. If you want less boxes, you can change this value https://github.com/tianweiy/CenterPoint/blob/400ae24bb4e8f4ccabd46757738bb0304bfa2681/configs/waymo/voxelnet/waymo_centerpoint_voxelnet_1x.py#L68 to be smaller (to suppress more boxes)

or this to be larger https://github.com/tianweiy/CenterPoint/blob/400ae24bb4e8f4ccabd46757738bb0304bfa2681/configs/waymo/voxelnet/waymo_centerpoint_voxelnet_1x.py#L70

**Comment by hughlee815** [comment]
That helps a lot, very very thanks.
