### ISSUE TITLE
how to create infos_test_10sweeps_withvelo.pkl <-- test info

### ISSUE THREAD

**Issue by abysmalocean** [tianweiy/CenterPoint#116]
how to create the infos_test_10sweeps_withvelo.pkl <-- test info file ?

**Comment by tianweiy** [comment]
python tools/create_data.py nuscenes_data_prep --root_path data/nuScenes/v1.0-test/  --version v1.0-test

**Comment by abysmalocean** [comment]
Thanks for your quick replay.
