### ISSUE TITLE
About test time config

### ISSUE THREAD

**Issue by XuyangBai** [tianweiy/CenterPoint#118]
Hi @tianweiy Thanks for sharing this great work. I have several questions regarding the configuration of test time.

1. why you choose 83 for `nms_post_max_size` ? wouldn't it be too large for most of the categories in one frame?
2. why the `post_center_limit_range=[-61.2, -61.2, -10.0, 61.2, 61.2, 10.0]` is the larger than `pc_range=(-51.2, -51.2, -5.0, 51.2, 51.2, 3.0)`, wouldn't it be useless for `post_center_limit_range`?
3. any general guidance on the configuration if I would like to train CenterPoint on my own dataset, currently I follow nuscenes configuration, but found many false positives, and the detection results generate fastly with the distance between objects center and the vehicle center.

Best,
Xuyang

**Comment by tianweiy** [comment]
> why you choose 83 for nms_post_max_size? wouldn't it be too large for most of the categories in one frame?

Yes, it will be quite large. I never tune this yet. 

> why the post_center_limit_range=[-61.2, -61.2, -10.0, 61.2, 61.2, 10.0] is the larger than pc_range=(-51.2, -51.2, -5.0, 51.2, 51.2, 3.0), wouldn't it be useless for post_center_limit_range?

Yes, you can set this to be a little smaller. This is only used at the end (after NMS). 

> any general guidance on the configuration if I would like to train CenterPoint on my own dataset, currently I follow nuscenes configuration, but found many false positives, and the detection results generate fastly with the distance between objects center and the vehicle center.

For false positives, you need to either increase the score threshold or decrease the NMS iou threshold. This should be able to eliminate FPs.  

> the detection results generate fastly with the distance between objects center and the vehicle center.

Could you elaborate this a little bit more?

**Comment by XuyangBai** [comment]
Thanks for your quick reply. For the last question, I breakdown the metric by the distance between object center and vehicle frame origin just like WOD, but I found the AP decrease very fastly when the distance becomes larger, for example, the AP for car is larger than 0.90 for [0-30m) range but decrease to like 0.4 for [30-50m). I know that might because the density and pts_in_gt_box is very small for far regions, but any suggestion to improve the results for far regions?

**Comment by tianweiy** [comment]
![image](https://user-images.githubusercontent.com/38497390/114114489-919e5d00-98a6-11eb-84ce-422aab0a1211.png)

I see. This is quite normal to my knowledge. If you visualize the prediction, for nuScenes (32 lane lidar), you only get one or two points inside a box (the bottom box in the image I attached). I guess there is no way to detect it ..

**Comment by XuyangBai** [comment]
Ok I see, thanks a lot :)
