### ISSUE TITLE
Details about the second stage

### ISSUE THREAD

**Issue by XuyangBai** [tianweiy/CenterPoint#121]
Could you explain some details of the second stage? As you mentioned in paper that for box regression, the model predict a **refinement** on top of first stage results.  My main question is how to refine the yaw angle predition. 

https://github.com/tianweiy/CenterPoint/blob/cb25e870b271fe8259e91c5d17dcd429d74abc91/det3d/models/roi_heads/roi_head_template.py#L52-L59

In your code, I found that you first compute the  `x,y,z,w,h,l` refinement target by the residual between ground truth xyzwhl and the first stage prediction, and then rotation them using the yaw angle.  And during test, you do the different order: first add the `whl` residual, rotate the bbox using the prediction yaw refinement, then add the `xyz` residual.

It is little difficult to understand the different order between the two steps and could you give some explaination? Besides, could we (1.) consider the yaw angle as a linear variable and just predict difference between `xyzwhl,yaw` or (2.) predict the absolute bbox coordinate, instead of the residual on top of first stage results?

**Comment by tianweiy** [comment]
> It is little difficult to understand the different order between the two steps and could you give some explanation 

This is the canonical transformation defined in PointRCNN (section 3.3). You basically transform gt targets to the coordinate defined by each proposal box. The rotation is to align the coordinate axis with the heading direction. Let me know if any part is still confusing. 

> consider the yaw angle as a linear variable and just predict the difference between xyzwhl,yaw

If you only use Bev features, this may be fine. But you need to do this canonical transformation if you want to use point level features (eg. xyz location) to ensure generalizability across different locations (see section 3.1 of LIDAR RCNN or PointRCNN paper)

>  predict the absolute bbox coordinate, instead of the residual on top of first stage results?

This will be hard afaik. Like regressing a value from 0 -70 is harder than regressing something in 0 - 0.5

**Comment by XuyangBai** [comment]
Thanks a lot for the quick reply, it is clear now.
