### ISSUE TITLE
Questions for combining CenterPoint with PointPainting.

### ISSUE THREAD

**Issue by ZhangYu1ing** [tianweiy/CenterPoint#122]
Hi,

thanks for sharing the idea for combining CenterPoint and PointPainting in  https://github.com/tianweiy/CenterPoint/issues/56#issuecomment-761717909. I have attempted to run this script and there are some questions and I also want to make sure the aim of this script:

1. As I understanding, you may want to paint the image information to the lidar points by 'PaintData'. The function 'paint' in this script plays the same role as the 'PointPainting' algorithm. So here we do not need to invoke the any functions in 'PointPainting' algorithm. Instead, we could only run this script and realize CenterPoint+PointPainting. Please correct me if I have any misunderstandings:D
2. As you demonstrated, this code uses a mmdetection3d nuImages model. Therefore, after installing mmDetection3D, we should set the path about '--info_path', '--config', and '--checkpoint', and use the corresponding files in mmDetection3D, rather than the files in CenterPoint, right? The reason why I am confused here is that I checked mmDetection3D support CenterPoint model. And if I follow the path mmdetection3d/configs/centerpoint, there are many .py files that look similar to you provided files in CenterPoint/configs/nusc/voxelnet. Therefore, I am wondering if the scripts should be run with the files in mmdetection3D rather than the files in CenterPoint.

I would appreciate your reply. Thanks in advance :D

**Comment by tianweiy** [comment]
> As I understanding, you may want to paint the image information to the lidar points by 'PaintData'. The function 'paint' in this script plays the same role as the 'PointPainting' algorithm. So here we do not need to invoke the any functions in 'PointPainting' algorithm. Instead, we could only run this script and realize CenterPoint+PointPainting. Please correct me if I have any misunderstandings:D

This script just tries to explain how pointpainting works. It is not runable with the current codebase. You can take a look at the paint function and write your version of pointpainting.

> 2 

mmdetection3d contains an reimplementation of CenterPoint. Here, info_path is a path to an info file that should contain camera intrinsic, extrinsics, config is a config in mmdet3d under nuimages folder.
