### ISSUE TITLE
Is it possible to provide an implementation of VoxelNet/PointPillars + Anchor Head?

### ISSUE THREAD

**Issue by jialeli1** [tianweiy/CenterPoint#123]
Hi. 
If we want to conduct our own research based on the CenterPoint code base, then the implementation of VoxelNet/PointPillars + Anchor Head is expected. It will be more convenient to verify our research and compare more methods.

**Comment by tianweiy** [comment]
If you want to use anchor based method, you can go back to commit 604585

**Comment by jialeli1** [comment]
Thanks a lot!
