### ISSUE TITLE
Explore the availablity of CenterPoint on Medical Volume Image.

### ISSUE THREAD

**Issue by Joevaen** [tianweiy/CenterPoint#124]
Hi,
Did you team make some tests on medical volume image (eg.CT)?

**Comment by tianweiy** [comment]
I remembered someone use centernet for medical imaging tasks. You can search on arxiv or somewhere. Ours arenot directly applicable as in the current setup we clamping the 3d space into a birds eye view heatmap for outdoor 3d detection.

**Comment by Joevaen** [comment]
Thanks for your reply,
I am going to try it and I will feedback result later.
