### ISSUE TITLE
Marginal improvement by second stage

### ISSUE THREAD

**Issue by XuyangBai** [tianweiy/CenterPoint#126]
Hi @tianweiy I have tried the second stage on my own data but found that the improvement is marginal. So I try to decompose the effect of second stage into the classification part and the regression part ( when testing the cls part, I only use the cls output to update the score of first stage; while testing the reg part, I only use the reg output to refine the boxes of the first stage) 
And I find that the cls head brought quite a lot of improvement but the regression head does not improve at all. I wonder have you even meet such problems?

**Comment by tianweiy** [comment]
Could you give some quantitative numbers? How many mAP improvements are from classification, regression, and in total? 

I also tried to ablate this in the past. On Waymo, pedestrian detection mainly benefits from classification but for vehicles, it is about half/half regression and classification.

**Comment by XuyangBai** [comment]
In my experiments, the mAP improves from 67.9%, 37.5%(iou 0.5&0.7 respectively) to 68.9%, 39.1% in total. For classification part, it leads to 69.6%, 38.0% while for regression part it leads to 67.7%, 37.9%.  As you can see, the regression part individually brought negligible improvement, and it even hurt the performance under 0.5 iou.  For each individual category, I found the improvement of classification head over the cyclist class is quite good (~9% AP for iou 0.5) but over car and pedestrian is negligible and even negative.

**Comment by tianweiy** [comment]
That sounds reasonable to me. For sparse lidar point clouds (e.g. nuScenes), the second stage won't help much for the regression part (even humans can't tell the exact heading/shape of the box if you are only given 3-4 lidar points). The classification branch will help with eliminating false positive which possibly explains the large improvement for cyclist. 

Note that in our paper, we only get this two-stage refinement worked on Waymo which has considerably denser point clouds. For nuScenes, we didn't notice an improvement by the time we submitted the paper. I tried Lidar RCNN on nuScenes and this also doesn't improve the regression

**Comment by XuyangBai** [comment]
I agree that the regression part won't help much for very sparse boxes, but the mAP I mentioned above is the mAP in range [0,30m] where the boxes should contain quite a number of points. Besides my Lidar data have about 220k points per frame, which is much denser than nuscenes, so I expect the regression part to improve the quality of the proposal boxes. And any guesses about why the classification head largely improves cyclist but no much influence on other categories?

Thanks again for the informative discussion!

**Comment by tianweiy** [comment]
> where the boxes should contain quite a number of points

Then you should try raw lidar point based two stage method to get a sense about the upper bound of regression refinement. 

> And any guesses about why the classification head largely improves cyclist but no much influence on other categories?

I guess it is mainly eliminating false positives. Like maybe in your training set, the cyclist is much less than pedestrians/vehicles, so in real inference, most are false positives. The second stage refinement score may fix some of these. You can visualize those predictions and see. Check this file https://github.com/tianweiy/CenterPoint/blob/master/tools/visual.py

**Comment by XuyangBai** [comment]
Thank you so much. I will do some visualization and try other two-stage methods to find the reasons. 

Best
Xuyang
