### ISSUE TITLE
Support double flip test in two stage method?

### ISSUE THREAD

**Issue by bringBackm** [tianweiy/CenterPoint#127]
I find that only one stage method support double flip test, is there any plan to support two stage~

**Comment by tianweiy** [comment]
In my understanding, double flip testing is only useful for the first stage proposal generation. After that, you just take the combined proposal boxes and refine it with two stage module. 

Moreover, I tend to not use flip testing recently as we already get near top performance for Waymo / nuScenes and the improvement for double flip testing doesn't seem to justify its 4x latency.
