### ISSUE TITLE
Class-balanced Grouping

### ISSUE THREAD

**Issue by XuyangBai** [tianweiy/CenterPoint#130]
Hi @tianweiy On waymo, why do you keep the `['VEHICLE', 'PEDESTRIAN', 'CYCLIST']` in one task instead of dividing them into three tasks like nuScenes? Intuitively, these three categories donot have similar shapes or sizes, so any specific reason for merging them in one group?

**Comment by tianweiy** [comment]
I found that both works similarly one year ago so for speed and simplicity, I just use a single group

**Comment by XuyangBai** [comment]
Thanks!
