### ISSUE TITLE
mAP on nuscenes

### ISSUE THREAD

**Issue by crawfish3** [tianweiy/CenterPoint#131]
Hi @tianweiy , your paper shows 58.0 detection mAP on nuscene test set, while I see 60.3 mAP of centerpoint-single on nuscenes learderboard, so did you perform double flip based on 58.0 and then get 60.3? Thank you.

**Comment by tianweiy** [comment]
in paper, it is single scale, on leaderboard it is flip testing. Please refer to paper number for comparisons.
