### ISSUE TITLE
How can I perform 3D tracking in your code？

### ISSUE THREAD

**Issue by Jiawen-huang** [tianweiy/CenterPoint#137]
I follow your introduction in waymo.md:

I have run 3D detection: python -m tools.dist_test /home/jiawen/CenterPoint/configs/waymo/pp/waymo_centerpoint_pp_two_pfn_stride1_3x.py --work_dir /home/jiawen/CenterPoint/work_dirs/waymo_centerpoint_pp_two_pfn_stride1_3x  --checkpoint /home/jiawen/CenterPoint/work_dirs/waymo_centerpoint_pp_two_pfn_stride1_3x/epoch_36.pth 

I got the file in   work_dirs/waymo_centerpoint_pp_two_pfn_stride1_3x :
 det3d  detection_pred.bin  epoch_36.pth  prediction.pkl

How can I perform 3D tracking in your code？
I run: python -m tools.waymo_tracking.test --work_dir /home/jiawen/CenterPoint/work_dirs/waymo_centerpoint_pp_two_pfn_stride1_3x  --checkpoint /home/jiawen/CenterPoint/work_dirs/waymo_centerpoint_pp_two_pfn_stride1_3x/epoch_36.pth --info_path work_dirs/waymo_centerpoint_pp_two_pfn_stride1_3x/prediction.pkl 

but I get bug:
Deploy OK
Traceback (most recent call last):
  File "/home/daiyaxuan/anaconda3/envs/centerpoint/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/daiyaxuan/anaconda3/envs/centerpoint/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/daiyaxuan/jiawen/CenterPoint/tools/waymo_tracking/test.py", line 263, in <module>
    main()
  File "/home/daiyaxuan/jiawen/CenterPoint/tools/waymo_tracking/test.py", line 90, in main
    infos = reorganize_info(infos)
  File "/home/daiyaxuan/jiawen/CenterPoint/tools/waymo_tracking/test.py", line 68, in reorganize_info
    token = info['token']
TypeError: string indices must be integers

**Comment by tianweiy** [comment]
--checkpoint /home/jiawen/CenterPoint/work_dirs/waymo_centerpoint_pp_two_pfn_stride1_3x/epoch_36.pth --info_path work_dirs/waymo_centerpoint_pp_two_pfn_stride1_3x/prediction.pkl

checkpoint should be the prediction.pkl  info should be the dataset info generated here https://github.com/tianweiy/CenterPoint/blob/master/docs/WAYMO.md

```
# Two Sweep Infos (for two sweep detection and tracking models)
python tools/create_data.py waymo_data_prep --root_path=data/Waymo --split train --nsweeps=2

python tools/create_data.py waymo_data_prep --root_path=data/Waymo --split val --nsweeps=2

python tools/create_data.py waymo_data_prep --root_path=data/Waymo --split test --nsweeps=2
```

**Comment by Jiawen-huang** [comment]
thanks！！！
I run ：
python -m tools.waymo_tracking.test --work_dir /home/jiawen/CenterPoint/work_dirs/waymo_centerpoint_pp_two_pfn_stride1_3x   --checkpoint work_dirs/waymo_centerpoint_pp_two_pfn_stride1_3x/prediction.pkl --info_path data/Waymo/infos_val_02sweeps_filter_zero_gt.pkl 

then the bug：
 File "/home/jiawen/CenterPoint/tools/waymo_tracking/test.py", line 176, in transform_box
    velocity = box[..., [6, 7]] 
IndexError: index 7 is out of bounds for axis 1 with size 7
 
I print the shape of box：(35, 7)

I do not how to slove it????

**Comment by tianweiy** [comment]
Hi, for tracking, you need to use one of the config that also predicts box velocity. Your current config doesn't support this.

**Comment by tianweiy** [comment]
https://github.com/tianweiy/CenterPoint/blob/master/configs/waymo/voxelnet/waymo_centerpoint_voxelnet_two_sweeps_3x_with_velo.py


This one supports velocity prediction (the with_velo in the name)

**Comment by tianweiy** [comment]
You can also get the detection / tracking result by sending me an email with waymo registration screenshot

**Comment by Jiawen-huang** [comment]
thanks！
