### ISSUE TITLE
How to get metrics like mAP in test set

### ISSUE THREAD

**Issue by Jay-9912** [tianweiy/CenterPoint#138]
Hi, tianweiy. When I run dist_test.py on my nuscenes test set, I only get prediction.pkl. How can I get metrics information like metrics_summary.json in my val set. It seems that my infos_test_10sweeps_withvelo_filter_True.pkl lacks gt_boxes information.

**Comment by tianweiy** [comment]
You can't get metrics locally. You need to submit the info_test_XXX.json to the server https://eval.ai/web/challenges/challenge-page/356/evaluation

**Comment by Jay-9912** [comment]
Thanks for quick reply, I will try then.
