### ISSUE TITLE
Rotation Code

### ISSUE THREAD

**Issue by joyfulday222** [tianweiy/CenterPoint#140]
@tianweiy really nice work. I only see the double flip code in the centerhead, so I wonder if you could show the test-time rotation augmentation code on top of the double flip operations?  Thank you!

**Comment by tianweiy** [comment]
right

**Comment by joyfulday222** [comment]
@tianweiy Thank you!

**Comment by StiphyJay** [comment]
> 

Hello. Have you reproduce this rotation trick? Could you share more details?
