### ISSUE TITLE
is ok to use spconv 1.2.1?

### ISSUE THREAD

**Issue by Shaoqing26** [tianweiy/CenterPoint#141]
I wanna know the differ between spconv 1.0 and spconv1.2.1, and is this will affect the accuracy?

**Comment by tianweiy** [comment]
I think it won't hurt

**Comment by tianweiy** [comment]
1.2 consumes less gpu memory to my knowledge

**Comment by Shaoqing26** [comment]
> 1.2 consumes less gpu memory to my knowledge
It is, and there also a question that why don't use nuscense API  replace nuscenes-devikit folder you proved?

**Comment by tianweiy** [comment]
You can use it. A few months ago the nuScenes devkit will download a specific pytorch version which mess up the whole environment. I think this is fixed now

**Comment by tianweiy** [comment]
also, you need to change the nan velocity in offical output to zero

**Comment by Shaoqing26** [comment]
> You can use it. A few months ago the nuScenes devkit will download a specific pytorch version which mess up the whole environment. I think this is fixed now

OK, got it, Thks~~
