### ISSUE TITLE
Did you use Valiation data when train for submission.

### ISSUE THREAD

**Issue by alsun-oven** [tianweiy/CenterPoint#142]

**Comment by tianweiy** [comment]
No

**Comment by alsun-oven** [comment]
when I use the iou threshold 0.7 in test dataset， get the more bbox. Did you use the iou threshold 0.7in test dataset.

**Comment by alsun-oven** [comment]
Did you use Valiation data when train for test dataset submission.

**Comment by tianweiy** [comment]
I didn't change anything between val and test

**Comment by tianweiy** [comment]
Which dataset are you talking about? Are you using my pretrained model for Waymo? In the folder, you can find the model + prediction file. The model is the same as the validation one

**Comment by alsun-oven** [comment]
Thanks
