### ISSUE TITLE
the usage of nuScenes dataset

### ISSUE THREAD

**Issue by ChunmianLin** [tianweiy/CenterPoint#143]
Hi, author. 
I want to know how much nuScenes data (full dataset v1.0) do you use for centerpoint training and validation and construct the following directory? 
Taking 'samples' directory for example, only one subset blob data, e.g. v1.0-trainval01_blobs, is used in the directory 'samples', or the data in different samples directories are extracted from several blobs, e.g. v1.0-trainval01_blobs and v1.0-trainval02_blobs, and then get them together to form a new 'samples' directory?

**Comment by tianweiy** [comment]
it has been a long time since I downloaded the data. But I use the whole dataset so it is probably all the blobs file.
