### ISSUE TITLE
What is the change of fixing sync-bn bug？

### ISSUE THREAD

**Issue by jialeli1** [tianweiy/CenterPoint#146]
Hi.

When I checked the difference between the latest two versions (c9822e1 and 0d09ec9), I did not find any essential changes to the config or code. How do you fix the sync-bn bug or What is the sync-bn bug?

Thanks.

**Comment by tianweiy** [comment]
see https://github.com/tianweiy/CenterPoint/pull/109

basically, originally, in all distributed training with sync-bn, the bn layer is not optimized (always in the initial random state), fixing this gives slight improvements

**Comment by jialeli1** [comment]
Thanks for your reply. It looks like this is an older modification.
