### ISSUE TITLE
Bbox regression target maybe isn't exactly correct?

### ISSUE THREAD

**Issue by Super-Tree** [tianweiy/CenterPoint#147]
Hi tianwei,
I did a experiment based on your code. In training, I only used one frame data which is the first frame data of the first segement,timestamp:1509155241195667. 
I trained 100,000 steps, and making the cls_loss to 0.0001 and reg_loss to 0.0000 which means that this frame should been exactly learned by the model. However, when I visualizes the prediction, I found that all attributes of the objects  matched the groundtruth except the location of `x y` .
![image](https://user-images.githubusercontent.com/24618712/121476419-38af8a00-c9f9-11eb-98df-481d61b13baa.png)
![image](https://user-images.githubusercontent.com/24618712/121476447-41a05b80-c9f9-11eb-89a6-832a1221de4b.png)
Blue represents gts, yellow represents predictions.

The reason I think is the calculation of `x y`targets :
https://github.com/tianweiy/CenterPoint/blob/master/det3d/datasets/pipelines/preprocess.py#L385
https://github.com/tianweiy/CenterPoint/blob/master/det3d/datasets/pipelines/preprocess.py#L391
The way for calculate `x y` targets, cast float number to int , isn't same as the classfication. There is a gap between training and testing process due the mismatch of cls and reg. I think it is better to use  rounding-off method, this will lead a more exactly regression result.

**Comment by tianweiy** [comment]
we still predict an offset here https://github.com/tianweiy/CenterPoint/blob/c9822e1202ff1b197db237d284f546e8cb98d766/det3d/datasets/pipelines/preprocess.py#L410

https://github.com/tianweiy/CenterPoint/blob/c9822e1202ff1b197db237d284f546e8cb98d766/det3d/models/bbox_heads/center_head.py#L397

**Comment by tianweiy** [comment]
"isn't same as the classfication"

what does this mean ?

**Comment by Super-Tree** [comment]
@tianweiy In heatmap calulation, 

> "isn't same as the classfication"
> 
> what does this mean ?

My bad, I think you draw the gaussian kernel using  interpolation method for the value of center of the kernel due to that object's center isn't always a int number.
I just read the code:
https://github.com/tianweiy/CenterPoint/blob/master/det3d/core/utils/center_utils.py#L52
Now, I think the way to calculate `x y` is same for cls and reg.
However, I still think the mismatch between prediction and gt is much due to the center calculation. I will try to find the reason. If you are interest for this, you can do the same experiment which is quite easy.

**Comment by tianweiy** [comment]
Will do after Friday's waymo challenge

**Comment by Super-Tree** [comment]
> Will do after Friday's waymo challenge

By the way, I think fix this problem may lead a small improvement on performance.

**Comment by tianweiy** [comment]
is it still a problem (I see you closed this issue)? I have limited bandwidth so I want to check if I should still look into this ?

**Comment by Super-Tree** [comment]
@tianweiy I found there was a bug in my code which led to the wrong regression. My fault...

**Comment by tianweiy** [comment]
sure, no problem
