### ISSUE TITLE
problem about evaluating

### ISSUE THREAD

**Issue by HzzzW** [tianweiy/CenterPoint#148]
Hi tianwei,

i want to try to use the evaluation for tracking, and i just run as follow:

**python tools/nusc_tracking/pub_test.py   --work_dir work_dirs/ --checkpoint detection_dirs/detection.json**

work_dirs is empty, detection.json from your model zoo:
https://drive.google.com/file/d/1GJzIBJKxg4NVFXF0SeBzmrL87ALuIEx0/view

but the following error was encountered:
KeyError: 'fd8420396768425eabec9bdddf7e64b6'

the code going wrong is as follow in pub_test.py:
`nusc_annos = {
        "results": {},
        "meta": None,
    }
    size = len(frames)

    print("Begin Tracking\n")
    start = time.time()
    for i in range(size):
        token = frames[i]['token']

        # reset tracking after one video sequence
        if frames[i]['first']:
            # use this for sanity check to ensure your token order is correct
            # print("reset ", i)
            tracker.reset()
            last_time_stamp = frames[i]['timestamp']

        time_lag = (frames[i]['timestamp'] - last_time_stamp) 
        last_time_stamp = frames[i]['timestamp']

        preds = predictions[token]

        outputs = tracker.step_centertrack(preds, time_lag)
        annos = []

`
i found the variable size is 6019, but the variable prediction size is 6008.

I don't know where I was wrong what should i do? thank you!

**Comment by tianweiy** [comment]
this file is the test set's detection result. You need to set these two arguments for test set 

https://github.com/tianweiy/CenterPoint/blob/c9822e1202ff1b197db237d284f546e8cb98d766/tools/nusc_tracking/pub_test.py#L29

otherwise, use the val set's predictions

**Comment by HzzzW** [comment]
Where should I download the val set's predictions from? Can you give me a link in detail? I dont know which one i shoulddownload.

**Comment by HzzzW** [comment]
> this file is the test set's detection result. You need to set these two arguments for test set
> 
> https://github.com/tianweiy/CenterPoint/blob/c9822e1202ff1b197db237d284f546e8cb98d766/tools/nusc_tracking/pub_test.py#L29
> 
> https://github.com/tianweiy/CenterPoint/blob/c9822e1202ff1b197db237d284f546e8cb98d766/tools/nusc_tracking/pub_test.py#L30
> 
> otherwise, use the val set's predictions

Where should I download the val set's predictions from? Can you give me a link in detail? I dont know which one i shoulddownload.

**Comment by tianweiy** [comment]
https://drive.google.com/drive/folders/1fAz0Hn8hLdmwYZh_JuMQj69O7uEHAjOh

this should work.

BTW, all links are in this section https://github.com/tianweiy/CenterPoint/blob/master/configs/nusc/README.md#voxelnetdepreacted

**Comment by HzzzW** [comment]
> https://drive.google.com/drive/folders/1fAz0Hn8hLdmwYZh_JuMQj69O7uEHAjOh
> 
> this should work.
> 
> BTW, all links are in this section https://github.com/tianweiy/CenterPoint/blob/master/configs/nusc/README.md#voxelnetdepreacted

I tried and it worked. Thank you for answering my question when you are very busy

**Comment by tianweiy** [comment]
sure, no problem
