### ISSUE TITLE
Help for unreasonable performance when using other epochs (e.g. not the latest.pth) for evaluation

### ISSUE THREAD

**Issue by jialeli1** [tianweiy/CenterPoint#151]
Hi. 

I made some modifications based on your code to adapt to my own database and task. 

When I evaluate the "latest.pth" after the end of training (epoch_20.pth if total epoch is 20), the performance is reasonable. But when I evaluate the previous pth (e.g. epoch_19/18/17.pth), the performance is obviously unreasonable (always close to 0). And during the training process, the loss value is continuously decreasing.

I don't know why and where is the problem? I am very grateful that you can give me some debugging hints.

**Comment by tianweiy** [comment]
I never met this issue. The acc at other epoch 17/18/19 is just slightly lower than 20. I guess there may be some modifications on your side that caused the issue
