### ISSUE TITLE
some questions about parameter initilization.

### ISSUE THREAD

**Issue by hughlee815** [tianweiy/CenterPoint#154]
Hi,

I noticed that the way of initialization of parameters in CenterHead is a little bit uncommon.
1. why do we give a init_bias(-2.19) for the last layer of hm?
`
  if 'hm' in head:
      fc[-1].bias.data.fill_(init_bias)
`
2. why kaiming_init for other layers?
`
  else:
      for m in fc.modules():
          if isinstance(m, nn.Conv2d):
              kaiming_init(m)
`

Could you please give some help about it? Thanks a lot!

**Comment by tianweiy** [comment]
1. This follows from centernet / corner net. Basically we want a small value so after sigmoid, it is close to 0 for the heatmap as the heatmap should be all zero except a few center.
2. You can use any init I guess.

**Comment by hughlee815** [comment]
Thx.
