### ISSUE TITLE
Model dependency on host orientation issue

### ISSUE THREAD

**Issue by akhilperincherry** [tianweiy/CenterPoint#155]
Hi Tianwei,

Great work on the model, the results look really promising. I have a question based on something I've been seeing when I run inference(using `single_inference.py`) on a couple of our velodyne lidar frames. The orientation of the boxes seem to be change when the orientation of the host vehicle changes. I have a couple of questions based on this and the below figures as reference -

- Do you think this is because the network was trained with nuscenes data that has a host vehicle orientation perpendicular to the data that I am using for inference ? Or is it something to do with the coordinate systems difference between nuScenes and the data I am using ? In my system, host vehicle's longitudinal axis is the x axis while the axis perpendicular to the left of this is the y axis. 

- What exactly is the role of [this](https://github.com/tianweiy/CenterPoint/blob/b068b761e2748c5bfb5499f12d30b27cf5429aab/tools/single_infernece.py#L147) line and [this](https://github.com/tianweiy/CenterPoint/blob/b068b761e2748c5bfb5499f12d30b27cf5429aab/tools/demo_utils.py#L59) line ?

- I see that your boxes are 9 dimensional. Are these X,Y,Z,L,W,H,Rotation around X, Rotation around Y, Rotation around Z ? And based on [this](https://github.com/tianweiy/CenterPoint/blob/b068b761e2748c5bfb5499f12d30b27cf5429aab/tools/demo_utils.py#L63), it seems like you're initializing velocity as a tuple with Rx, Ry, 0. What exactly does this mean ? Isn't orientation atan(vy,vx) technically ?

PFA figures below for reference from my inference data. You can see in one figure, orientations of the boxes are off but in the other they're aligned. So, it seems to be a function of the host vehicle orientation, not sure if I am missing something. For these results, I get the inference box from running `single_inference.py`, I used [this](https://github.com/tianweiy/CenterPoint/blob/b068b761e2748c5bfb5499f12d30b27cf5429aab/tools/single_infernece.py#L147) offset as is and then passed it to `_second_det_to_nusc_box(detection)`, but commented out [this](https://github.com/tianweiy/CenterPoint/blob/master/tools/demo_utils.py#L63) offset because my system seems to be perpendicular to that of [NuScenes](https://www.nuscenes.org/nuscenes#data-collection).

Thanks in advance and really appreciate your work. 

![scan_288](https://user-images.githubusercontent.com/22408082/124157498-d5000600-da66-11eb-91b0-5f93bc650f7c.png)
![scan_369](https://user-images.githubusercontent.com/22408082/124157547-e34e2200-da66-11eb-934f-f88ee40bfc74.png)

Best,
Akhil

**Comment by akhilperincherry** [comment]
Actually, I resolved it, it was just a transformation issue and I wasn't sure what coordinate system was being used here but I found [this](https://github.com/tianweiy/CenterPoint/issues/67#issuecomment-760483112) which was really useful to fix my issue.

**Comment by tianweiy** [comment]
sounds good!
