### ISSUE TITLE
Higher PyTorch versions supported?

### ISSUE THREAD

**Issue by henrylee2570** [tianweiy/CenterPoint#156]
Hi,

Thanks for the great work and the code release! I wonder if higher versions of PyTorch have been tested and would there be any compatibility issue?

**Comment by tianweiy** [comment]
I think so long as you can get spconv installed and work with the specific pytorch version, the other part of this codebase is fine (with any version). 

I have tried a lot of pytorch version, the headache is mostly with installing spconv, but after installing it, they should work well...

**Comment by henrylee2570** [comment]
Got it! Yeah I feel the pain... thanks for the quick response!
