### ISSUE TITLE
where does infos_val_10sweeps_withvelo_filter_True.json come from？

### ISSUE THREAD

**Issue by Cc-Hy** [tianweiy/CenterPoint#159]
GOOD JOB!
i have some questions 
① I noticed by running 'tools/create_data.py' can we get the 'infos_train_10sweeps_withvelo_filter_True.pkl' file,
but in the tracking script there is a 'infos_train_10sweeps_withvelo_filter_True.json' file, and i fail to find where its coming from.
i d like to know from where can i create the file. so is the 'frames_meta.json' file and others. 
② whats different between these two .pkl file and the .json file?
③ and id like to know whether the frames in 'frames_meta.json' is  in order like frame 1-40 is from the same scene in time order, 41-80 is from  the second scene in time order... 
i m new at this , thank you !

**Comment by Cc-Hy** [comment]
and so is the 'frames_meta.json' file and others.

**Comment by tianweiy** [comment]
I suppose you are running nuscenes tracking 

1. you can download the precomputed detection file "json" from https://github.com/tianweiy/CenterPoint/tree/master/configs/nusc Specifically, we use centerpoint_voxel_1440_dcn(flip)

2. pkl file contains meta data for each frame and json file is the detection result. 

3. frame_metas.json is computed on the fly in https://github.com/tianweiy/CenterPoint/blob/master/tools/nusc_tracking/pub_test.py 
you can find details here https://github.com/tianweiy/CenterPoint/blob/b068b761e2748c5bfb5499f12d30b27cf5429aab/tools/nusc_tracking/pub_test.py#L38
