### ISSUE TITLE
about iou-aware

### ISSUE THREAD

**Issue by tornadomeet** [tianweiy/CenterPoint#161]
hello, @tianweiy 
the ablation  study in your centernet++ paper says:
![centernet++](https://user-images.githubusercontent.com/5860892/126603847-0dfacd6d-832f-47b4-9bfd-9423f9cdc80f.png)

```IoU Rectification``` can improve 2.5 percent based stage1, so where is  the ```IoU Rectification code``` in https://github.com/tianweiy/CenterPoint ?

i can only found the related one line code in https://github.com/tianweiy/CenterPoint/blob/master/det3d/models/detectors/two_stage.py#L134 , but this is in the second stage.

another, ```beta=1```in your code but ```beta=2``` in your paper.

thanks!

**Comment by tianweiy** [comment]
It is about to be implemented in this pr https://github.com/tianweiy/CenterPoint/pull/157

I will push this part of code today or tomorrow.

**Comment by tornadomeet** [comment]
@tianweiy  great! thanks.

**Comment by tianweiy** [comment]
just, added my implementation in the new_release branch. You can find the modification and corresponding configuration in this commit https://github.com/tianweiy/CenterPoint/commit/13c39d814f790f1232e153d366bd2aff1c0990ac

**Comment by tornadomeet** [comment]
@tianweiy  thanks! 

i have read your iou-aware implementation, it's almost the same with the implementation of mine. but i found it does not help to improve performance on nuscene actually. the reason is:
if not use iou-aware during deploy, we'll use ```score_threshold=0.1``` by default.
if using iou-aware during deploy, we need to reduce ```score_threshold```(such as 0.03),  because we multiplied the predict_iou, which is 0~1, to the heatmap score, so the heatmap score is reduced if compared with it's original output.
and in my experiment without iou-aware, ```score_threshold=0.03``` is also better than(~1 map higher) ```score_threshold=0.1```.

so i doubt that the performance improved from iou-aware,  maybe mostly from reducing the ```score_threshold```.

**Comment by tianweiy** [comment]
could you give some specific results. which config, what do you get with 0.1 / 0.03 score threshold, and with / without iou prediction? 

I never tried nuScenes + iou prediction, so not really sure about that. For Waymo, I think reducing to 0.03 score threshold won't matter too much and iou prediction does gives some improvement

**Comment by tianweiy** [comment]
I see. I didn't try point pillars in the past. According to my two stage result, PointPillars + two stage (which include iou prediction) also doesn't improve much. 

Overall, I still believe IoU prediction is still kind of useful at least in the tech report's specific setting (VoxelNet + Waymo dataset which gets dense point clouds)

**Comment by tornadomeet** [comment]
@tianweiy  thanks, get it.  i'll try this on waymo dataset in the furture.
