### ISSUE TITLE
Question about the changes of IoU-aware confidence rectification from the original implementation.

### ISSUE THREAD

**Issue by yukke42** [tianweiy/CenterPoint#162]
Thank your for sharing the new release paper and codes!

I read your and the original implementation of IoU-aware confidence rectification, and I found two changes.
- predicted iou isn't encoded from [0, 1] to [-1, 1]
- use l1 loss instead of smooth l1 loss

Is there any reason?

**Comment by tianweiy** [comment]
You can try the original one, I think the performance should be similar. I only get time to train one model before the challenge and I choose the current setting. I use L1 loss only because it is kind of the standard of all my projects

**Comment by yukke42** [comment]
@tianweiy Thank you!
