### ISSUE TITLE
Question about parameter of gaussian heatmap

### ISSUE THREAD

**Issue by Angericky** [tianweiy/CenterPoint#164]
Hello,  
   In gaussian2D((diameter, diameter), sigma=diameter / 6) to generate the gaussian heatmap, you set sigma as diameter / 6.
   Why did you set this value ` diameter / 6 ` as the standard deviation of gaussian distribution?

Thanks

**Comment by tianweiy** [comment]
Hi, thanks for the interest. 

I follow the gaussian map radius definition from CenterNet https://github.com/xingyizhou/CenterNet and CornerNet
