### ISSUE TITLE
Waymo pretrain 

### ISSUE THREAD

**Issue by DongfeiJi** [tianweiy/CenterPoint#167]
Is there a pretrained model for waymo pilliar

**Comment by tianweiy** [comment]
please send me an email with informations described here https://github.com/tianweiy/CenterPoint/blob/master/configs/waymo/README.md#waymo-3d-detection

**Comment by cyhasuka** [comment]
Hi, @tianweiy 
I have sent the relevant documentation to your MIT email address to prove that I agree with the rules for the use of the waymo dataset, but have not yet received a reply, and I wonder if it is the email that is being filed in the spam folder.
I'd like a copy of your .pth file to learn your excellent algorithms.
Sincerest thanks!
Look forward to your reply!
