### ISSUE TITLE
GT-AUG strategy bug (may be)

### ISSUE THREAD

**Issue by majaya** [tianweiy/CenterPoint#175]
Hi tianweiy,

Thank you for sharing the extraordinary  work!!!

Now I has some questions: 
(1) Did you find some thing wrong when using db_sampler, in CenterPoint/det3d/core/sampler/sample_ops.py line 190: 
![image](https://user-images.githubusercontent.com/37564415/129690864-4b4924e6-3c4d-4cef-8dbd-ca9f68bc0b0d.png)
why we use s_points[:, :3] += info["box3d_lidar"][:3] this code, is it right, when I draw pointcloud and it's gt ,if you use this code ,the pointcloud can't match gt (of course , points translate along xyz from gt location), is it a bug or some aug strategy, please check. the result is when I use db_sampler, more false detection occured.
(2) when I use CenterPoint to train my own dataset, I found the rotation of the detection box is unstable, when we test continuous frame scene， some boudingbox might deflection left and right， I work for anchor based PointPillar for long time，and I do not find this problem（although the mAP is lower than centerpoint), is there a common problem or I just made some wrong config, needs some help thanks.

**Comment by tianweiy** [comment]
Answer to question 1. 

This part is right. We have a transformation when we generate the gt database https://github.com/tianweiy/CenterPoint/blob/a3fad4201c5610aa456dfd2d513516579b88ac79/det3d/datasets/utils/create_gt_database.py#L127 so now we transform it back.

Question 2:

I don't think it is a common problem. You can try increasing the orientation loss weight.

**Comment by majaya** [comment]
thank you for all of you advice , I will try!
