### ISSUE TITLE
sparse_shape = np.array(input_shape[::-1]) + [1, 0, 0]

### ISSUE THREAD

**Issue by xuetaohao1994** [tianweiy/CenterPoint#176]
Hi. Could I know if any specific reason that we need add **1** for z axis sparse shape ? 
When I comment **# + [1, 0, 0]** and use different padding, it still works.

Thank you very much for explanation.

**Comment by tianweiy** [comment]
which line of code ?

**Comment by xuetaohao1994** [comment]
> which line of code ?

Thank you for the reply. I attached the link: https://github.com/tianweiy/CenterPoint/blob/master/det3d/models/backbones/scn.py#L151

**Comment by tianweiy** [comment]
I copied this line from previous repos. I think it is used for a batch dimension. I suggest we just leave it as it is now

**Comment by xuetaohao1994** [comment]
I try to remove this and change padding. It can give me same performance in 1.0-trainval dataset.
