### ISSUE TITLE
Segmentation fault (core dumped) on Waymo

### ISSUE THREAD

**Issue by nullkatar** [tianweiy/CenterPoint#177]
Hello @tianweiy, thanks a lot for your work! I have a question regarding training on my own data. I simply added instances during data preparation stage. In more details: I'm running a model of your on Waymo and I added  in `det3d/datasets/waymo/waymo_converter.py` I added a little bit of code which adds cars, bicycles and  pedestrians. The thing is that 

```
CUDA_VISIBLE_DEVICES=-1 python det3d/datasets/waymo/waymo_converter.py --record_path 'WAYMO_DATASET_ROOT/tfrecord_training/*.tfrecord'  --root_path 'WAYMO_DATASET_ROOT/train/'
```
```
python tools/create_data.py waymo_data_prep --root_path=data/Waymo --split train --nsweeps=1
```

gives me no issues, but while training the model does not starts. These are last messages which appears on my screen:
```
        (dim): Sequential(
          (0): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU()
          (3): Conv2d(64, 3, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
        (rot): Sequential(
          (0): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU()
          (3): Conv2d(64, 2, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
        (hm): Sequential(
          (0): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU()
          (3): Conv2d(64, 3, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
      )
    )
  )
)
2021-08-18 17:08:20,842 - INFO - Start running, host: josh94mur@cds2, work_dir: ./work_dirs/waymo_centerpoint_pp_two_pfn_stride1_3x
2021-08-18 17:08:20,843 - INFO - workflow: [('train', 1)], max: 36 epochs
2021-08-18 17:08:25,458 - INFO - finding looplift candidates
Segmentation fault (core dumped)

```
Can you please say if there is any solutions to that problem which you may think about?  I understand that it is some kind of internal pytorch issue, but I just want to hear any idea from you about adding these instances into the dataset. Everything I did is picked precisely data from Waymo, and added it in other places. The only code which I modified is `waymo_converter.py`. Do you think if these additional instances should be added anywhere else?

**Comment by tianweiy** [comment]
Hi, I don't have any idea in mind. 

> I added a little bit of code which adds cars, bicycles and pedestrians. 

Can you explain this in more details? This seems to be the problem ...

> Can you please say if there is any solutions to that problem which you may think about?

I have no way to debug this given the current error message. I suggest you to add a print statement to locate the error. I guess it is near the dataset files

**Comment by sissini** [comment]
didi u solved the problem? i have the same problem 'Segmentation fault (core dumped) ',  wenn process waymo dataset. holp for your help

**Comment by sissini** [comment]
didi u solved the problem? i have the same problem 'Segmentation fault (core dumped) ', wenn process waymo dataset. holp for help

**Comment by nullkatar** [comment]
Hello @sissini, Yes, I solved it. The problem was in somehow incorrectly loaded data, its types were incorrectly read. If I were you I would just put `.float()` after each load of file in the program you are running (in my case it was `waymo_converter.py`).
