### ISSUE TITLE
Nuscenes Readme 

### ISSUE THREAD

**Issue by DongfeiJi** [tianweiy/CenterPoint#179]
I can see that in nuscenes config readme, 
voxel has two eval scores, 
one is before the bug is fixed, and the other is after the bug is fixed. 
What bug is fixed？
### VoxelNet 
| [centerpoint_voxel_1440](voxelnet/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z.py) |59.6  | 66.8 | [URL]
### VoxelNet(depreacted) 
These results are obtained before the bug fix. 
| [centerpoint_voxel_1024](voxelnet/nusc_centerpoint_voxelnet_01voxel.py) | 16 | 56.4 | 64.8 | [URL](https://drive.google.com/drive/folders/1RyBD23GDfeU4AnRkea2BxlrosbKJmDKW?usp=sharing) |

**Comment by tianweiy** [comment]
see https://github.com/tianweiy/CenterPoint/issues/169
