### ISSUE TITLE
Cannot reproduce detection results of "centerpoint_voxel_1440_dcn(flip)"

### ISSUE THREAD

**Issue by Peterbotliang** [tianweiy/CenterPoint#180]
Hi,

I am trying to reproduce the detection results using the provided trained models. Now I am able to obtain exactly the same detection boxes for "centerpoint_voxel_1440", but not the case for the deprecated setting "centerpoint_voxel_1440_dcn(flip)". Are there some changes in the model?

**Comment by tianweiy** [comment]
Please use this config https://github.com/tianweiy/CenterPoint/blob/master/configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_dcn_flip.py 
I will update the link

**Comment by Peterbotliang** [comment]
Thank you for your prompt reply!
