### ISSUE TITLE
the point range and voxel size of the custom data

### ISSUE THREAD

**Issue by clytze0216** [tianweiy/CenterPoint#181]
hi, Thanks for your nice work!
I want to train with my own data on the CenterPoint-KITTI. I change the point range size :[-140.8,-80,-3,140.8,80,1] and the voxel size:[0.1,0.05,0.5] to match my data range.
But when I started training, I found that the loss of the model could not drop, and no results could be detected. I would like to ask if you want to modify the point cloud scope to adapt to your own data, which content should be modified? My most sincere thanks in advance !!

I am looking forward to your reply, which is very important to me. Thank you!

**Comment by tianweiy** [comment]
replied in the other repo
