### ISSUE TITLE
Video display of results 

### ISSUE THREAD

**Issue by HLL-TXX** [tianweiy/CenterPoint#182]
Hi,
After I ran dist_test.py, I found that the visualization of the test results was a few frames of discontinuous images. What should I do if I want the detection result to be displayed like a video with adjacent frames? thanks.

**Comment by tianweiy** [comment]
How do you visualize it ? Do you write some custom code ? In that case, you may need some sorting to make it continuous. Additionally, assuming you are using nuScenes, their frame rate is 2 FPS so it won't look that continuous

**Comment by akhilperincherry** [comment]
@tianweiy Do you think #172 could solve this ?

**Comment by tianweiy** [comment]
I am waiting for the original poster to explain the details

**Comment by HLL-TXX** [comment]
Thanks for your reply. Inspired by you, I have solved this problem.
