### ISSUE TITLE
data augmentation-ground-truth sampling

### ISSUE THREAD

**Issue by HuangVictorAuto** [tianweiy/CenterPoint#184]
Hi, Tianwei. I read you paper for CenterPoint++. "We adopt ground-truth sampling [15] on Waymo to deal with the long tail class distribution, which copies and pastes points inside an annotated box from one frame to another frame."
how did you handle the time_lag dimension? Thanks in advance!

**Comment by HuangVictorAuto** [comment]
Thanks for your quick reply! The database points for multi sweep was collected as :
**point_indices = box_np_ops.points_in_rbbox(points, gt_boxes)**
points = sensor_data["lidar"]["combined"], all points stacked together with time
annos = sensor_data["lidar"]["annotations"] , gt_boxes = annos["boxes"] ,the gt_boxes is for the current frame
yes, the points will already contains multi-frame point cloud with the time_lag feature. But only partial for previous frame, because the gt_boxes is only for current frame. Is my understanding correct? I don't know whether this will enfluence db-sampler effect.
Thank you in advance!

**Comment by tianweiy** [comment]
you are right. it is only partial. I guess we can do some interpolation to get box location in previous frame and then crop the point cloud. I don't know if this will be better
