### ISSUE TITLE
'Create data' is running in the CPU

### ISSUE THREAD

**Issue by turtleMaster20** [tianweiy/CenterPoint#186]
I downloaded the entire NuScenes dataset and am trying to create the data for the package.

When I checked the CPU and the GPU usage the CPU Usage seems very high and the GPU seems to be not used. Further the processing (or training) has been going on about two hours in the time of writing.

Images Uploaded:

1. CPU Usage
2. Training Image
3. GPU Usage

![cpu_cp](https://user-images.githubusercontent.com/71133902/131840177-0b4b88e7-e3c7-4ea2-9274-03e44bb88fc9.png)
![create_cp](https://user-images.githubusercontent.com/71133902/131840181-0b366561-6d5b-438d-983b-b4941c0b7278.png)
![gpu_cp](https://user-images.githubusercontent.com/71133902/131840183-4295b6b3-4e37-498a-8b7c-edf5acb8cea7.png)

**Comment by tianweiy** [comment]
When I checked the CPU and the GPU usage the CPU Usage seems very high and the GPU seems to be not used. Further, the processing (or training) has been going on for about two hours in the time of writing.

Now, it is generating the gt database. All the operations (mainly write files to disk) indeed happens on the CPU. A few hours seems reasonable.

**Comment by turtleMaster20** [comment]
Took 11 hours but it worked...thanks

**Comment by tianweiy** [comment]
tbh It mainly depends on the disk speed. It is less than 1 hr on our side
