### ISSUE TITLE
nms doubts for centerpoint two stage

### ISSUE THREAD

**Issue by HuangVictorAuto** [tianweiy/CenterPoint#187]
Hi, Tianwei, sorry to bother you again. I tried to implement the two stage method on OpenPcdet. I have two questions.
**First, why you didn't use the max pooling but the nms gpu for first stage post processing?**
       As mentioned in CenterNet paper. One of the main advantage of CenterNet is to left out the computational nms process. 
       But when I check your cfgs, you use nms-gpu instead. I wonder what is your consideration about this?
      
      "The peak keypoint extraction serves as a sufficient NMS alternative and can be implemented efficiently on device using a 3 × 3 max pooling operation." 
      
      "nms=dict(
              use_rotate_nms=True,
              use_multi_class_nms=False,
              nms_pre_max_size=4096,
              nms_post_max_size=500,
              nms_iou_threshold=0.7,
          )"

**Second, why no nms is needed for second stage post processing?**
    "# currently don't need nms 
                pred_dict = {
                    'box3d_lidar': box_preds,
                    'scores': scores,
                    'label_preds': labels,
                    "metadata": batch_dict["metadata"][index]
                }
    "
Thanks in advance!

**Comment by tianweiy** [comment]
>  First, why you didn't use the max pooling but the nms gpu for first stage post processing?

We can't use max pooling as the object size in 3d is relatively small and only occupy one or two voxel in the final feature map. Maxpooling will suppress objects in a crowd.

> No nms in second stage

In early experiments, this one doesn't improve performance so I leave it out

**Comment by HuangVictorAuto** [comment]
Thank you for your info!
