### ISSUE TITLE
Changing point cloud range to run inference

### ISSUE THREAD

**Issue by akhilperincherry** [tianweiy/CenterPoint#188]
Hi @tianweiy!

I have a lidar data where 10 lidar scans (10FPS setting) are accumulated in a rolling manner. The origin for the entire data is the location of host vehicle in the first frame of the data. So, I find that the default range values [here](https://github.com/tianweiy/CenterPoint/blob/master/configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_dcn.py#L141) would need to be changed to cover more area around the vehicle in my case since the origin is not the current vehicle position in my case. However, if I only change the point cloud range without changing voxel size, I get tensor mismatch error.

From what I understand, in the config file I pointed above, the resulting voxel map shape is (1440, 1440, 40) where 1440 = (54+54)/0.075 and 40 = 8/0.2. If I change the point cloud range but also change the voxel size accordingly to obtain a resulting map shape of (1440, 1440, 40) eg: 216/0.150 = 1440, then the data flows through the model for inference.

Does this mean, the network expects input data to be size (1440, 1440, 40) and if I need different map shapes, I would need to re-train ?

Also, I see another config file [here](https://github.com/tianweiy/CenterPoint/blob/master/configs/nusc/voxelnet/nusc_centerpoint_voxelnet_01voxel.py#L137) where the voxel map shape is (1024, 1024, 40). Is this config for a model that was trained with different point cloud ranges ?

Thanks in advance!

**Comment by tianweiy** [comment]
Does this mean, the network expects input data to be size (1440, 1440, 40) and if I need different map shapes, I would need to re-train ?

Yes

Also, I see another config file here where the voxel map shape is (1024, 1024, 40). Is this config for a model that was trained with different point cloud ranges ?

it is trained with the corresponding range and voxel size
```
    range=[-51.2, -51.2, -5.0, 51.2, 51.2, 3.0],
    voxel_size=[0.1, 0.1, 0.2],
```

**Comment by akhilperincherry** [comment]
Thanks @tianweiy, that makes sense. On an unrelated note, do you think we can merge #172 or is there something that needs to be changed in it ?
