### ISSUE TITLE
Waymo Readme is val or test

### ISSUE THREAD

**Issue by DongfeiJi** [tianweiy/CenterPoint#189]
In CenterPoint\configs\waymo\README.md
it shows centerpoint poinpilliars 3 class result（60.3maph）
 is it on val set or test set？

**Comment by tianweiy** [comment]
Val

**Comment by DongfeiJi** [comment]
> Val

For waymo dataset has v1.0 and v1.2, is it on v1.0?
Because i eval your pred bin, centerpoint waymo popintpilliar got maph 59.64, but in readme it is 60.3.
More, could u please give me your val set gt bin?

**Comment by tianweiy** [comment]
it is v1.2 (latest one)

you can find detailed stats here https://waymo.com/open/challenges/entry/?timestamp=1608651205573400&challenge=DETECTION_3D&email=yintianwei@utexas.edu&submissionType=VALIDATION

I don't use val set gt bin recently. I would suggest submitting to the server. It is fast (< 30minute for eval)

**Comment by tianweiy** [comment]
>  Because i eval your pred bin, centerpoint waymo popintpilliar got maph 59.64, but in readme it is 60.3.

I can check this

**Comment by DongfeiJi** [comment]
> > Because i eval your pred bin, centerpoint waymo popintpilliar got maph 59.64, but in readme it is 60.3.
> 
> I can check this
Yes, i eval your pred bin offline, i will try it online, thanks for your reminding.
Please let me know if u have any news

**Comment by tianweiy** [comment]
I just evaluated the file on the server, results are here https://waymo.com/open/challenges/entry/?timestamp=1608651205573400&challenge=DETECTION_3D&email=yintianwei@utexas.edu&submissionType=VALIDATION

summary: it is 60.2 which is quite close to 60.3. I guess there may be some tiny differences but the overall results seem right

**Comment by DongfeiJi** [comment]
> I just evaluated the file on the server, results are here https://waymo.com/open/challenges/entry/?timestamp=1608651205573400&challenge=DETECTION_3D&email=yintianwei@utexas.edu&submissionType=VALIDATION
> 
> summary: it is 60.2 which is quite close to 60.3. I guess there may be some tiny differences but the overall results seem right

Thanks, there may be bugs in my eval code.

**Comment by DongfeiJi** [comment]
> it is v1.2 (latest one)
> 
> you can find detailed stats here https://waymo.com/open/challenges/entry/?timestamp=1608651205573400&challenge=DETECTION_3D&email=yintianwei@utexas.edu&submissionType=VALIDATION
> 
> I don't use val set gt bin recently. I would suggest submitting to the server. It is fast (< 30minute for eval)

Hi~ After i upload pred bin file to the surver on web，
it shows no No submission information when i press view submission.
Have u seen this problem?
More, how do u submit to the server?
Thanks for your kindness.

**Comment by tianweiy** [comment]
could you take a screenshot

**Comment by tianweiy** [comment]
I submit it to the server here 

![image](https://user-images.githubusercontent.com/38497390/132160785-9797a588-0e8c-4066-898f-a35d5725fe38.png)

**Comment by tianweiy** [comment]
> Hi~ After i upload pred bin file to the surver on web，

Oh, you should not directly upload the bin file. You need to convert the bin file to the submission file. Instructions are here https://github.com/waymo-research/waymo-open-dataset/blob/master/docs/quick_start.md#submit-to-leaderboard-for-perception-tasks-only

**Comment by DongfeiJi** [comment]
> > Hi~ After i upload pred bin file to the surver on web，
> 
> Oh, you should not directly upload the bin file. You need to convert the bin file to the submission file. Instructions are here https://github.com/waymo-research/waymo-open-dataset/blob/master/docs/quick_start.md#submit-to-leaderboard-for-perception-tasks-only

Thank you so much！！！I was stupid :）

**Comment by DongfeiJi** [comment]
> I just evaluated the file on the server, results are here https://waymo.com/open/challenges/entry/?timestamp=1608651205573400&challenge=DETECTION_3D&email=yintianwei@utexas.edu&submissionType=VALIDATION
> 
> summary: it is 60.2 which is quite close to 60.3. I guess there may be some tiny differences but the overall results seem right
Hi~
I also submitted the bin you gave me(email apply) to the server, which is 59.64， compared with yours 60.3.
（i also use the model to inference, it is also 59.64）
Is there a problem with the bin on the network disk
https://waymo.com/open/challenges/entry/?timestamp=1630918836773316&challenge=DETECTION_3D&emailId=32b2600f-b2d3&submissionType=VALIDATION

**Comment by tianweiy** [comment]
That's weird. I also used the bin in the drive for the submission yesterday.
