### ISSUE TITLE
Tracking is working with NuScenes but strange error occurs

### ISSUE THREAD

**Issue by turtleMaster20** [tianweiy/CenterPoint#190]
The Tracking seems to be working with nuScenes but still an error occurs.

Code:

 `python3 tools/nusc_tracking/pub_test.py --work_dir work_dirs/nusc_0075_test --checkpoint detection.json --version v1.0-test --root data/nuScenes/v1.0-test`

Error:

![tracking_error](https://user-images.githubusercontent.com/71133902/132125058-380d103e-bed9-4e5c-96a0-43f07ece51c7.png)

**Comment by tianweiy** [comment]
Hi, after generating the prediction files, you need to submit to the eval server to get results for the **test** set. 

The evaluation code can only evaluates val set locally
