### ISSUE TITLE
Are the detection (and tracking) results for nuScenes test set generated from the latest model of "centerpoint_voxel_1440_dcn(flip test)"?

### ISSUE THREAD

**Issue by Peterbotliang** [tianweiy/CenterPoint#192]
As title. I am curious as I hope to have all results coming from the same model.

P.S. For "latest model", I mean the one that has 66.5 AMOTA and 0.567 AMOTP on the validation set.

**Comment by tianweiy** [comment]
Hi, the CenterPoint-Single entry (for both detection and tracking) is generated from "centerpoint_voxel_1440_dcn(flip test)"

**Comment by Peterbotliang** [comment]
Hi, I am confused as you mentioned "The numbers are from an old version of the codebase. Current detection models should perform slightly better." 

I also generate detection results for the test set using the model provided in "centerpoint_voxel_1440_dcn(flip test)" but they are slightly different from the ones in the model zoo. I am not sure if there is a bug or they are indeed from different models.

**Comment by tianweiy** [comment]
what number do you get? (so that I can guess what is the problem)

**Comment by Peterbotliang** [comment]
I didn't submit it to the evaluation server. I just plot the detection boxes and find that they are different.

I remember that months ago the entry of "centerpoint_voxel_1440_dcn(flip test)" has 65.9 AMOTA. I am not sure if there is a change in the model.

**Comment by tianweiy** [comment]
Hi, I think the current detection model is different from the one we used for the tracking submission. The story is like 

2020 May: we submit something to detection / tracking leaderboard 
2020 June- Dec: Some refactoring and retrain model 
2021 Jan: release 

I think you can compare with the model on the val set. For test set, you can either use this 63.8 number or you can try to generate it using our model and do a submission.
