### ISSUE TITLE
Running time of CenterPoint

### ISSUE THREAD

**Issue by XuyangBai** [tianweiy/CenterPoint#193]
Hi @tianweiy Thanks for sharing the excellent work. I am trying to evaluate the running time of CenterPoint on the NuScenes dataset. I use the CenterPoint implementation and benchmark script in mmdet3d and find the FPS on my V100 GPU is only about **4.6 FPS**. I use `centerpoint_0075voxel_second_secfpn_circlenms_4x8_cyclic_20e_nus.py` (7.5cm voxel size, circle NMS, no dcn). While I find in your repo, even with dcn, CenterPoint with 7.5 voxel size and circle NMS could run as **11 FPS**. Have you ever compare the implementation detail of mmdet3d and your repos and any ideas on the speed difference?

Best,
Xuyang

**Comment by tianweiy** [comment]
Thanks for the interest. I think the network structure should be similar but I never compare the speed breakdown yet. Maybe, you can benchmark each module's speed and do a comparison. I suspect the following modules may be slow 
1. voxelization (they use their custom cuda code for this if I remember exactly)
2. their 3d conv backbone 
3. postprocessing (the circle nms is actually slow for both repos especially when the #boxes get larger. I didn't use it in recent version)

**Comment by XuyangBai** [comment]
Thanks a lot for the reply. I will try to find the speed bottleneck of mmdet3d. 

Best,
Xuyang

**Comment by XuyangBai** [comment]
Hi @tianweiy  Sorry to reopen this issue. I try to breakdown the running time of CenterPoint-Voxel in mmdet3d on nuScenes (with 10 sweeps and 7.5 cm voxel size). The results are as follow:

- voxelization: 185ms
- sparse conv backbone: 52.3ms
- SECOND +SECONDFPN: 8.1ms
- detection head: 9.7ms
- post-processing: 13.5ms 

So it seems the marjor bottleneck is the voxelization part. In your report for CenterPoint++ submission, I find the voxelization only takes about 2ms, may I ask how do you perform the voxelization?  I have tried to replace the voxelization in mmdet3d by `VoxelGenerator` in `det3d/core/input/voxel_generator.py` but this only reduces the voxelization time by about 10ms. Any mistakes might I make? Thank you in advance. 

Best,
Xuyang

**Comment by XuyangBai** [comment]
Hi, I just try `spconv.util.VoxelGeneratorV2` and the voxelization time reduces to 23ms :)  Still much slower than 2ms. Any idea on the reasons? My spconv version is `1.2.1`

**Comment by tianweiy** [comment]
The speed up is due to dynamic voxelization. You can check this file to get an idea https://github.com/tianweiy/CenterPoint/blob/new_release/det3d/models/readers/dynamic_voxel_encoder.py

**Comment by tianweiy** [comment]
For further speedup. I noticed that recent torch version will be slightly faster + spconv 2.x is much faster (though not sure if there are bugs in computation ... ) + You can try fp16(I notice that if the final head is in fp32, the other layers in fp16, the accuracy won't drop on Waymo)

**Comment by XuyangBai** [comment]
Thanks a lot for the quick reply and suggestions!
