### ISSUE TITLE
Doubts about regressing to the velocity 

### ISSUE THREAD

**Issue by LSQsjtu** [tianweiy/CenterPoint#194]
I found after detection, the model produce the box which has the attribute of velocity. But the input is the data_batch which only has the information of one frame. The data_batch isn't a temporal sequence. In the paper, it introduced "In our implementation, we transform and merge points from previous frames into the current reference frame and predict the difference in object position between the current and the past frame normalized by the time difference (velocity)". Are the transforming and merging points from previous frames into the current reference frame done during the data preparing time?

**Comment by tianweiy** [comment]
the points in data_batch is already multi sweep point cloud. See https://github.com/tianweiy/CenterPoint/blob/fb4806f057dbbb1f8d9a201f7c73f7923399abeb/det3d/datasets/pipelines/loading.py#L133
