### ISSUE TITLE
how was the weight (between hm and loc loss) is determined?

### ISSUE THREAD

**Issue by you4ever** [tianweiy/CenterPoint#196]
the "weight" parameter to CenterHead is set to 0.25 and 2.0 for nusc dataset and waymo, respectively. Wonder how was that determined and what's the considerations when choosing the right weight?

**Comment by tianweiy** [comment]
in some earlier version of the codebase, the nuScenes model seems to be sensitive to the weight parameter so we did some grid search (0.125/ 0.25 / 0.5 /1 / 2) and find this to be the best one. 

For Waymo, we use the default parameter following previous works (SECOND, PVRCNN)

**Comment by you4ever** [comment]
great to know! followup question: what's the root cause of sensitivity to this weight for nusc dataset while not so much for waymo? is that because of the dataset or network architecture/parameters?

**Comment by tianweiy** [comment]
the network is the same. I think the main reason is that the evaluation metric is different. nuScenes metric heavily weights the heatmap prediction as bird-eye view center-distance based map counts for 50% of the final score, so we don't really need to do the other attribute regression too well. On the other hand, Waymo uses map based on 3D IoU and the metric tends to focus more on the box regression (shape, exact location)

**Comment by you4ever** [comment]
thanks a lot for the explanation -- that makes a lot of sense. so if I understand correctly in either of the two cases (weight = 0.25 or 2.0) the network should give some reasonable results. I'm asking because I'm running into some issues when I try to adapt the network to some other problem. the issue I have is the heatmap degenerates to all zeros and won't improve. based on your explanation seems this weight is not a major issue.

**Comment by tianweiy** [comment]
yeah, they should give reasonable result in both case.  

> the issue I have is the heatmap degenerates to all zeros and won't improve

You can try to set reg weight to 0 for debugging? Maybe also check your heatmap target
