### ISSUE TITLE
Are the models trained in an end-to-end manner?

### ISSUE THREAD

**Issue by wusize** [tianweiy/CenterPoint#197]
Is the error in the 2nd stage backpropagated to the 1st stage? Or are the two stages trained separately?

**Comment by tianweiy** [comment]
it is trained separately. The model is frozen during the training of second stage https://github.com/tianweiy/CenterPoint/blob/fb4806f057dbbb1f8d9a201f7c73f7923399abeb/det3d/models/detectors/two_stage.py#L27 

The main reason is that we originally work on the first stage models and already have pertained model for this. To add a second stage, we find that the model is more sensitive to lr schedule if we train together so we decided to freeze the backbone weights and only train the second stage.
