### ISSUE TITLE
How to run single fram in nuScenes dataset?

### ISSUE THREAD

**Issue by LSQsjtu** [tianweiy/CenterPoint#199]
Hi! Can I run [single_infernece.py](https://github.com/tianweiy/CenterPoint/blob/master/tools/single_infernece.py) with the checkpoint and config file in the [MODEL ZOO](https://github.com/tianweiy/CenterPoint/blob/master/configs/nusc/README.md)?
 Or can I create date using `python tools/create_data.py nuscenes_data_prep --root_path=NUSCENES_TRAINVAL_DATASET_ROOT --version="v1.0-trainval" --nsweeps=1`? 
And then am I able to run the training that only uses the lidar files in the 'samples' folder and not use the lidar files in the 'sweeps' folder？
I will appreciate for you replying!

**Comment by tianweiy** [comment]
> Hi! Can I run single_infernece.py with the checkpoint and config file in the MODEL ZOO?

Not sure, I didn't use the single_inference.py for a long time but I guess so. 


> And then am I able to run the training that only uses the lidar files in the 'samples' folder and not use the lidar files in the 'sweeps' folder？

Yes, you also want to set nsweep to 1 if you only want to use a single sweep (in the samples) folder https://github.com/tianweiy/CenterPoint/blob/1acc72ac7f1e9e21d0c38a2c4353e8b97f343336/configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z.py#L87

**Comment by LSQsjtu** [comment]
Thanks a lot for your reply! I have another question that if I only want to only use the data in v1.0-trainval01_blobs.tgz, can I change  the code or the sample.json and sample_data.json to slove the bug?

**Comment by tianweiy** [comment]
I never tried this but you can try. (I guess you also need to tweak the devkit)

**Comment by palas21** [comment]
Hi @LSQsjtu, have you tried to run the inference with v1.0-trainval01_blobs.tgz? I am trying to use a partition of the dataset to obtain detection results. If you could give a little heads up, it would be perfect.

**Comment by palas21** [comment]
To be able to use a partition of the dataset, you need to determine which scenes are you going to use with scene-ids. Than, in nuscenes-devkit you can go to python-sdk/utils/splits.py and than according to which part of the dataset are you going to use (trainval, test, mini etc.) you need to delete the other scenes-ids in that array. You can see the example for trainval01 split here: 

![Image](https://github.com/user-attachments/assets/df5d6e09-8fa8-47a6-ad6b-0a1fd7aa613e)
