### ISSUE TITLE
Centerpoint-voxelnet on cpu

### ISSUE THREAD

**Issue by muralipv18** [tianweiy/CenterPoint#201]
I need to run the centerpoint-voxelnet model on cpu.  I changed the code to run on cpu but i'm getting below error.
"boxes must be CUDA tensor at /.../det3d/ops/iou3d_nms/src/iou3d_nms.cpp:93".
Can anyone knows how to run the model on cpu?

**Comment by tianweiy** [comment]
it only works with gpu
