### ISSUE TITLE
How to install apex?

### ISSUE THREAD

**Issue by LSQsjtu** [tianweiy/CenterPoint#202]
When I install APEX, the errors occurs. It says that the version of CUDA isn't suitable for apex. I want to use multi-GPU to run the task. Can I use cuda-11.1 and install the right version of apex? Otherwise, does it means I am only allow to use cuda-8.0 mentioned here [https://github.com/tianweiy/CenterPoint/blob/master/docs/INSTALL.md#cuda-extensions](https://github.com/tianweiy/CenterPoint/blob/master/docs/INSTALL.md#cuda-extensions)

**Comment by tianweiy** [comment]
you can use any Cuda so long as you are able to compile apex.

**Comment by LSQsjtu** [comment]
Thanks a lot! I successfully installed apex. But when I try to import apex, errors happened.
![20211001152320](https://user-images.githubusercontent.com/59142188/135581811-81b54332-4037-47f2-bf24-61fd2f1b5901.png)
I use cuda-11.1 and pytorch1.9.
It seems the version of pytorch doesn't match.

**Comment by tianweiy** [comment]
https://github.com/NVIDIA/apex/issues/186#issuecomment-472337874

**Comment by LSQsjtu** [comment]
I really appreciate your reply. It works now.

**Comment by LSQsjtu** [comment]
Sorry to bother you again. In my laboratory, the GPU A100 isn't compatible with cuda10.0 and pytorch1.1. So if I want to use pytorch1.9 and cuda11.1. What changes should I do in the  [INSTALL](https://github.com/tianweiy/CenterPoint/blob/master/docs/INSTALL.md)?
The ops and the version of apex and spconv need to change. But I have no sense how to change. Do I need to use the latest version of apex and spconv？

**Comment by tianweiy** [comment]
you should use the latest spconv. It takes far less memory than the old version and seems faster.

for apex, I am not sure, I guess you can try the old one or the latest one and see which one you can compile.
