### ISSUE TITLE
Plot Bounding Boxes over 6 Camera Images and Publish to ROS Topics to be Visualized in Rviz

### ISSUE THREAD

**Issue by iamsiddhantsahu** [tianweiy/CenterPoint#21]
@tianweiy @muzi2045 From the trained model's generated co-ordinates of the 3D bounding boxes from **line 197** in [single_inference.py](https://github.com/tianweiy/CenterPoint/blob/master/tools/single_infernece.py#L197), I wanted to first transform these points into their 6 different respective camera plane and plot it using OpenCV/Matplotlib as described in the render_annotation() function in nuScenes devkit [nuscenes.py](https://github.com/nutonomy/nuscenes-devkit/blob/274725ae1b3a2d921725016e3f4b383b8b218d3a/python-sdk/nuscenes/nuscenes.py#L903) at **line 903**. Additionally, it would great if the tracking id and object category could be labeled over these bounding boxes.

Once this is done, we can publish these images with bounding boxes to a ROS topic to be visualized in Rviz. And these changes to the `single_inference.py` and `multi_sweep_inference.py` files.

**Comment by muzi2045** [comment]
It's just a visualization problem, hope you can implement it and open a pull request.

**Comment by iamsiddhantsahu** [comment]
@muzi2045 Yes, sure. How can I transform the predicted co-ordinates of the bounding boxes from lidar plane to camera plane using the calibration files, depending on the camera the object is visible the most?

**Comment by iamsiddhantsahu** [comment]
@muzi2045 If add Subscribers for the 6 different cameras after **line 248** in [single_inference.py](https://github.com/tianweiy/CenterPoint/blob/master/tools/single_infernece.py#L248), do I also have to add [TimeSynchronizer](https://docs.ros.org/api/message_filters/html/python/#message_filters.TimeSynchronizer)?

**Comment by muzi2045** [comment]
there normally has there coordinates when transform point from lidar coords to camera coords:
1. Lidar coords(right hand, x front, y left, z up) -->  Camera coords(right hand, z front, y left, x down)
2. Camera coords  --> Camera plane (u,v) coords.
you will find the calib param in those open source dataset.

**Comment by muzi2045** [comment]
If the dataset has done the time sync in hardware collection, there is no need to sync it again in reading the raw data.

**Comment by iamsiddhantsahu** [comment]
As described in **line 925** in [nuscenes.py](https://github.com/nutonomy/nuscenes-devkit/blob/274725ae1b3a2d921725016e3f4b383b8b218d3a/python-sdk/nuscenes/nuscenes.py#L925), before plotting the 2D bounding boxes over camera images, how do I figure out among the 6 different cameras, in **which camera image the object is fully visible?**

**Comment by iamsiddhantsahu** [comment]
The **/tf** ROS topic is given out these type of data with translation and rotation. Can we use it to transform co-ordinates of bounding boxes in lidar frame to camera frame? 
![Screenshot from 2020-07-31 16-13-55](https://user-images.githubusercontent.com/28495849/89028036-34323380-d349-11ea-9226-f5314d99a32f.png)

**Comment by tianweiy** [comment]
[here](https://github.com/nutonomy/nuscenes-devkit/blob/274725ae1b3a2d921725016e3f4b383b8b218d3a/python-sdk/nuscenes/nuscenes.py#L242) it does the translation and check visibility.

**Comment by iamsiddhantsahu** [comment]
@tianweiy Thanks, but I am afraid I am unable to the retrieve the **cs_record** dictionary data from any ROS topic. The cs_record dictionary seems to have all the **transformation** and **rotation** matrices and **camera** **intrinsic** **parameters** as described [here](https://github.com/nutonomy/nuscenes-devkit/blob/274725ae1b3a2d921725016e3f4b383b8b218d3a/python-sdk/nuscenes/nuscenes.py#L254) and [here](https://github.com/nutonomy/nuscenes-devkit/blob/274725ae1b3a2d921725016e3f4b383b8b218d3a/python-sdk/nuscenes/nuscenes.py#L228) respectively. Kindly suggest.

**Comment by iamsiddhantsahu** [comment]
@tianweiy @muzi2045 The predicted bounding boxes co-ordinates are with respect to the lidar frame. Before transforming them to a particular camera, we need to **first determine which camera's translation and rotation matrix we should use**. The **[render_annotation()](https://github.com/nutonomy/nuscenes-devkit/blob/274725ae1b3a2d921725016e3f4b383b8b218d3a/python-sdk/nuscenes/nuscenes.py#L903)** function from the nuScenes devkit takes as input the annotation token token with which the image path is known and the bounding boxes are plotted. 

But in our case I was wondering how can we determine to **which camera we transform the co-ordinates of the predicted bounding box** and plot the bounding boxes after that?

**Comment by muzi2045** [comment]
it's about the Nuscenes camera FOV parameters. and compute the obstacles center_pos and dimension size locate in which camera FOV, there will be something like trunk locate in three camera image in the mean time.

**Comment by iamsiddhantsahu** [comment]
@tianweiy @muzi2045 Can the [box_in_image() function](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/geometry_utils.py#L57) be used for the problem of determining the predicted bounding boxes co-ordinates corresponds to which camera and which camera's external calibration matrix (rotation + translation) should be used?

**Comment by tianweiy** [comment]
@iamsiddhantsahu  sorry for the late reply, I am really busy working on other projects. I think you can use this function. Though you need to check for every camera and then you will get a list of cameras that contain this object so you can draw boxes on these images. If you are not hurry, I can add some visualization files in a few weeks

**Comment by iamsiddhantsahu** [comment]
Thanks! I am also working on it and hopefully can I can open a PR. 

This is what I have decided to do.
1) Create an instance of the nuScenes "**[Box](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/data_classes.py#L457)**" class.
2) Assign the member variable like [**center, size, orientation, label etc.**](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/data_classes.py#L470) of the above created Box instance with the [**predicted co-ordinates of the Bounding Box**](https://github.com/tianweiy/CenterPoint/blob/master/tools/single_infernece.py#L209) in the **single_inference.py** file 
3) Transform these predicted co-ordinates, first from the lidar frame to the ego vehicle frame and then from the ego vehicle to the camera frame. (Which camera's transformation needs to be applied will be answered by the **[box_in_image()](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/geometry_utils.py#L57)** function.)
4) Once we have the list of cameras, we can plot the predicted co-ordinates by using the **[render_cv2()](https://github.com/nutonomy/nuscenes-devkit/blob/274725ae1b3a2d921725016e3f4b383b8b218d3a/python-sdk/nuscenes/utils/data_classes.py#L612)** function and pass the corresponding camera's intrinsic parameters to the "**view**" argument as well.
5) Then it can can be published to a ROS topic and visualized in Rviz.

Any suggestions/improvements are most welcomed!

**Comment by xavidzo** [comment]
> @tianweiy @muzi2045 Thanks! I am also working on it and hopefully I can open a PR.
> 
> This is what I have decided to do.
> 
> 1. Create an instance of the nuScenes "**[Box](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/data_classes.py#L457)**" class.
> 2. Assign the member variable like [**center, size, orientation, label etc.**](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/data_classes.py#L470) of the above created Box instance with the [**predicted co-ordinates of the Bounding Box**](https://github.com/tianweiy/CenterPoint/blob/master/tools/single_infernece.py#L209) in the **single_inference.py** file
> 3. Transform these predicted co-ordinates, first from the lidar frame to the ego vehicle frame and then from the ego vehicle to the camera frame. (Which camera's transformation needs to be applied will be answered by the **[box_in_image()](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/geometry_utils.py#L57)** function.)
> 4. Once we have the list of cameras, we can plot the predicted co-ordinates by using the **[render_cv2()](https://github.com/nutonomy/nuscenes-devkit/blob/274725ae1b3a2d921725016e3f4b383b8b218d3a/python-sdk/nuscenes/utils/data_classes.py#L612)** function and pass the corresponding camera's intrinsic parameters to the "**view**" argument as well.
> 5. Then it can can be published to a ROS topic and visualized in Rviz.
> 
> Any suggestions/improvements are most welcomed!

@iamsiddhantsahu would you please open a Pull request regarding this task if your implementation was indeed successful?
