### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'return_loss'.

### ISSUE THREAD

**Issue by gayathri1818** [tianweiy/CenterPoint#211]
Hi,
I am trying to run demo.py with the nuscenes data and pretrained model: centerpoint_pillar_512_demo.
But while running the file, I am getting the below type Erorr. 
Traceback (most recent call last):
  File "tools/demo.py", line 131, in <module>
    main()
  File "tools/demo.py", line 90, in main
    model, data_batch, train_mode=False, local_rank=0,
  File "/home/CenterPoint/det3d/torchie/apis/train.py", line 114, in batch_processor
    return model(example, return_loss=False)
  File "/home/installations/lib/python3.6/site-packages/torch/nn/modules/module.py", line 729, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'return_loss'.

I see that all the function calls are proper and below are the function parameters and arguments sent:
train.py's batch_processor is calling model file:  https://github.com/tianweiy/CenterPoint/blob/master/det3d/torchie/apis/train.py
def batch_processor(model, data, train_mode, **kwargs):
    .........
    return model(example, return_loss=False)

This triggers the below function block from file site-packages/torch/nn/modules/module.py:
def _call_impl(self, *input, **kwargs):
     ..........
     result = self.forward(*input, **kwargs)

and forward function gets triggered: file: https://github.com/tianweiy/CenterPoint/blob/master/det3d/models/detectors/point_pillars.py
def forward(self, example, return_loss=True, **kwargs):

Not able to understand the reason for type error unexpected keyword return_loss. I cross-checked the spelling too, it is the same in all the calls and function parameters.
Did anyone face such an issue or am I checking in the right direction?

**Comment by Songhuilun** [comment]
can you help me ?are you solve this problem?
