### ISSUE TITLE
How to special which gpus to use? If I have 4 gpus in my machine ,but only what to use the first two gpus? Is there any solution?

### ISSUE THREAD

**Issue by machengnan** [tianweiy/CenterPoint#213]

**Comment by tianweiy** [comment]
you can set CUDA_VISIBLE_DEVICES=0,1 to use first two opus

**Comment by machengnan** [comment]
> you can set CUDA_VISIBLE_DEVICES=0,1 to use first two opus

Great! It works. But there is another question, when I set --gpus = 2, only first gpu is used, the second gpu isn't used, Can you give me some suggestions?  Is there some other parameters which I forgot to set?  is --local_rank?

**Comment by machengnan** [comment]
> > you can set CUDA_VISIBLE_DEVICES=0,1 to use first two opus
> 
> Great! It works. But there is another question, when I set --gpus = 2, only first gpu is used, the second gpu isn't used, Can you give me some suggestions? Is there some other parameters which I forgot to set? is --local_rank?

Also I don't use torch.distributed.launch --nproc_per_node.  Just debug in vscode.

**Comment by tianweiy** [comment]
you will need 

torch.distributed.launch --nproc_per_node 2 

to use 2 gpus

**Comment by machengnan** [comment]
> you will need
> 
> torch.distributed.launch --nproc_per_node 2
> 
> to use 2 gpus

OK, So nice of you , Thanks!
