### ISSUE TITLE
Does this code surpport dynamic voxelization?

### ISSUE THREAD

**Issue by a954217436** [tianweiy/CenterPoint#215]
Thanks for replying

**Comment by tianweiy** [comment]
For voxelnet, there is an implementation here https://github.com/tianweiy/CenterPoint/blob/38797b6c51e6ca20c8421a504e8e45e739c67cec/det3d/models/readers/dynamic_voxel_encoder.py#L1

I will push a new version in a new days and it will have dynamic voxelization for pointpillar

**Comment by a954217436** [comment]
> For voxelnet, there is an implementation here
> 
> https://github.com/tianweiy/CenterPoint/blob/38797b6c51e6ca20c8421a504e8e45e739c67cec/det3d/models/readers/dynamic_voxel_encoder.py#L1
> 
> I will push a new version in a few days and it will have dynamic voxelization for pointpillar

OK, thanks a lot! Looking forward~
