### ISSUE TITLE
Train second stage with KITTI

### ISSUE THREAD

**Issue by melodytr** [tianweiy/CenterPoint#216]
Hello,

Thank you for sharing this great work. For my thesis, I try to do 3D bounding box detection of cars in KITTI dataset. Now, I have heat-map like outputs that has peaks on center of bounding box and some other real values inside the bounding box. So, I would like to define bounding box using those heatmaps. I assume that I need to train the second stage of this work and get the final bounding box prediction. To do that, I am investigating your codebase, but if you help me by giving some hint where I can start, it would be very helpful.
Also, I do not understand completely what  .pkl files serve for. In KITTI there is no such files. Could I do training and testing without them?

Thanks in advance.
Best!

**Comment by tianweiy** [comment]
This repo doesn't support KITTI but there is an implementation here https://github.com/tianweiy/CenterPoint-KITTI .

I tried CenterPoint's second stage but it is not as effective as other methods. So I provide raw centerpoint config and centerpoint + pvrcnn (a popular two stage method) at   https://github.com/tianweiy/CenterPoint-KITTI

**Comment by melodytr** [comment]
Thank you for your reply. I understand. I check the repo you provide.  Thank you for your great works, as well.
Then, considering centerpoint-kitti repo, I again would like to ask for your help. 
So, let assume I have point cloud info from KITTI and detected center points. Using those info, I would like to train a model that yields bounding boxes per center point. How could I do that using pvrcnn/centerpoint/centerpoint+pvrcnn? Do you have any suggestions? I do not want to train a model from very beginning like you are doing. I want to use my detected centerpoints.

Thank you in advance.
Best!

**Comment by tianweiy** [comment]
I see. If you already have detected center points, you can use extract features from the bird eye view feature map using bilinear interpolation and only train a box estimation branch. Basically, you still run the current lidar backbone (voxelnet or pointpillars) to get a bird eye view feature map and then simply use your precomputed feature to get a feature vector from the bev feature map and use a few layers MLP to turn this feature into a box. And then you can supervise this box estimation using simple l1 loss. This will give you the rotated bounding boxes. And then the second stage is the same

**Comment by melodytr** [comment]
Thank you so much for your reply!

**Comment by melodytr** [comment]
Hello,
I change my methodology and would like to make use of your codebase more. 
I want to backpropagate from detected centers. I want to train the centerpoint_rcnn model configuration and get a result of a backward pass from each center point. For this purpose, I have to find the index of a center point in input point cloud data.
I am not sure if I can find what I want. 
Could you help me to localize the module where you define the centerpoint locations and detecting them?
Thank you in advance.
