### ISSUE TITLE
US or Asia nuscenes data

### ISSUE THREAD

**Issue by JayChan-USTC** [tianweiy/CenterPoint#217]
1.For the nuscenes data set, there are two types of data, US and Asia. What kind of data do you use? 

2.If I only use a subset of the nuscenes data，such as, Lidar blobs only, will it affect the final result in your model?

**Comment by tianweiy** [comment]
1. we use both 

2. you mean subset of sensors (like only use Lidar) or subset of dataset sweeps (use 1/2 of the total number of sweeps)? If it is subset of sensor, it won't affect result. If it is subset of dataset sweeps, it will be slightly worse with less training data
