### ISSUE TITLE
Different shape of data["coordinates"] in the dataset and the dataloader

### ISSUE THREAD

**Issue by LSQsjtu** [tianweiy/CenterPoint#219]
I found in the dataset, the shape of the "coordinates" is N * 3, while the shape of the "coordinates" is N * 4 in the dataloader. It seem the "coordinates" only add 0 in the first place of the "coordinates". 
```python
key in ["coordinates", "points", "cyv_coordinates"]:
coors = []
for i, coor in enumerate(elems):
    coor_pad = np.pad(
        coor, ((0, 0), (1, 0)), mode="constant", constant_values=i
    )
    coors.append(coor_pad)
ret[key] = torch.tensor(np.concatenate(coors, axis=0))
```
Can I add the value of the reflection intensity？

**Comment by tianweiy** [comment]
coordinates only maintain each voxel's 3d location. The reflection intensity kind of features are in either points or voxels 

https://github.com/tianweiy/CenterPoint/blob/e086a1242e01b07e113b186494b7a866e2fc1085/det3d/models/detectors/voxelnet.py#L38

**Comment by LSQsjtu** [comment]
Thanks very much.
