### ISSUE TITLE
Import spconv fail, no support for sparse convolution!

### ISSUE THREAD

**Issue by Liaoqing-up** [tianweiy/CenterPoint#221]
hello, i install the spconv according to the INSTALL.md, i can suceessfully import spconv in python.
But when i run
 `# nuScenes
python tools/create_data.py nuscenes_data_prep --root_path=NUSCENES_TRAINVAL_DATASET_ROOT --version="v1.0-trainval" --nsweeps=10 --virtual True `, 
i get this error "**Import spconv fail, no support for sparse convolution!
iou3d cuda not built. You don't need this if you use circle_nms. Otherwise, refer to the advanced installation part to build this cuda extension
no apex
No Tensorflow**
"
how can i use spconv?

**Comment by tianweiy** [comment]
which version of spconv do you use ? 

Also, this is just warning message and you can still create data even if spconv is not installed

**Comment by Liaoqing-up** [comment]
> 

i git checkout 7342772 in spconv, then Compile and install from source code as suggested in _INSTALL.md_. Another problem is **no checkpoint found** when i run `python virtual_gen.py --info_path data/nuScenes/infos_train_10sweeps_withvelo_filter_True.pkl  `
from MVP to generate virtual points, but i have downloaded the centernet2 model and place it in the MVP directory.

**Comment by tianweiy** [comment]
Oh, you need another arguments for generating virtual point. add MODEL.WEIGHTS model_path to the command, I will update the docs. BTW, you can also use the precomputed virtual points. There is a link in the readme. Generating it yourself will take 10-20 hrs.

I will look into the spconv issue and reply back soon

**Comment by tianweiy** [comment]
the spconv warning happens at https://github.com/tianweiy/CenterPoint/blob/a338ce92b03c8c5ad7c8084165635f11ff2d3745/det3d/core/bbox/box_np_ops.py#L9
I think you can remove the whole try except block or just ignore the warning. It should not affect later computation. Post here if you meet further issues

**Comment by Liaoqing-up** [comment]
ok, thanks. So the project dosen't use spconv to compute?

**Comment by tianweiy** [comment]
It uses in computation, but not in create data

**Comment by Liaoqing-up** [comment]
hi, should i install Det3d before? Because when i run train.py i got the error _"ImportErrorImportError: : cannot import name 'iou3d_nms_cuda' from 'det3d.ops.iou3d_nms' (/opt/sdatmp/project/CenterPoint/det3d/ops/iou3d_nms/__init__.py)cannot import name 'iou3d_nms_cuda' from 'det3d.ops.iou3d_nms' (/opt/sdatmp/project/CenterPoint/det3d/ops/iou3d_nms/__init__.py)"_

**Comment by tianweiy** [comment]
No need, but you need to run bash setup.sh in this repo

**Comment by Liaoqing-up** [comment]
hello, what file should i feed when i run /tools/visual to visualization the predict, i had tried prediction.pkl(generate after run dist_test), but that seemed  mismatch.

**Comment by tianweiy** [comment]
No files for now but visual could be an example. It should be easy to visualize must stuff in open 3d with a few lines of code
