### ISSUE TITLE
Training PointPillars model with dynamic voxelizer

### ISSUE THREAD

**Issue by YoushaaMurhij** [tianweiy/CenterPoint#222]
@tianweiy , Have you tried to train Pointpillars model with the dynamic voxelizer in your realtime-version ?

Thanks,
Youshaa

**Comment by tianweiy** [comment]
I never tried but the accuracy won't change and the speed will be faster. PP + dynamic voxelization requires some code modifications and I will see if I have time to implement and push this in the next few days

**Comment by tianweiy** [comment]
I don't get time to write code recently but there seem to be one dynamic voxelization + pp here https://github.com/qcraftai/simtrack/blob/e45eab15f000a3f03885febfed60f98b6ad7b40c/det3d/models/readers/dynamic_pillar_encoder.py

**Comment by YoushaaMurhij** [comment]
Thanks a lot @tianweiy! I will check this code.
