### ISSUE TITLE
about det3d.models.registry

### ISSUE THREAD

**Issue by DipDipPotatoChips** [tianweiy/CenterPoint#226]
from det3d.utils import Registry

READERS = Registry("reader")
BACKBONES = Registry("backbone")
NECKS = Registry("neck")
HEADS = Registry("head")
LOSSES = Registry("loss")
DETECTORS = Registry("detector")
SECOND_STAGE = Registry("second_stage")
ROI_HEAD = Registry("roi_head")
print(READERS)
print(BACKBONES)
print(NECKS)
print(HEADS)
print(LOSSES)
print(DETECTORS)
print(SECOND_STAGE)
print(ROI_HEAD)

Registry(name=reader, items=[])
Registry(name=backbone, items=[])
Registry(name=neck, items=[])
Registry(name=head, items=[])
Registry(name=loss, items=[])
Registry(name=detector, items=[])
Registry(name=second_stage, items=[])
Registry(name=roi_head, items=[])

I try to print them but there are none,I read the from det3d.utils import Registry and don't now where the class message.

**Comment by tianweiy** [comment]
sorry, what is the problem ? Could you elaborate ?

**Comment by DipDipPotatoChips** [comment]
there is a register.class in /det3d/models/register.py
for example,to register DETECTORS = Registry("detector"),Which codes specifies the location of the class /det3d/models/detectors/point_pillars.py ?
There should be codes here to store the information in the registry class，right？
like：
Registry(name=backbone, items={
'ResNet': <class 'mmdet.models.backbones.resnet.ResNet'>, 
'ResNetV1d': <class 'mmdet.models.backbones.resnet.ResNetV1d'>, 
'HRNet': <class 'mmdet.models.backbones.hrnet.HRNet'>, 
'ResNeXt': <class 'mmdet.models.backbones.resnext.ResNeXt'>, 
'SSDVGG': <class 'mmdet.models.backbones.ssd_vgg.SSDVGG'>})
I can't find it

**Comment by tianweiy** [comment]
it is done through the register_module function

https://github.com/tianweiy/CenterPoint/blob/5b0e574a4478086ee9686702456aaca4f4115caa/det3d/models/detectors/point_pillars.py#L5

**Comment by DipDipPotatoChips** [comment]
But it only works when the class is instantiated.I can't find where is it in the code instantiate the class PointPillars

**Comment by DipDipPotatoChips** [comment]
> it is done through the register_module function
> 
> https://github.com/tianweiy/CenterPoint/blob/5b0e574a4478086ee9686702456aaca4f4115caa/det3d/models/detectors/point_pillars.py#L5

But it only works when the class is instantiated.I can't find where is it in the code instantiate the class PointPillars

**Comment by tianweiy** [comment]
if you mean where is the module built

https://github.com/tianweiy/CenterPoint/blob/5b0e574a4478086ee9686702456aaca4f4115caa/det3d/models/builder.py#L18

**Comment by DipDipPotatoChips** [comment]
> if you mean where is the module built
> 
> https://github.com/tianweiy/CenterPoint/blob/5b0e574a4478086ee9686702456aaca4f4115caa/det3d/models/builder.py#L18

No，I mean I can't find the code that instantiating the class point_pillars to use @DETECTORS.register_module

**Comment by tianweiy** [comment]
https://github.com/tianweiy/CenterPoint/blob/5b0e574a4478086ee9686702456aaca4f4115caa/det3d/models/detectors/__init__.py#L2 

import should do the job
