### ISSUE TITLE
RT model Two stage config

### ISSUE THREAD

**Issue by carlhuang070** [tianweiy/CenterPoint#228]
Hi tianweiy,
     from papers ,we know the stage two also have some contribution to improve accuracy.
     But  I can not found waymo Real Time 3D detection Two stage config ?

**Comment by tianweiy** [comment]
it requires some code changes. I will update a config and merge this branch into master once I get (probably in one to two week)

**Comment by carlhuang070** [comment]
Thanks very mush! Your baseline code is very useful for driving the progress of 3D detection & Tracking.

**Comment by carlhuang070** [comment]
When we can get two stage config for RT modeling ?? Thanks your effort.

**Comment by tianweiy** [comment]
I still get a few final exams until 15. Will work on this after finishing them

**Comment by tianweiy** [comment]
will push today

**Comment by carlhuang070** [comment]
Thanks

**Comment by tianweiy** [comment]
just updated https://github.com/tianweiy/CenterPoint/blob/c4b4e0fc97ec6d42d6a31f559816d3305abdf750/configs/waymo/voxelnet/two_stage/waymo_base.py 

two other tips:

1. you need a pretrained single-stage model and you can specify the path here https://github.com/tianweiy/CenterPoint-WOD/blob/5185b8af3c9785b6c6af4d360038c9649c4a9ce0/CenterPoint-dev/configs/waymo/voxelnet/two_stage/waymo_base.py#L22

2. for faster training, maybe you can consider caching the feature with a pretrained backbone and only train the second stage which is just a few layers of MLP (and will be significantly faster). However, this may need some 100 gb space.
