### ISSUE TITLE
RT Detection  Model Config add support velocity and support tracking

### ISSUE THREAD

**Issue by carlhuang070** [tianweiy/CenterPoint#229]
Hi tianweiy,

         I want to add support velocity base on Real time config(waymo_centerpoint_voxelnet_three_sweeps_20e_iou_pred.py).

this change is right ?   

       code_weights=[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
        common_heads={'reg': (2, 2), 'height': (1, 2), 'dim':(3, 2), 'rot':(2, 2), 'iou': (1, 2), 'vel':(1,2)}, # (output_channel, num_conv)

I can not get tracking result base on Real time model which training after adding support velocity.

**Comment by tianweiy** [comment]
the change seems right.

I can not get tracking result base on Real time model which training after adding support velocity.

could you explain a bit more what is the challenges for not getting tracking result?

**Comment by carlhuang070** [comment]
I debug Why we can not get tracking list . I found we get null list [] after  this function (def step_centertrack(self, results, time_lag): in tracking.py) .

But we debug this function input(results, time_lag) do not found wrong data.

Do you think get  velocity data is wrong ??   
--- velocity = box[:,[6,7]]

**Comment by tianweiy** [comment]
the velocity is right. 

I am a little confusing.  When you are saying, you can't get tracking results, do you mean that there are some errors when you run the code or the results are really bad? 

> I found we get null list [] after this function (def step_centertrack(self, results, time_lag): in tracking.py) .

This is normal as we use a large score threshold https://github.com/tianweiy/CenterPoint/blob/a3ffc821eedf0fd3408a4f0ce8ba0726ce847938/tools/waymo_tracking/test.py#L38 (most objects will be filtered out). 

btw, the input to test.py needs to be the prediction.pkl saved at https://github.com/tianweiy/CenterPoint/blob/a3ffc821eedf0fd3408a4f0ce8ba0726ce847938/tools/dist_test.py#L199 Is this part right in your experiment?

**Comment by tianweiy** [comment]
BTW, feel free to use Chinese if it is easier to illustrate the points

**Comment by carlhuang070** [comment]
非常感谢，debug 下，确实是threshold 的阈值设置导致，，RT model  修改了IoU ,需要将各个地方的score_thresh 降低点。


多谢。。
