### ISSUE TITLE
Any work update on Waymo dataset

### ISSUE THREAD

**Issue by DeepakVellampalli** [tianweiy/CenterPoint#23]
@tianweiy 
Do you have any update on the workside relevant to waymo dataset? Can you update if any

**Comment by tianweiy** [comment]
Thanks for the interest. I am working on it right now. But there is not an estimated timeline yet.

**Comment by tianweiy** [comment]
It will be out in a few weeks.

**Comment by tianweiy** [comment]
We now support Waymo. It is in active development and let me know if you face any problems.

**Comment by DeepakVellampalli** [comment]
Thanks tianwei. Your models works well even on other datasets like KITTI. Hopefully you will release single model which handles all the classes like Vehicle,Pedestrian and Cyclist classes also in near future. Awaiting for your next models

**Comment by tianweiy** [comment]
Yeah, we will support more classes and have some major updates for the models in the fall. Close this issue for now.

**Comment by chowkamlee81** [comment]
@tianweiy Thanks

**Comment by tianweiy** [comment]
@chowkamlee81 @DeepakVellampalli  I fix a NMS threshold bug and it is now close to SOTA single model on the benchmark for car detection. I am training all three classes but we plan to opensource them after we get to top on Waymo / nuScenes. I guess this will be done next month. I will keep this issue open until then

**Comment by chowkamlee81** [comment]
@tianweiy , Thanks for your update and hope for the best
