### ISSUE TITLE
Error in dcn

### ISSUE THREAD

**Issue by 3bobo** [tianweiy/CenterPoint#231]
Thanks for your great works! I first train the `nusc_centerpoint_voxelnet_01voxel.py` and it works, but when I turn to `nusc_centerpoint_voxelnet_0075voxel_dcn_flip` there is an error in dcn:

> error in deformable_im2col: no kernel image is available for execution on the device
 
But the `Installation` works, my platform:
Ubuntu 18.04
RTX 3090
CUDA 11.1
Python 3.7.11
Pytorch 1.9.0

By the way, is it necessary to install `cudnn` for setup?

**Comment by tianweiy** [comment]
hi, first of all, I suggest using this config https://github.com/tianweiy/CenterPoint/blob/master/configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z.py 

it doesn't need to build dcn with better results and faster training speed (66.8 vs 65.4). You can also do flip testing using this config (and get the extra improvement).

For your original question, I guess they are some code change needed for coda 11.1 (as the original code is a few years old now).  

> But the Installation works

You mean bash setup.sh works ? Are you installing in the same environment as your 3090 ? (for instance, you may need to set cuda_visible_devices if you get two different gpus on your server)

**Comment by 3bobo** [comment]
Thanks for your reply! The new config you mentioned could run on my platform. Following your suggestion, I re-build the code and find I downgrade the CUDA arch to 7.5 with:
> export TORCH_CUDA_ARCH_LIST="7.5"

to build `spconv` and `apex` before run `bash setup.py`, which results in the error. After canceling the setting, the `bash setup.py` still works, but I need some modification to build `spconv` and could only install `spconv-1.0`. Meanwhile, when I run the dcn config again, the original error disappears but there is a new error:
>File "/root/code/CenterPoint/det3d/ops/dcn/deform_conv.py", line 92, in backward
   cur_im2col_step)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape (...) instead.

**Comment by tianweiy** [comment]
Yeah, I suggest just using the new config. It is better and faster

**Comment by 3bobo** [comment]
Ok, thanks for your reply!
