### ISSUE TITLE
Do you try five sweeps to improve accuracy ?

### ISSUE THREAD

**Issue by carlhuang070** [tianweiy/CenterPoint#233]
Hi tianweiy,

          we know multi sweeps fusion can improve accuracy (from 1,2,3 sweeps result).

          So do you try more sweeps fusion (4 or 5) to improve accuracy.

**Comment by tianweiy** [comment]
i didn't. Basically, I mainly use 3 sweeps for the real-time challenge and I feel more sweeps will introduce too large latency so that the model won't be able to finish within 70 ms. I guess it will have some improvements but I am not sure how much it will be

**Comment by carlhuang070** [comment]
Thanks, This is a very valuable reply.
