### ISSUE TITLE
[Errno 2] No such file or directory: 'data/nuScenes/infos_train_10sweeps_withvelo_filter_True.pkl'

### ISSUE THREAD

**Issue by TianhaoFu** [tianweiy/CenterPoint#241]
Hi, when I was using your code, I came across such bug.
```
[Errno 2] No such file or directory: 'data/nuScenes/infos_train_10sweeps_withvelo_filter_True.pkl'
```
could you give me some ideas on how to fix it ?
thanks!
:)

**Comment by tianweiy** [comment]
it is generated here https://github.com/tianweiy/CenterPoint/blob/master/docs/NUSC.md#create-data

**Comment by TianhaoFu** [comment]
> it is generated here https://github.com/tianweiy/CenterPoint/blob/master/docs/NUSC.md#create-data

thanks!
