### ISSUE TITLE
best performance training config on nuscenes 

### ISSUE THREAD

**Issue by TianhaoFu** [tianweiy/CenterPoint#242]
### VoxelNet 
| Model                 | Validation MAP  | Validation NDS  | Link          |
|-----------------------|-----------------|-----------------|---------------|
| [centerpoint_voxel_1440](voxelnet/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z.py) |59.6  | 66.8 | [URL](https://drive.google.com/drive/folders/1FOfCe9nWQrySUx42PlZyaKWAK2Or0sZQ?usp=sharing)  |
### PointPillars 

| Model                 | FPS       | Validation MAP  | Validation NDS  | Link          |
|-----------------------|-----------------|-----------------|-----------------|---------------|
| [centerpoint_pillar](pp/nusc_centerpoint_pp_02voxel_two_pfn_10sweep.py) | 31 | 50.3 | 60.2 | [URL](https://drive.google.com/drive/folders/1K_wHrBo6yRSG7H7UUjKI4rPnyEA8HvOp?usp=sharing) |

Hi,  I want reproduce the voxel and pointpillars results above, the CONFIG_PATH should be what?
```
python -m torch.distributed.launch --nproc_per_node=2 ./tools/train.py CONFIG_PATH
```

THanks!
:)

**Comment by tianweiy** [comment]
this one https://github.com/tianweiy/CenterPoint/blob/master/configs/nusc/pp/nusc_centerpoint_pp_02voxel_two_pfn_10sweep.py 

for a slightly better result, you can use https://github.com/tianweiy/CenterPoint/blob/master/configs/mvp/nusc_centerpoint_pp_fix_bn_z_scale.py

it has slightly better data augmentation parameters and achieve 52.4 map / 61.5 nds in my experiments. models are available at https://github.com/tianweiy/MVP#main-results

**Comment by TianhaoFu** [comment]
> this one https://github.com/tianweiy/CenterPoint/blob/master/configs/nusc/pp/nusc_centerpoint_pp_02voxel_two_pfn_10sweep.py
> 
> for a slightly better result, you can use https://github.com/tianweiy/CenterPoint/blob/master/configs/mvp/nusc_centerpoint_pp_fix_bn_z_scale.py
> 
> it has slightly better data augmentation parameters and achieve 52.4 map / 61.5 nds in my experiments. models are available at https://github.com/tianweiy/MVP#main-results

thanks for your reply.
Now i have the answer of best result of centerNpoint based on pointpillars.

could you tell me the config path pf best result of centerpoint based on voxelnet? @tianweiy 

thanks!
:)
