### ISSUE TITLE
A bug on voxelization && A TensorRT version of Centerpoint

### ISSUE THREAD

**Issue by Abraham423** [tianweiy/CenterPoint#243]
Hi, tianwei:
     Thanks for your great work,  I wrote a [TensorRT project](https://github.com/Abraham423/CenterPointTensorRT.git) to accelerate inference, the project is exactly based on configs/waymo/pp/waymo_centerpoint_pp_two_pfn_stride1_3.py. I implement the inference by TensorRT and found the mAP/mAPH metrics are *better than* that of the original torch model.  And the reason is that, points in WAYMO Openset is permuted roughly regularly according to their 3D-locations, when we make voxelizaiton in a point-wise-for-loop way([see here](https://github.com/tianweiy/CenterPoint/blob/952f14b694970cb667d8e3fa00ab5ae0936fa164/det3d/ops/point_cloud/point_cloud_ops.py#L87)), only the top20 of points will be accepted,  which is a biased subsampling. 
To make unbiased subsampling if there are more than 20 points belonging to this voxel, you can either shuffle the permutation of those points or make point-wise multi-threads, I choose the latter way implemented by CUDA, where whether a point will be accepted into the voxel is totally randomly,  because orders of threads are random.

**Comment by tianweiy** [comment]
great works, I will add a link to your project in the readme later today. 

your solution also sounds reasonable. I have a version that implements dynamic voxelization (using all points inside the pillar) through torch unique / scatter_mean, that one should solve the problem but not sure how fast it is in comparison to yours

**Comment by Abraham423** [comment]
That's right, the problem only occurs when we make traditional voxelization,  and dynamic voxelization will be fine ~
