### ISSUE TITLE
output of centerpoint_head

### ISSUE THREAD

**Issue by mc171819** [tianweiy/CenterPoint#245]
hi, i'm a new user of centerpoint. According to the config of waymo_centerpoint_voxelnet_two_sweeps_3x_with_velo.py, you will output this: 
`{'reg': (2, 2), 'height': (1, 2), 'dim':(3, 2), 'rot':(2, 2), 'vel':(2,2)}`
Then you will calculate the loss as: 
` if return_loss:
        return self.bbox_head.loss(example, preds, self.test_cfg)`
However, in loss calculate function of centerpoint_head, i need a pred_dict['hm']:, `preds_dict['hm'] = self._sigmoid(preds_dict['hm'])` you don't set `dcn_head` in your config file so it is keeping false, so SepHead will be used. I wonder where the 'hm' is from?

**Comment by tianweiy** [comment]
it is hard coded here https://github.com/tianweiy/CenterPoint/blob/928dbb69485f63efc37aa14fcd8a2322cc802357/det3d/models/bbox_heads/center_head.py#L225

because we feel we always need hm and its channel is related to #classes

**Comment by mc171819** [comment]
> it is hard coded here
> 
> https://github.com/tianweiy/CenterPoint/blob/928dbb69485f63efc37aa14fcd8a2322cc802357/det3d/models/bbox_heads/center_head.py#L225
> 
> because we feel we always need hm and its channel is related to #classes

Thx
