### ISSUE TITLE
question about centerhead

### ISSUE THREAD

**Issue by TianhaoFu** [tianweiy/CenterPoint#247]
Hi,

I noticed that the pointpillar backbone version center point is one stage detection. In this situation, What is the difference between center head and other heads ? I don't really see much difference. Could you explain it from the source code?
```
class CenterHead(nn.Module):
    def __init__(
        self,
        in_channels=[128,],
        tasks=[],
        dataset='nuscenes',
        weight=0.25,
        code_weights=[],
        common_heads=dict(),
        logger=None,
        init_bias=-2.19,
        share_conv_channel=64,
        num_hm_conv=2,
        dcn_head=False,
    ):
```

Thank you very much!
:)

**Comment by tianweiy** [comment]
> In this situation, What is the difference between center head and other heads ? I don't really see much difference

Other previous methods do the detection in anchor-based fashion, which means that they will have predetermined box templates of certain shape / rotation and at certain bev location. In contrast, we use point-based detection to detect objects first as center points and regress other attributes from center features after that which tend to perform better for extremely small / large objects or objects with various rotations.  The main convincing experiment is pedestrian detection on Waymo where *any* sota anchor-based methods lag behind our method by a large margin.

**Comment by TianhaoFu** [comment]
i know, thanks!
