### ISSUE TITLE
Question about the config file

### ISSUE THREAD

**Issue by StiphyJay** [tianweiy/CenterPoint#248]
Hi~, Dr. Yin. Thanks for your great job!  I want to ask which config file or setting has the best detection performance on Nuscenes dataset except  MVP. Looking forward to your reply!

**Comment by tianweiy** [comment]
no Doctor yet, but this one is the best https://github.com/tianweiy/CenterPoint/blob/master/configs/mvp/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z_scale.py

and it will give you 59.5 map / 66.7 NDS

**Comment by StiphyJay** [comment]
> no Doctor yet, but this one is the best https://github.com/tianweiy/CenterPoint/blob/master/configs/mvp/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z_scale.py
> 
> and it will give you 59.5 map / 66.7 NDS

Thank you very much. Wish you a successful graduation～

**Comment by StiphyJay** [comment]
Hello, tianwei~  After I. read your open-source code. I  have another question about why the length of the **preds_dicts** predicted by the network when compute the loss is 6. Is it because you transform and merge the Lidar points of the non-annotated frames into its following annotated frame? That is to say, you fuse the non-annotated point cloud with the annotated point cloud. Is the number of frames of the fused point cloud 6? So how many frames do you fuse for labeled point clouds and unlabeled point clouds? looking forward to your reply.

**Comment by tianweiy** [comment]
no, we fuse the past 9 frames (so in total 10 frames)

 I have another question about why the length of the preds_dicts predicted by the network when compute the loss is 6. 

this is the number of groups as we compute loss for each group separately. it is defined here https://github.com/tianweiy/CenterPoint/blob/47d61adacb75ba6ccb49ae666dc257d04e323a2c/configs/mvp/nusc_centerpoint_pp_fix_bn_z_scale.py#L6

**Comment by StiphyJay** [comment]
> no, we fuse the past 9 frames (so in total 10 frames)
> 
> I have another question about why the length of the preds_dicts predicted by the network when compute the loss is 6.
> 
> this is the number of groups as we compute loss for each group separately. it is defined here
> 
> https://github.com/tianweiy/CenterPoint/blob/47d61adacb75ba6ccb49ae666dc257d04e323a2c/configs/mvp/nusc_centerpoint_pp_fix_bn_z_scale.py#L6

OK. I see. Thanks for your reply! Great!
