### ISSUE TITLE
result for trainval and test?

### ISSUE THREAD

**Issue by AndyYuan96** [tianweiy/CenterPoint#25]
Hi, I just wonder if I can get the trainval or test result (json file), just like megvi provide their trainval.json result and test.json result.

**Comment by tianweiy** [comment]
Yeah, [here](https://github.com/tianweiy/CenterPoint/blob/master/docs/MODEL_ZOO.md) we provide the result for detection/tracking on the validation and testing set. The train set will take some time to generate and let me know if you also want it

**Comment by AndyYuan96** [comment]
> Yeah, [here](https://github.com/tianweiy/CenterPoint/blob/master/docs/MODEL_ZOO.md) we provide the result for detection/tracking on the validation and testing set. The train set will take some time to generate and let me know if you also want it

Thank you, enough
