### ISSUE TITLE
Why db_sampler is disabled by default?

### ISSUE THREAD

**Issue by Abyssaledge** [tianweiy/CenterPoint#250]
Hi, Tianwei,
I noticed a `enable=False` in db_sampler in the configs. Does  that mean CenterPoint do not use copy-paste augmentation by default?
If there are no misunderstandings, I wonder why CenterPoint  disable it?

**Comment by tianweiy** [comment]
no, we use copy-paste.

For nuScenes, the improvements are not too large (maybe 0.5 nds), for Waymo, it doesn't improve vehicle / pedestrian, but matters a lot for cyclists 

this enable=False is a dummy value, I simply copy the config from past configs and the code never use this value. To disable db_sampler, set it to None
