### ISSUE TITLE
question about gt annotation 

### ISSUE THREAD

**Issue by TianhaoFu** [tianweiy/CenterPoint#252]
Hi, 
When I was using your code,
i found such code
```
            gt_annos.append(
                {
                    "bbox": np.tile(np.array([[0, 0, 50, 50]]), [N, 1]),
                    "alpha": np.full(N, -10),
                    "occluded": np.zeros(N),
                    "truncated": np.zeros(N),
                    "name": gt_names[mask],
                    "location": gt_boxes[mask][:, :3],
                    "dimensions": gt_boxes[mask][:, 3:6],
                    "rotation_y": gt_boxes[mask][:, 6],
                    "token": info["token"],
                }
            )
```
I have some questions as follows:
- I wonder know does the `dimension` corresponding to bounding box `[w,l,h]`? or `[w,h,l]`?
- What's the base unit of [w,l,h]? metre or centimetre ?
- Is the input point cloud data positive？ or will there be negative numbers？
- Also i want to know does the gt box Do the 8 vertices of the gt box correspond to points on the point cloud？or do they not necessarily correspond to points on the point cloud？
- And for `[location, dimensions, rotation ]`Which has a greater impact on the test results mAP and why? is there a reference?

**Comment by tianweiy** [comment]
where is this code block ? Could you post a link?

> I wonder know does the dimension corresponding to bounding box [w,l,h]? or [w,h,l]?

wlh 

> What's the base unit of [w,l,h]? metre or centimetre ?

meter

> Is the input point cloud data positive？ or will there be negative numbers？

it can have negative locations 

> Also i want to know does the gt box Do the 8 vertices of the gt box correspond to points on the point cloud？or do they not necessarily correspond to points on the point cloud？


it doesn't correspond to points 

> And for [location, dimensions, rotation ]Which has a greater impact on the test results mAP and why? is there a reference?

location, as map is 50% of NDS, and dimensions is 10% or  so.

**Comment by TianhaoFu** [comment]
Thank you for your answer, 
- the code is in https://github.com/tianweiy/CenterPoint/blob/master/det3d/datasets/nuscenes/nuscenes.py
- I would also like to ask which of today's target detection algorithms performs best and worst on the three outputs [location, size, rotation]?Improve which gains the most

- Also, I noticed that the point cloud data is not normalized in the code, but fed directly to the network. So are the input point cloud coordinates the original collected coordinate data, or has some pre-processing been done, and if so, where is the code?

Thanks!

**Comment by tianweiy** [comment]
1. you can ignore this part. We never use it 
2. I am not sure. No one do a comparison separately to my knowledge.
3. We filter points outside of the range. https://github.com/tianweiy/CenterPoint/blob/47d61adacb75ba6ccb49ae666dc257d04e323a2c/det3d/models/readers/dynamic_voxel_encoder.py#L9
there is no other normalizations

**Comment by TianhaoFu** [comment]
> 3. We filter points outside of the range. https://github.com/tianweiy/CenterPoint/blob/47d61adacb75ba6ccb49ae666dc257d04e323a2c/det3d/models/readers/dynamic_voxel_encoder.py#L9
>    
>    there is no other normalizations

it seems that in pointpillars-based centerpoint coords range [1,512],Where did this come from?
thanks !

**Comment by tianweiy** [comment]
there are two things here, one is real xyz location, the other is the coordinate (coordinate the 1,512 is determined by range and voxel size, ),

basically 

coor_x = (x - x_start) / voxel_x

**Comment by TianhaoFu** [comment]
ok, iknow , thanks !
