### ISSUE TITLE
 visualization code

### ISSUE THREAD

**Issue by TianhaoFu** [tianweiy/CenterPoint#253]
Hi,

Could provide your visualization code of using CenterPoint pre-trained model on Nuscenes dataset?

Thanks!
:)

**Comment by TianhaoFu** [comment]
I find it ~

**Comment by siddharthKatageri** [comment]
Hi @TianhaoFu, can you please help me by telling which code did you find as visualization code??

Thanks

**Comment by 18lalala** [comment]
could you tell me where is the visualizing code?

**Comment by siddharthKatageri** [comment]
demo.py visualizes the lidar points and the detection boxes in top-view.
for 3D view, dump the points and detection boxes into a pickle file and can use open3d to render it.

**Comment by 18lalala** [comment]
> 

thank you! I'm a beginner,can you share the 3D view visualization code?thx a lot!
