### ISSUE TITLE
validation code and config

### ISSUE THREAD

**Issue by TianhaoFu** [tianweiy/CenterPoint#255]
Hi, 

I want to see my model performance on nuscences val dataset, how can i do it ? it seems that all the config only can train, cannot validate.

thanks!

**Comment by tianweiy** [comment]
the dist_test.py will evaluate your model in the end.

**Comment by Liaoqing-up** [comment]
hello, tianweiy. I want to monitor the training process, such as do a evaluate for a trained epoch right now. Can i realize it by pass some parameter in train config? Or how can i realize it?

**Comment by tianweiy** [comment]
not really sure, but maybe adding a 'val': 1 to here https://github.com/tianweiy/CenterPoint/blob/47d61adacb75ba6ccb49ae666dc257d04e323a2c/configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_dcn.py#L231 

may do a validation every 1 epoch

**Comment by Liaoqing-up** [comment]
ok, I'll try ~. By the way, can you share your experience in training? Only by observing the printed loss or something other? Thanks~

**Comment by Liaoqing-up** [comment]
ok, I'll try . By the way, can you share your experience in training? Only by observing the printed loss or something other? Thanks

**Comment by tianweiy** [comment]
I never really look at the loss. I do a full run of training and then measure map. This is the only valid way to my knowledge. For faster iteration, I may downsample the dataset

**Comment by Liaoqing-up** [comment]
ok, I got it , thanks ~

**Comment by TianhaoFu** [comment]
thanks.

if the dist_test.py is on val dataset. 

how can i get the test prediction in order to get nuscnenes tensorboard test dataset rank?

**Comment by tianweiy** [comment]
You can change https://github.com/tianweiy/CenterPoint/blob/47d61adacb75ba6ccb49ae666dc257d04e323a2c/configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z.py#L167

to infos_test

**Comment by TianhaoFu** [comment]
thanks~
