### ISSUE TITLE
The question about velocity

### ISSUE THREAD

**Issue by JayChan-USTC** [tianweiy/CenterPoint#256]
Hi author, as mentioned in the paper:

"The velocity estimate is special, as it requires two in-put map-views the current and previous time-step. It predicts the difference in object position between the current and the past frame. "

Where are the two in-put map-views the current and the past frame reflected in the code？
（I always thought that the CenterPoint only inputs one current frame of point cloud, and then predicts the velocity of detections.)

**Comment by tianweiy** [comment]
we read multiple sweep Lidar data https://github.com/tianweiy/CenterPoint/blob/47d61adacb75ba6ccb49ae666dc257d04e323a2c/det3d/datasets/pipelines/loading.py#L137
