### ISSUE TITLE
question about multiple gpu

### ISSUE THREAD

**Issue by TianhaoFu** [tianweiy/CenterPoint#257]
hi, 
when i whether use 
```
python -m torch.distributed.launch ./tools/train.py ./configs/nusc/pp/nusc_centerpoint_pp_02voxel_two_pfn_10sweep_circular_nms.py
```
or 
```
python ./tools/train.py ./configs/nusc/pp/nusc_centerpoint_pp_02voxel_two_pfn_10sweep_circular_nms.py
```
I only can use one gpu to train. but I have 4 available gpus in one machine.

Could you tell me why this problem happened?

**Comment by tianweiy** [comment]
you need sth like 

python -m torch.distributed.launch  --nproc_per_node 4 --master_port some number 

to start the multi-gpu training

**Comment by TianhaoFu** [comment]
it works.

thanks~
