### ISSUE TITLE
mismatched shape

### ISSUE THREAD

**Issue by moon5ye** [tianweiy/CenterPoint#259]
Thank you for your wonderful works. But when I test the model, there is a mismatched shape.

Also, I am wondering how to visualize the testing results on Nuscenes?

python tools/dist_test.py configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_dcn_flip.py --work_dir work_dirs/nusc_centerpoint_voxelnet_dcn_0075voxel_flip_testset  --checkpoint work_dirs/nusc_0075_dcn_flip_track/voxelnet_converted.pth  --testset --speed_test
No APEX!
no apex
WARNING:tensorflow:From /home/cav/Documents/Zonglin/CenterPoint/det3d/datasets/waymo/waymo_common.py:17: The name tf.enable_eager_execution is deprecated. Please use tf.compat.v1.enable_eager_execution instead.

No APEX!
2022-01-17 16:26:11,662 - INFO - Distributed testing: False
2022-01-17 16:26:11,662 - INFO - torch.backends.cudnn.benchmark: False
2022-01-17 16:26:11,717 - INFO - Finish RPN Initialization
2022-01-17 16:26:11,717 - INFO - num_classes: [1, 2, 2, 1, 2, 2]
Use HM Bias:  -2.19
Use Deformable Convolution in the CenterHead!
2022-01-17 16:26:11,747 - INFO - Finish CenterHead Initialization
Use Test Set
xxxxxxxxxxxxxxxxxxxxx
<det3d.datasets.nuscenes.nuscenes.NuScenesDataset object at 0x7f04ca142590>
xxxxxxxxxxxxxxxxxxxxx
10
The model and loaded state dict do not match exactly

these keys have mismatched shape:
+-------------------------------+---------------------------------+---------------------------------+
| key                           | expected shape                  | loaded shape                    |
+-------------------------------+---------------------------------+---------------------------------+
| backbone.conv_input.0.weight  | torch.Size([16, 3, 3, 3, 5])    | torch.Size([3, 3, 3, 5, 16])    |
| backbone.conv1.0.conv1.weight | torch.Size([16, 3, 3, 3, 16])   | torch.Size([3, 3, 3, 16, 16])   |
| backbone.conv1.0.conv2.weight | torch.Size([16, 3, 3, 3, 16])   | torch.Size([3, 3, 3, 16, 16])   |
| backbone.conv1.1.conv1.weight | torch.Size([16, 3, 3, 3, 16])   | torch.Size([3, 3, 3, 16, 16])   |
| backbone.conv1.1.conv2.weight | torch.Size([16, 3, 3, 3, 16])   | torch.Size([3, 3, 3, 16, 16])   |
| backbone.conv2.0.weight       | torch.Size([32, 3, 3, 3, 16])   | torch.Size([3, 3, 3, 16, 32])   |
| backbone.conv2.3.conv1.weight | torch.Size([32, 3, 3, 3, 32])   | torch.Size([3, 3, 3, 32, 32])   |
| backbone.conv2.3.conv2.weight | torch.Size([32, 3, 3, 3, 32])   | torch.Size([3, 3, 3, 32, 32])   |
| backbone.conv2.4.conv1.weight | torch.Size([32, 3, 3, 3, 32])   | torch.Size([3, 3, 3, 32, 32])   |
| backbone.conv2.4.conv2.weight | torch.Size([32, 3, 3, 3, 32])   | torch.Size([3, 3, 3, 32, 32])   |
| backbone.conv3.0.weight       | torch.Size([64, 3, 3, 3, 32])   | torch.Size([3, 3, 3, 32, 64])   |
| backbone.conv3.3.conv1.weight | torch.Size([64, 3, 3, 3, 64])   | torch.Size([3, 3, 3, 64, 64])   |
| backbone.conv3.3.conv2.weight | torch.Size([64, 3, 3, 3, 64])   | torch.Size([3, 3, 3, 64, 64])   |
| backbone.conv3.4.conv1.weight | torch.Size([64, 3, 3, 3, 64])   | torch.Size([3, 3, 3, 64, 64])   |
| backbone.conv3.4.conv2.weight | torch.Size([64, 3, 3, 3, 64])   | torch.Size([3, 3, 3, 64, 64])   |
| backbone.conv4.0.weight       | torch.Size([128, 3, 3, 3, 64])  | torch.Size([3, 3, 3, 64, 128])  |
| backbone.conv4.3.conv1.weight | torch.Size([128, 3, 3, 3, 128]) | torch.Size([3, 3, 3, 128, 128]) |
| backbone.conv4.3.conv2.weight | torch.Size([128, 3, 3, 3, 128]) | torch.Size([3, 3, 3, 128, 128]) |
| backbone.conv4.4.conv1.weight | torch.Size([128, 3, 3, 3, 128]) | torch.Size([3, 3, 3, 128, 128]) |
| backbone.conv4.4.conv2.weight | torch.Size([128, 3, 3, 3, 128]) | torch.Size([3, 3, 3, 128, 128]) |
| backbone.extra_conv.0.weight  | torch.Size([128, 3, 1, 1, 128]) | torch.Size([3, 1, 1, 128, 128]) |
+-------------------------------+---------------------------------+---------------------------------+
2022-01-17 16:26:14,523 - INFO - work dir: work_dirs/nusc_centerpoint_voxelnet_dcn_0075voxel_flip_testset
[                                                  ] 0/6008, elapsed: 0s, ETA

**Comment by tianweiy** [comment]
hi, the problem is due to the weight shape change in spconv 2.0 (model is trained in spconv 1.x). 

To solve this, you need to set an environment variable 

```
test spconv 1.x model in spconv 2.x: Firstly set environment variable before run program, Then set all algo in conv/pool to ConvAlgo.Native. Linux: export SPCONV_FILTER_HWIO="1", Windows powershell: $Env:SPCONV_FILTER_HWIO = "1". WARNING test spconv 1.x model don't support implicit gemm algorithm.
```

Please refer to https://github.com/traveller59/spconv/blob/master/docs/SPCONV_2_BREAKING_CHANGEs.md for more infos

**Comment by moon5ye** [comment]
Thanks for your reply!

I have two more questions.

First, how to visualize the tracking result of nuScenes?

Second, I recieved this error when I tried to generate the tracking results based on the detection results on nuScenes.
I found there is a tracking_result.json. Does it means tracking is already done?

======
Loading NuScenes tables for version v1.0-test...
23 category,
8 attribute,
4 visibility,
0 instance,
12 sensor,
1800 calibrated_sensor,
462901 ego_pose,
15 log,
150 scene,
6008 sample,
462901 sample_data,
0 sample_annotation,
4 map,
Done loading in 3.2 seconds.
======
Reverse indexing ...
Done reverse indexing in 0.7 seconds.
======
Deploy OK
Use hungarian: False
Begin Tracking

The speed is 532.0349059821517 FPS
======
Loading NuScenes tables for version v1.0-test...
23 category,
8 attribute,
4 visibility,
0 instance,
12 sensor,
1800 calibrated_sensor,
462901 ego_pose,
15 log,
150 scene,
6008 sample,
462901 sample_data,
0 sample_annotation,
4 map,
Done loading in 3.1 seconds.
======
Reverse indexing ...
Done reverse indexing in 0.7 seconds.
======
Initializing nuScenes tracking evaluation
Loaded results from /home/cav/Documents/Zonglin/CenterPoint/work_dirs/tracking_result.json. Found detections for 6008 samples.
Loading annotations for val split from nuScenes version: v1.0-test
Traceback (most recent call last):
  File "tools/nusc_tracking/pub_test.py", line 192, in <module>
    eval_tracking()
  File "tools/nusc_tracking/pub_test.py", line 160, in eval_tracking
    args.root
  File "tools/nusc_tracking/pub_test.py", line 176, in eval
    nusc_dataroot=root_path,
  File "/home/cav/anaconda3/envs/centerpoint/lib/python3.7/site-packages/nuscenes/eval/tracking/evaluate.py", line 85, in __init__
    gt_boxes = load_gt(nusc, self.eval_set, TrackingBox, verbose=verbose)
  File "/home/cav/anaconda3/envs/centerpoint/lib/python3.7/site-packages/nuscenes/eval/common/loaders.py", line 80, in load_gt
    'Error: Requested split {} which is not compatible with NuScenes version {}'.format(eval_split, version)
AssertionError: Error: Requested split val which is not compatible with NuScenes version v1.0-test

**Comment by tianweiy** [comment]
> I found there is a tracking_result.json. Does it means tracking is already done?

Yes, you can ignore the error (it happens because we don't have test set annotations, it is only available on eval server)

> First, how to visualize the tracking result of nuScenes?

I don't have an easy way, you may want to plot out the box and tracking id to see how well they are

**Comment by moon5ye** [comment]
Thank you so much!!!

Appreciate your wonderful work again!
