### ISSUE TITLE
Does centerpoint-pp use dynamic voxelization?

### ISSUE THREAD

**Issue by TianhaoFu** [tianweiy/CenterPoint#262]
it seems that the centerpoint-pp limit the max point within voxel using num=20.
https://github.com/tianweiy/CenterPoint/blob/master/configs/nusc/pp/nusc_centerpoint_pp_02voxel_two_pfn_10sweep.py
```
voxel_generator = dict(
    range=[-51.2, -51.2, -5.0, 51.2, 51.2, 3.0],
    voxel_size=[0.2, 0.2, 8],
    max_points_in_voxel=20,
    max_voxel_num=[30000, 60000],
)
```

So is there dynamic voxelization in centerpoint whether popintpillars-based or voxelnet-based?

**Comment by tianweiy** [comment]
currently only voxelnet uses dynamic voxelization.

**Comment by TianhaoFu** [comment]
thanks
