### ISSUE TITLE
training config files in original centerpoint paper

### ISSUE THREAD

**Issue by TianhaoFu** [tianweiy/CenterPoint#264]
Hi,

could you provide the config files of the result on nuscenes in your original cvpr2021 paper?
both voxelnet and pointpillars.

thanks!

**Comment by tianweiy** [comment]
I am confused. Everything is already provided. What do you want exactl

**Comment by TianhaoFu** [comment]
Hello, I looked at the repo again and have gotten what I wanted, thanks!
