### ISSUE TITLE
about global_vel_to_ref

### ISSUE THREAD

**Issue by mc171819** [tianweiy/CenterPoint#266]
Hi, i wonder what's the meaning of this function in waymo_decoder.py. I test this in segment-1005081002024129653_5313_150_5333_150_with_camera_labels.tfrecord, i get the speed before and after this function like this:
speed:0[20.330629091724095, 0.2304147476950128]
ref_speed:0[20.331686087123163, -0.09982205783806877, 0.0]

why the speed_x doesn't change much? In my thought, speed is the absolutu speed, ref speed is speed relative to the moving car so speed_x should smaller than absolute speed.

**Comment by tianweiy** [comment]
> ref speed is speed relative to the moving car so speed_x should smaller than absolute speed.


no, ref speed is not relative speed, it is still absolute speed but it is transformed to ego vehicle's pose.
