### ISSUE TITLE
Memory error when creating nuScenes data

### ISSUE THREAD

**Issue by koraykoca** [tianweiy/CenterPoint#267]
Hi, I am facing this issue while preparing nuScenes data. I am using Google Cloud Platform and have NVIDIA Tesla T4 with 16GB memory. Data creation takes almost 8 hours and gave this error in the end. Could you have a suggestion about what should I do before waiting for another 8 hours? 

██| 34149/34149 [8:20:26<00:00,  1.14it/s]
train sample: 28130, val sample: 6019
Traceback (most recent call last):
  File "tools/create_data.py", line 35, in <module>
    fire.Fire()
  File "/opt/conda/envs/cpkitti1/lib/python3.6/site-packages/fire/core.py", line 141, in Fire                            
    component_trace = _Fire(component, args, parsed_flag_args, context, name)                                            
  File "/opt/conda/envs/cpkitti1/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire                           
    target=component.__name__)
  File "/opt/conda/envs/cpkitti1/lib/python3.6/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace             
    component = fn(*varargs, **kwargs)
  File "tools/create_data.py", line 12, in nuscenes_data_prep
    nu_ds.create_nuscenes_infos(root_path, version=version, nsweeps=nsweeps, filter_zero=filter_zero)                    
  File "/home/koraykoca34/CenterPoint/det3d/datasets/nuscenes/nusc_common.py", line 603, in create_nuscenes_infos        
    pickle.dump(train_nusc_infos, f)
MemoryError

**Comment by tianweiy** [comment]
The file generates the info files and gt database. 

I can send you the info files if you want. Please send me an email yintianwei@utexas.edu 


 The gt database is however too large to share (generating info files takes less than ten minutes on my end, and maybe 30 - 60 minutes for the database, I think the io on google cloud is too slow).  You can disable gt sampling though, see instructions here Data creation takes almost 8 hours and gave this error in the end.

**Comment by tianweiy** [comment]
actually, you can download the info files here https://drive.google.com/file/d/1-qMtNx61lNUAm-s1-Afg--6rCqd672s7/view?usp=sharing

**Comment by koraykoca** [comment]
Thank you for the info files and for your fast response. 

Do you have an idea why this error occurred, maybe CPU RAM (13 GB) is not enough?

**Comment by tianweiy** [comment]
it could be. The nuScenes object will already take a few gigs when initialized.

**Comment by proggheli** [comment]
Hi! I sent you a email, could I also revive this files? I could not access the files from the link above.
