### ISSUE TITLE
Extension for training

### ISSUE THREAD

**Issue by Cascol-SCUT** [tianweiy/CenterPoint#269]
I want to add more features to each point, like its segmentic result from a 3D segmantic network. After reading the code, I wonder if  I can just concat it to voxel_features and do nothing. Currently I am using config ```nusc_centerpoint_voxelnet_0075voxel_fix_bn_z.py```, which gives me voxel_features with shape of [369252, 5].

**Comment by tianweiy** [comment]
i would suggest concatenate to point features here https://github.com/tianweiy/CenterPoint/blob/47d61adacb75ba6ccb49ae666dc257d04e323a2c/det3d/datasets/pipelines/loading.py#L40 

and then you can do nothing (except changing channel number in network). You may also need to disable gt sampling (or generate a new one that also contains these 3d semantic feature)

**Comment by Cascol-SCUT** [comment]
Thanks, I'll try to work it out
