### ISSUE TITLE
Not able to download waymo pretrained models

### ISSUE THREAD

**Issue by DeepakVellampalli** [tianweiy/CenterPoint#27]
@tianweiy 
Not able to download waymo pretrained models. Can you kindly give permission acess. Do the needful

**Comment by chowkamlee81** [comment]
Even iam also unable to download your pretrained models of waymo dataset. @tianweiy Kindly suggest

**Comment by tianweiy** [comment]
The link seemed to have some issue, can you try it now?

**Comment by chowkamlee81** [comment]
@tianweiy 
Iam able to download models and the model is very stable and working beautifully.
Hope you will release unified models (Vehicle/Pedestran/Cyclist) soon.
U made my day

**Comment by DeepakVellampalli** [comment]
Iam able to download both the waymo pretrained models.
@tianweiy 
Thankyou
