### ISSUE TITLE
tricks about result on nuscenes leaderboard

### ISSUE THREAD

**Issue by TianhaoFu** [tianweiy/CenterPoint#272]
Hi, what strategies are available for submitting results to the nuscenes list? Do you have a strategy for model ensamble or other data augmentation methods that you use? thanks!

**Comment by tianweiy** [comment]
I don't know much about tricks. Multimodal Virtual Point is our best entry and it only uses a single model without tta. 

AFAIK, you don't need to compare those ensemble models if you do any paper submission so I don't think any tricks are that useful.
