### ISSUE TITLE
where is the velocity information?

### ISSUE THREAD

**Issue by zyl1336110861** [tianweiy/CenterPoint#278]
hello, thank you for your sharing! I am confused when I try to find the gt velocity information in the dbinfos_train_2sweeps_withvelo.pkl. I failed to find it. So can you tell me where is it?

**Comment by zyl1336110861** [comment]
I can see the the shape of box3d_lidar in the dbinfos_train_2sweeps_withvelo.pkl is 1*9 instead of 1*7. Is that mean the extra two dimensions are the velocites?

**Comment by zyl1336110861** [comment]
I can see the the shape of box3d_lidar in the dbinfos_train_2sweeps_withvelo.pkl is 1x9 instead of 1x7. Is that mean the extra two dimensions are the velocites?

**Comment by tianweiy** [comment]
which dataset ?

**Comment by tianweiy** [comment]
and yes, two dimensions are velocitiies (index -2 -3)

https://github.com/tianweiy/CenterPoint/blob/3c64610e78756990c8f67732749806a7a83caa5a/det3d/datasets/nuscenes/nusc_common.py#L505

**Comment by zyl1336110861** [comment]
Waymo&nbsp;dataset


---Original---
From: &quot;Tianwei ***@***.***&gt;
Date: Sat, Mar 5, 2022 11:45 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tianweiy/CenterPoint] where is the velocity information? (Issue#278)




 
which dataset ?
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tianweiy** [comment]
yes, velocity is in this 9-dim vector see https://github.com/tianweiy/CenterPoint/blob/3c64610e78756990c8f67732749806a7a83caa5a/det3d/datasets/waymo/waymo_decoder.py#L193

**Comment by zyl1336110861** [comment]
OK！ Thank you so much!
