### ISSUE TITLE
About the waymo dataset processing

### ISSUE THREAD

**Issue by StiphyJay** [tianweiy/CenterPoint#281]
Hi, tianwei, Thanks for your great job. It's amazing! However, when I run your waymo dataset process code:

how many files in your 'WAYMO_DATASET_ROOT/train/lidar' path after you run this command:
`CUDA_VISIBLE_DEVICES=-1 python det3d/datasets/waymo/waymo_converter.py --record_path 'WAYMO_DATASET_ROOT/tfrecord_training/*.tfrecord'  --root_path 'WAYMO_DATASET_ROOT/train/'
`
When I run command above, I got different number files in this path: 'WAYMO_DATASET_ROOT/train/lidar.
I use the code from master branch, I got 158081 file in this path: WAYMO_DATASET_ROOT/train/lidar'. After this, When I run the command: `python tools/create_data.py waymo_data_prep --root_path=data/Waymo --split train --nsweeps=1`, There have some error:

**data/Waymo/gt_database_2sweeps_withvelo/VEHICLE/150720_VEHICLE_73.bin
data/Waymo/gt_database_2sweeps_withvelo/VEHICLE/149648_VEHICLE_43.bin
data/Waymo/gt_database_2sweeps_withvelo/VEHICLE/154136_VEHICLE_22.bin
data/Waymo/gt_database_2sweeps_withvelo/PEDESTRIAN/157042_PEDESTRIAN_13.bin
data/Waymo/gt_database_2sweeps_withvelo/VEHICLE/148520_VEHICLE_1.bin
data/Waymo/gt_database_2sweeps_withvelo/VEHICLE/155720_VEHICLE_55.bin
data/Waymo/gt_database_2sweeps_withvelo/VEHICLE/155740_VEHICLE_106.bin
data/Waymo/gt_database_2sweeps_withvelo/PEDESTRIAN/157070_PEDESTRIAN_29.bin
data/Waymo/gt_database_2sweeps_withvelo/PEDESTRIAN/156288_PEDESTRIAN_17.bin
data/Waymo/gt_database_2sweeps_withvelo/PEDESTRIAN/157298_PEDESTRIAN_42.bin
data/Waymo/gt_database_2sweeps_withvelo/VEHICLE/153060_VEHICLE_25.bin
data/Waymo/gt_database_2sweeps_withvelo/PEDESTRIAN/157846_PEDESTRIAN_5.bin
data/Waymo/gt_database_2sweeps_withvelo/VEHICLE/151236_VEHICLE_39.bin
data/Waymo/gt_database_2sweeps_withvelo/PEDESTRIAN/157662_PEDESTRIAN_25.bin
data/Waymo/gt_database_2sweeps_withvelo/PEDESTRIAN/156288_PEDESTRIAN_17.bin
data/Waymo/gt_database_2sweeps_withvelo/VEHICLE/147840_VEHICLE_41.bin
data/Waymo/gt_database_2sweeps_withvelo/PEDESTRIAN/156286_PEDESTRIAN_80.bin
data/Waymo/gt_database_2sweeps_withvelo/VEHICLE/154204_VEHICLE_41.bin
data/Waymo/gt_database_2sweeps_withvelo/VEHICLE/154024_VEHICLE_16.bin
data/Waymo/gt_database_2sweeps_withvelo/PEDESTRIAN/157042_PEDESTRIAN_13.bin**

However, when I use the code from new_relesae branch,  I got 134697 file in this path: WAYMO_DATASET_ROOT/train/lidar'.

So, I am confused, what is the correct number for those file? And I could have the correct final file for training in waymo dataset.

Look forward to your reply!

**Comment by tianweiy** [comment]
@StiphyJay 

158081 is the right number. 

```
 There have some error:

data/Waymo/gt_database_2sweeps_withvelo/VEHICLE/150720_VEHICLE_73.bin
data/Waymo/gt_database_2sweeps_withvelo/VEHICLE/149648_VEHICLE_43.bin
```

could you paste the full error (stack frame)? I don't know why it will output this message. 

> However, when I use the code from new_relesae branch, I got 134697 file in this path: WAYMO_DATASET_ROOT/train/lidar'.

this is weird. i don't know the reason.

**Comment by tianweiy** [comment]
Val / Test set results are available upon email request. I plan to add train prediction but I don't have the time / GPU / disk resources recently.

**Comment by BaiLiping** [comment]
thanks for your reply. My email is blp_engineer@outlook.com. Thanks a lot.

**Comment by BaiLiping** [comment]
just validation and test set results would do, we are running a traditional filter on it, so no training required. Thanks a lot.

**Comment by cyhasuka** [comment]
Hi,  @StiphyJay,
I found that you have tried to train centerpoint on waymo dataset, I would like to ask you if it is possible to share the checkpoint.pth file, I have accepted waymo's privacy agreement and would like to learn more about the algorithm but struggling to train it on my own due to lack of GPU and hard drive resources.
Sincerest thanks!
Look forward to your reply!
