### ISSUE TITLE
differences in the nuScenes volexnet config files

### ISSUE THREAD

**Issue by mreece813** [tianweiy/CenterPoint#283]
I was looking into the  nuScenes volexnet configs and was wondering what are the main differences between them. When i was taking a look they looked to be mostly the same codes but what are those differences between the files?

Thanks for any response

**Comment by tianweiy** [comment]
see the name of the file.

1. dcn ones use deformable convolution but it is not useful in the most recent codebase (kept for backward compatibility)

2. 0075 / 0 1 means 0.075 meter or 0.1 meter for voxel size 

3. flip means using flip test time augmentation (4x slower, slightly higher accuracy)

Let me know if you have further questiosn
