### ISSUE TITLE
About the nuScenes dataset

### ISSUE THREAD

**Issue by 18lalala** [tianweiy/CenterPoint#284]
should I download all the files or just the metadata file(0.43GB)?

**Comment by tianweiy** [comment]
all files

**Comment by 18lalala** [comment]
sry,when running the demo,i met this error
(centerpoint) puzek@104-server:~/ljy_projects/CenterPoint$ python tools/demo.py 
Import spconv fail, no support for sparse convolution!
No Tensorflow
Deformable Convolution not built!
Use HM Bias:  -2.19
10
The model and loaded state dict do not match exactly

missing keys in source state_dict: reader.pfn_layers.1.linear.weight, reader.pfn_layers.1.norm.bias, reader.pfn_layers.1.norm.running_mean, reader.pfn_layers.1.norm.running_var, reader.pfn_layers.1.norm.weight

these keys have mismatched shape:
+---------------------------------------+----------------------+----------------------+
| key                                   | expected shape       | loaded shape         |
+---------------------------------------+----------------------+----------------------+
| reader.pfn_layers.0.linear.weight     | torch.Size([32, 10]) | torch.Size([64, 10]) |
| reader.pfn_layers.0.norm.weight       | torch.Size([32])     | torch.Size([64])     |
| reader.pfn_layers.0.norm.bias         | torch.Size([32])     | torch.Size([64])     |
| reader.pfn_layers.0.norm.running_mean | torch.Size([32])     | torch.Size([64])     |
| reader.pfn_layers.0.norm.running_var  | torch.Size([32])     | torch.Size([64])     |
+---------------------------------------+----------------------+----------------------+
Traceback (most recent call last):
  File "tools/demo.py", line 130, in <module>
    main()
  File "tools/demo.py", line 86, in main
    points = data_batch['points'][:, 1:4].cpu().numpy()
TypeError: list indices must be integers or slices, not tuple
