### ISSUE TITLE
just to clarify, here 10 sweep means aggregate 10 frames of lidar data right?

### ISSUE THREAD

**Issue by BaiLiping** [tianweiy/CenterPoint#288]
The one without flip augmentation https://drive.google.com/drive/folders/1OazJ7wULZcDtE-grW2AKBkMnA0h1Co98?usp=sharing  (66.8 NDS val performance)

The one with flip augmentation https://drive.google.com/drive/folders/14TvJegUV1BPCw5oWqEwR0AvXM8tjLsQt?usp=sharing (68.5 NDS val performance)

_Originally posted by @tianweiy in https://github.com/tianweiy/CenterPoint/issues/249#issuecomment-1015891599_

**Comment by tianweiy** [comment]
yes
