### ISSUE TITLE
voxelnet

### ISSUE THREAD

**Issue by Liaoqing-up** [tianweiy/CenterPoint#300]
hello, tianweiy. I debug the source code, find that in Voxelnet there seems to be no VFE layer in each voxel, but directly use 3D sparse convolution , is that right?

**Comment by Liaoqing-up** [comment]
and... can you explain the point features meaning as the feature shape is 21?
an example in a pillar point :
```
tensor([-1.0799e+01,  1.0660e+00, -2.0542e+00,  9.0000e+00,  1.0000e+00,
         1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,
         1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,  0.0000e+00,
         0.0000e+00, -9.9692e-02, -3.6344e-02,  3.8075e-04, -9.8801e-02,
        -3.4023e-02], device='cuda:0')
```
the first three are the absolute coordinates of the point, the last five are relative coordinates, but what about the othes? The 5th-15th look like painted mask label? And others?

**Comment by tianweiy** [comment]
> The 5th-15th look like painted mask label

It is a padding of 1 for real points. See https://github.com/tianweiy/CenterPoint/blob/2145ada1f96b7b4b8f19f3b0012aab589962806f/det3d/datasets/pipelines/loading.py#L35 for details

**Comment by Liaoqing-up** [comment]
> 

ok, i have got it, thankyou ~

**Comment by tianweiy** [comment]
yes, it is a simplified version of VoxelNet (used in SECOND paper and all follow-up works). Simple mean proves to be efficient and effective so people adopted this in the end

**Comment by jjimin** [comment]
I got it!!!! Thank you for your kind answer!
