### ISSUE TITLE
Waymo training set preprocessing

### ISSUE THREAD

**Issue by jacobson15p** [tianweiy/CenterPoint#304]
I'm trying to preprocess the waymo training data, however it looks like when I try to generate the info files using create_data.py I'm running out of memory when trying to pickle the info:

```
train  split  exist frame num: 158081
100%|##############################################################################################################################| 158081/158081 [13:12<00:00, 199.36it/s]
sample: 158081
Killed

```
My machine has 256 GB RAM; does generating the training info file really require more than that, or is there something else I am not understanding?

**Comment by tianweiy** [comment]
> does generating the training info file really require more than that

it doesn't. The pkl file should be smaller than 900 mb.

**Comment by jacobson15p** [comment]
Really? I was getting a pkl file of 60 GB with 100000 frames. Any idea why that is?

**Comment by jacobson15p** [comment]
Actually I realized I added extra info to the pkl files, that must be why the are so much bigger.
