### ISSUE TITLE
Question about multi sweep

### ISSUE THREAD

**Issue by mc171819** [tianweiy/CenterPoint#306]
Hi, I'm wondering about why multi frame is more accurate than single frame, since moving object may have ghosting.

**Comment by mc171819** [comment]
@tianweiy

**Comment by tianweiy** [comment]
I think it mainly help for 
1. stationary objects, where there is no ghost effect and you get more points 
2. dynamic objects, where you can infer the rotation / velocity much better with multi sweep 

> since moving object may have ghosting

that's right. But as all the points are concatenated with their timestamp the model is able to gather useful information from ghosting point clouds.
