### ISSUE TITLE
Reproduce the CenterPoint-Pillar with two 2080Ti

### ISSUE THREAD

**Issue by XYunaaa** [tianweiy/CenterPoint#31]
Hi!
I tried to reproduce your experiment on two 2080Tis.
According to your code, I used the training method in your paper, but **the training result is still about 28mAP**.
In your paper, you used some methods to replicate the experiment on pointPillar, which increased the experimental results to 45.5mAP.
How did you solve it? 
Is it related to the machine(you use 4 V100s)?
Thank you

**Comment by tianweiy** [comment]
I don't think 4 or 2 gpu matter that much. Could you upload your training log here or send it to my email? Also show the commit id of your centerpoint version and probably git diff result.

**Comment by tianweiy** [comment]
Figure out that the problem is the training set contains only a few thousand images. Please reopen the issue if you still can't reproduce result with full train set
