### ISSUE TITLE
Error(s) in loading state_dict for VoxelNet 

### ISSUE THREAD

**Issue by ajinkyakhoche** [tianweiy/CenterPoint#317]
Thank you for your wonderful contribution! 

When running [single_inference_ros.py](https://github.com/tianweiy/CenterPoint/blob/master/tools/single_infernece_ros.py#L90) , line 93, I get the following error. Tried pre-trained weights from [model zoo](https://github.com/tianweiy/CenterPoint/blob/master/configs/nusc/README.md#voxelnet)(VoxelNet) for nuscenes 

`Error(s) in loading state_dict for VoxelNet:

	size mismatch for backbone.conv_input.0.weight: copying a param with shape torch.Size([3, 3, 3, 5, 16]) from checkpoint, the shape in current model is torch.Size([16, 3, 3, 3, 5]).
	
	size mismatch for backbone.conv1.0.conv1.weight: copying a param with shape torch.Size([3, 3, 3, 16, 16]) from checkpoint, the shape in current model is torch.Size([16, 3, 3, 3, 16]).
	
	size mismatch for backbone.conv1.0.conv2.weight: copying a param with shape torch.Size([3, 3, 3, 16, 16]) from checkpoint, the shape in current model is torch.Size([16, 3, 3, 3, 16]).
	
	size mismatch for backbone.conv1.1.conv1.weight: copying a param with shape torch.Size([3, 3, 3, 16, 16]) from checkpoint, the shape in current model is torch.Size([16, 3, 3, 3, 16]).
	
	size mismatch for backbone.conv1.1.conv2.weight: copying a param with shape torch.Size([3, 3, 3, 16, 16]) from checkpoint, the shape in current model is torch.Size([16, 3, 3, 3, 16]).
	
	size mismatch for backbone.conv2.0.weight: copying a param with shape torch.Size([3, 3, 3, 16, 32]) from checkpoint, the shape in current model is torch.Size([32, 3, 3, 3, 16]).
	
	...`
	
Further info: Installed using standard [instructions](https://github.com/tianweiy/CenterPoint/blob/master/docs/INSTALL.md), using pytorch 1.8.1+cu11, spconv-cu111

Any advice?

**Comment by tianweiy** [comment]
it should work now https://github.com/tianweiy/CenterPoint/commit/8fcdc944bbb455bd25943b331aaf961aa0ab32cd

just pull the code again

**Comment by ajinkyakhoche** [comment]
Thanks for your quick reply! I can confirm this works. In order to load the model, for eg. in [single_inference_ros.py, line 90](https://github.com/tianweiy/CenterPoint/blob/master/tools/single_infernece_ros.py#L90), one can:

change 

`self.net.load_state_dict(torch.load(self.model_path)["state_dict"])`

to 
```
state_dict = torch.load(self.model_path)["state_dict"]
torchie.load_state_dict(self.net, state_dict)
