### ISSUE TITLE
Questions about the size of the prediction map

### ISSUE THREAD

**Issue by jialeli1** [tianweiy/CenterPoint#32]
Hi. 
Q1. Is the size of your prediction maps for heat and box reg both 128 × 128?
Q2. How to understand the _dense reg_, if only the pixels at the keypoints locations (heat=1.0) are used to train box regression?

Thank you very much.

**Comment by tianweiy** [comment]
Q1 Which config does you refer to ? The output resolution is different for different model / dataset / voxel size.

Q2 The dense reg is a trick we tried in centernet / centerpoint. So basically, we can also allow regression from a center 3*3 area. The original idea is that in this way we can get more accurate regression even if the keypoint is off by one or two pixels. We didn't get this work too well yet so we still only regress to other attributes at center locations.

**Comment by jialeli1** [comment]
> Q1 Which config did you refer to ? The output resolution is different for different model / dataset / voxel size.
> 
> Q2 The dense reg is a trick we tried in centernet / centerpoint. So basically, we can also allow regression from a center 3*3 area. The original idea is that in this way we can get more accurate regression even if the keypoint is off by one or two pixels. We didn't get this work too well yet so we still only regress to other attributes at center locations. 

Thanks for your reply.
Q1. For example, what is the prediction map resolution in config VoxelNet-1440_dcn_flip and VoxelNet-1024? I just want to know the effect of resolution on the result.
Q2. I agree with your point that the center area is still helpful for box regression. But only the center point is used in your code and the original CenterNet code. I tried using center area to train box regression, but it didn't work very well. This confuses me. Did this idea work in your attempts?

**Comment by tianweiy** [comment]
Q1 For voxelnet, the output stride is 8 do voxel_1440 -> 1440/8 for the prediction map. Larger output resolution / smaller voxel size is generally better but it takes more time. 

Q2 > We didn't get this work too well yet so we still only regress to other attributes at center locations (in both repos)
