### ISSUE TITLE
the problem of "Create into files" when preparing waymo data

### ISSUE THREAD

**Issue by xiaoxishuo** [tianweiy/CenterPoint#321]
hi, i have followed the suggestion to prepare **Waymo** data. Download waymo data,convert th tfrecord to pickle, and create a symlink successfully. The next step is Create into files.
But when i run ```python tools/create_data.py waymo_data_prep --root_path=data/Waymo --split=val --nsweeps=1```
i get this error,
**nuScenes devkit not found!
Import spconv fail, no support for sparse convolution!
iou3d cuda not built. You don't need this if you use circle_nms. Otherwise, refer to the advanced installation part to build this cuda extension
no apex
nuScenes devkit not Found!
[libprotobuf FATAL google/protobuf/stubs/common.cc:83] This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.20.1).
  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verificat
ion failed in "bazel-out/k8-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.20.1).  Contact the program author for an update. 
 If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-opt/bin/tensorfl
ow/core/framework/tensor_shape.pb.cc".)
Aborted**
and failed to ceate **infos_val_01sweeps_filter_zero_gt.pkl**
how can i solve this?

**Comment by tianweiy** [comment]
interesting, could you figure out which line of this file https://github.com/tianweiy/CenterPoint/blob/8fcdc944bbb455bd25943b331aaf961aa0ab32cd/det3d/datasets/waymo/waymo_common.py#L307 does the program fail? (add some print statements to debug)?

**Comment by xiaoxishuo** [comment]
yes，i add some print statement and find out it didn't enter  `create_waymo_infos` function.Besides，It seems cannot solved by updating `Protocol Buffer version`.
After adding some print statements to debug，I finally found it was the `import` problem, now the error  has disappeared.
Thank you very much!
