### ISSUE TITLE
when creating training data, why the gt_database_1sweeps_withvelo is empty? 

### ISSUE THREAD

**Issue by liuronghuang** [tianweiy/CenterPoint#327]
Question about create_groundtruth_database.

Hi, sorry to bother you, i got a question about create_grounth_database when i train using the waymo dataset. I follow the tutorial `python tools/create_data.py waymo_data_prep --root_path=data/Waymo --split train --nsweeps=1` and after the code finishes, i found the gt_database_1sweeps_withvelo folder empty. Is there something wrong? And i found the function "get_sensor_data" in “det3d/datasets/waymo/waymo.py” sets the points and annotations in dict{res} to None by default. It's the reason why the gt_database folder is empy?

Or maybe I'm just overthinking? Maybe the files in gt_database would not have been generated when creating training data?

**Comment by tianweiy** [comment]
the none won't matter. 

So you now successfully generate the info files but not the gt_database? 

I would suggest adding some print statement inside this function https://github.com/tianweiy/CenterPoint/blob/8fcdc944bbb455bd25943b331aaf961aa0ab32cd/tools/create_data.py#L25

and see why the file doesn't save to the directory. 

e.g. check the length of the dataset at https://github.com/tianweiy/CenterPoint/blob/8fcdc944bbb455bd25943b331aaf961aa0ab32cd/det3d/datasets/utils/create_gt_database.py#L72

or check the file saving at https://github.com/tianweiy/CenterPoint/blob/8fcdc944bbb455bd25943b331aaf961aa0ab32cd/det3d/datasets/utils/create_gt_database.py#L130

**Comment by liuronghuang** [comment]
Thanks for your repaly! I'll try and checkout, appericate!

**Comment by liuronghuang** [comment]
The reason is that waymo dataset v.10 has a bug, details in [https://github.com/waymo-research/waymo-open-dataset/issues/117#issuecomment-1011309632](url). 

Dataset v1.0 populates all `num_lidar_points_in_box` with 0.
https://github.com/tianweiy/CenterPoint/blob/8fcdc944bbb455bd25943b331aaf961aa0ab32cd/det3d/datasets/waymo/waymo_common.py#L262

So cause `mask_not_zero` to be 0
https://github.com/tianweiy/CenterPoint/blob/8fcdc944bbb455bd25943b331aaf961aa0ab32cd/det3d/datasets/waymo/waymo_common.py#L273

The script filter all gt boxes, that's why `gt_database` folder is empty and the box_loss is always 0 when training.
https://github.com/tianweiy/CenterPoint/blob/8fcdc944bbb455bd25943b331aaf961aa0ab32cd/det3d/datasets/waymo/waymo_common.py#L275

Solutions:
1. Download the latest waymo dataset
2. Design a function to count the number of points in gt_3d_box
3. Ignore the `# filter boxes without lidar points` and `mask_not_zero` (not recommanded)
https://github.com/tianweiy/CenterPoint/blob/8fcdc944bbb455bd25943b331aaf961aa0ab32cd/det3d/datasets/waymo/waymo_common.py#L276
rewrite:
`info['gt_boxes'] = gt_boxes.astype(np.float32)`
`info['gt_names'] = gt_names.astype(str)`
