### ISSUE TITLE
Why do we use conv with bias before batch norm in spconv backbone?

### ISSUE THREAD

**Issue by zhanggefan** [tianweiy/CenterPoint#328]
Hi!
First of all, thank you for your fantastic work and it helps me a lot with my research.
But I also found some code that puzzles me: we use conv with bias everywhere before batch norm in the `SpMiddleResNetFHD` backbone. Did you do this on purpose? As far as I know, the bias here will have no effect because it will be normalized out by BN.
https://github.com/tianweiy/CenterPoint/blob/8fcdc944bbb455bd25943b331aaf961aa0ab32cd/det3d/models/backbones/scn.py#L68

**Comment by tianweiy** [comment]
nope. without bias should also work
