### ISSUE TITLE
data generation failed when running create_data.py 

### ISSUE THREAD

**Issue by MengmengLi19** [tianweiy/CenterPoint#329]
Hi author, 
I downloaded nuScenes v1.0-mini,  when I ran create_data.py, there should be 4 new files generated as shown in NUSC.md
however, the following 2 files were not generated :
                     |──dbinfos_train_10sweeps_withvelo.pkl <-- GT database info files
                     |── gt_database_10sweeps_withvelo <-- GT database 
Could you please suggesting the solving method or the reason of failure on generating the 2 files? 

I think there was something I ignored because  an error appears ------No such file or directory: 'data/nuScenes/dbinfos_train_10sweeps_withvelo.pkl''  when I continued to run "python tools/train.py configs/nusc/pp/nusc_centerpoint_pp_02voxel_two_pfn_10sweep.py"

**Comment by tianweiy** [comment]
change this statement to include v1.0-mini https://github.com/tianweiy/CenterPoint/blob/8fcdc944bbb455bd25943b331aaf961aa0ab32cd/tools/create_data.py#L13
