### ISSUE TITLE
Parameter about post_center_limit_range in test_cfg

### ISSUE THREAD

**Issue by YaoHan404** [tianweiy/CenterPoint#33]
post_center_limit_range=[-61.2, -61.2, -10.0, 61.2, 61.2, 10.0]
anchor_ranges=[-51.2, -51.2, 0.49, 51.2, 51.2, 0.49]
 
post_center_limit_range is larger than anchor_ranges,  why not equal?
Exist any meaningful prediction boxes between  51.2 and 61.2?

**Comment by tianweiy** [comment]
Yeah, maybe there are some objects.

**Comment by YaoHan404** [comment]
Thank you. @tianweiy
