### ISSUE TITLE
Initialization problems

### ISSUE THREAD

**Issue by changjiahao** [tianweiy/CenterPoint#333]
Thank you for your work！I want to ask why the heatmap is initialized to -2.19，I am based on the model and tried to allocate positive and negative samples in the dense way but  performance is not good

**Comment by tianweiy** [comment]
https://github.com/tianweiy/CenterPoint/issues/154#issuecomment-872664072

there is no defined rule for initialization. I follow this from centernet and it works in my setting

**Comment by changjiahao** [comment]
ok thk
