### ISSUE TITLE
The tensorflow version

### ISSUE THREAD

**Issue by SakuraRiven** [tianweiy/CenterPoint#340]
I noticed that the waymo dataset needs TF **just** to address the tfrecord data?

I am not familiar with tf and wondering which version is correct. Does ```import tensorflow.compat.v2 as tf``` means that: if using tf1.x it will switch to 2.x automatically, but using 2.x it will be fine without doing anything?

**Comment by tianweiy** [comment]
I don't know much about tf. This part is copied from the official devkit

**Comment by SakuraRiven** [comment]
I see, thanks for your reply
