### ISSUE TITLE
About waymo infos

### ISSUE THREAD

**Issue by SakuraRiven** [tianweiy/CenterPoint#341]
Hi, I have some questions:

1. Why would we have to transform from Waymo to KITTI coordinate, like ![here](https://github.com/tianweiy/CenterPoint/blob/master/det3d/datasets/waymo/waymo_common.py#L266)

2. Maybe the ![following comments](https://github.com/tianweiy/CenterPoint/blob/master/det3d/datasets/waymo/waymo_common.py#L267) are wrong? I just noticed that https://github.com/tianweiy/CenterPoint/issues/136#issuecomment-840150281
```
Waymo: x, y, z, length, width, height, rotation from positive x axis clockwisely
KITTI: x, y, z, width, length, height, rotation from negative y axis counterclockwisely 
```

3. And as a beginner I also confused about sweeps, would you mind briefly explaining nsweeps=1=2 ?

**Comment by tianweiy** [comment]
1. Because we work with multiple datasets and need a unified coordinate system to deal with the data.

2. Yeah, the comments should be changed to the one in the issue you mentioned.

3. Sweeps refer to the number of point cloud you use. Sweep=1 means you only use the most recent point cloud, 2,3 or so means you combine pc from the last 2/3 time steps

**Comment by SakuraRiven** [comment]
Thanks for your kind reply~

> 1. Because we work with multiple datasets and need a unified coordinate system to deal with the data.

So we can use data with a unified manner to train our model. However, the format is supposed to restore original when we submitting test results?




>  3. Sweeps refer to the number of point cloud you use. Sweep=1 means you only use the most recent point cloud, 2,3 or so means you combine pc from the last 2/3 time steps

Besides tracking task, I think we just need sweep=1 to train a detection model. Does  ```2 sweep detection``` means transform points among 2 frames into the same coordinates so that we can get more dense points and achieve more accurate results? Is that a common trick to improve the performance? Where could we find any related experiments?

**Comment by tianweiy** [comment]
It is restored here https://github.com/tianweiy/CenterPoint/blob/8fcdc944bbb455bd25943b331aaf961aa0ab32cd/det3d/datasets/waymo/waymo_common.py#L71

It is. It will be a few points higher with 2/3 frames. You can see the results section

**Comment by tianweiy** [comment]
https://github.com/tianweiy/CenterPoint/blob/master/configs/waymo/README.md

**Comment by SakuraRiven** [comment]
@tianweiy Thanks for your reply

You mean that the two-frame fusion could boost performance by introducing more points to present more accurate appearance? I agree but it requires short time gap so that the objects in two frames could match. Otherwise the ```gt_database``` which only take current boxes to cover objects among frames with different times would bring noise points.

And the fusion also bring more computation. So, it‘s only a common trick to improve performance in competitions? I noticed that the origin paper did not mentioned. Meanwhile, Does practical applications also take this way to improve performance?
