### ISSUE TITLE
spconv安装失败

### ISSUE THREAD

**Issue by wfs123456** [tianweiy/CenterPoint#347]
已经安装了cuda10.0.及 cudnn10.0依旧报错，可以帮忙看一下吗
/CMakeDetermineCUDACompiler.cmake:277 (message):
  CMAKE_CUDA_ARCHITECTURES must be non-empty if set.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

**Comment by tianweiy** [comment]
还是pip install 吧。 自己编译有各种各样问题，每台机器都不一样。用新一点的torch version, 然后按这里教程装下spconv 2.x https://github.com/traveller59/spconv 

apex 新torch version 可能用不了，把这行换成https://pytorch.org/docs/stable/generated/torch.nn.SyncBatchNorm.html#torch.nn.SyncBatchNorm.convert_sync_batchnorm
