### ISSUE TITLE
class classification in CenterPoint

### ISSUE THREAD

**Issue by SakuraRiven** [tianweiy/CenterPoint#348]
Hi, where could I find the classification probs in CenterPoint of all classes, such as nusceces datasets. I only find separate heads with regression outputs.

**Comment by ApoorvaSuresh** [comment]
Hi, have you found the solution to this question? I'm trying to find the same. Please let me know, thank you!

**Comment by SakuraRiven** [comment]
@ApoorvaSuresh Hi, there are no probs cause the objects are detected on local max position with specific head. The same position outputs of other heads should not combine or softmax.
