### ISSUE TITLE
Tracking Inference Code

### ISSUE THREAD

**Issue by YoushaaMurhij** [tianweiy/CenterPoint#35]
Could you please provide a simple tracking function similar to the _single_inference.py_ ROS code?
I tried to implement pub_test.py in ROS with no success [The tracker seems to work only for nuSences data]. 
I am trying to get tracking results by applying raw Lidar point clouds to get detections (BBox + score + type) and track them in the next lidar point cloud.

**Comment by tianweiy** [comment]
I don't know any ROS. Though I will prepare a simple python demo using raw lidar point clouds like #34 when I get time.

**Comment by YoushaaMurhij** [comment]
Thanks for your response!
A simple tracking demo using raw lidar point clouds would be very helpful.

**Comment by YoushaaMurhij** [comment]
Another question: You are using object velocity in your tracking script. but it is not clear how to got it from the detection script. Are you using some data from the dataset that are not in the output of the detection model? or I am missing something?

**Comment by tianweiy** [comment]
our model will predict the velocity in the detection. The box also contains the velocity prediction for the respective object https://github.com/tianweiy/CenterPoint/blob/5f3b3e141c3139baeaa8f461366f5cd17710cb12/det3d/models/bbox_heads/mg_head.py#L1781

**Comment by tianweiy** [comment]
Get way too many deadlines recently. I will try to work on this on Thursday.

**Comment by YoushaaMurhij** [comment]
I am trying implement **Tracking** inside the ROS inference code. Specifically inside the `def run(self, points)` function
in `class Processor_ROS`  in similar way to the tracking which is done in `pub_test.py`. But seems to be a little complicated for me!
The way the data is collected and formatted makes it harder. Can you please check my initial code thoughts? It should be something like this:

```

        with torch.no_grad():
            outputs = self.net(self.inputs, return_loss=False)[0]
        # print(f"output: {outputs}")
        torch.cuda.synchronize()
        print("  network predict time cost:", time.time() - t)
        outputs = remove_low_score_nu(outputs, 0.45)
        #========================== Tracking ======================
        for idx, output in enumerate(outputs):
            token = idx      #TODO we don't need tokens in ROS
            for k, v in output.items():
                if k not in [
                    "metadata",
                ]:
                    output[k] = v.to(cpu_device)
            detections.update(
                {idx: output,}
            )
        
        if frames[i]['first']:   #TODO add the right condition in ROS (start of a ROSbag)
            tracker.reset()
            last_time_stamp = frames[i]['timestamp']

        time_lag = (frames[i]['timestamp'] - last_time_stamp)   #TODO get time stamp from ROSbag
        last_time_stamp = frames[i]['timestamp']

        preds = detections    #TODO check if this format is correct as an input 

        tracks = tracker.step_centertrack(preds, time_lag)
        annos = []

        for item in tracks:
            if item['active'] == 0:
                continue 
            nusc_anno = {
                "sample_token": token,               
                "translation": item['translation'],
                "size": item['size'],
                "rotation": item['rotation'],
                "velocity": item['velocity'],
                "tracking_id": str(item['tracking_id']),
                "tracking_name": item['detection_name'],
                "tracking_score": item['detection_score'],
            }
            annos.append(nusc_anno)
        #nusc_annos["results"].update({token: annos})
        #========================================================================
        boxes_lidar = outputs["box3d_lidar"].detach().cpu().numpy()
        print("  predict boxes:", boxes_lidar.shape)
        scores = outputs["scores"].detach().cpu().numpy()
        types = outputs["label_preds"].detach().cpu().numpy()
        boxes_lidar[:, -1] = -boxes_lidar[:, -1] - np.pi / 2
        print(f"  total cost time: {time.time() - t_t}")
        return scores, boxes_lidar, types
```

**Comment by tianweiy** [comment]
It is generally correct, another thing is that we do the tracking in the global coordinate (so that the center distance is accurate), so all detection boxes need to be transformed to global first.

**Comment by YoushaaMurhij** [comment]
How to convert the tracking results from Lidar coordinates system to global coordinates system?

**Comment by tianweiy** [comment]
https://github.com/tianweiy/CenterPoint/blob/ce9591caa8361df963c230a0d5622cc77dba8b85/det3d/datasets/nuscenes/nusc_common.py#L226 

https://github.com/tianweiy/CenterPoint/blob/ce9591caa8361df963c230a0d5622cc77dba8b85/det3d/datasets/nuscenes/nusc_common.py#L247

**Comment by YoushaaMurhij** [comment]
Thanks! I will check that.

**Comment by iamsiddhantsahu** [comment]
@YoushaaMurhij Yes, I am also trying exactly the same. Where you able to plot/visualise the tracking id, velocity etc in ROS rviz?

**Comment by tianweiy** [comment]
see [this](https://github.com/tianweiy/CenterPoint/issues/35#issuecomment-687852566) contains translation from detection box in local coordinate to nusc box in global one which contains 'translation' / 'velocity' / etc..

**Comment by iamsiddhantsahu** [comment]
@tianweiy This question is not related to the issue subject.

I wanted to "test" the trained model. So I need to first run the 
`python tools/dist_test.py configs/centerpoint/nusc_centerpoint_voxelnet_dcn_0075voxel_flip_testset.py --work_dir work_dirs/nusc_centerpoint_voxelnet_dcn_0075voxel_flip_testset  --checkpoint work_dirs/nusc_centerpoint_voxelnet_dcn_0075voxel_flip_testset/epoch_20.pth  --speed_test `

This generates a `prediction.pkl` file in the `work_dirs/nusc_centerpoint_voxelnet_dcn_0075voxel_flip_track_circle_nms`

But then for tracking, the `pub_test.py` file uses `--checkpoint work_dirs/nusc_centerpoint_voxelnet_dcn_0075voxel_flip_testset/infos_test_10sweeps_withvelo.json` which is **JSON file not a pkl file**. 

Is the `infos_test_10sweeps_withvelo.json` **JSON** file generated somewhere?

**Comment by tianweiy** [comment]
https://github.com/tianweiy/CenterPoint/blob/ce9591caa8361df963c230a0d5622cc77dba8b85/det3d/datasets/nuscenes/nuscenes.py#L280

**Comment by tianweiy** [comment]
The dust test also generate the json file

**Comment by iamsiddhantsahu** [comment]
@tianweiy Thanks! 

What does this part of @YoushaaMurhij  code does? Kindly help!
```
for idx, output in enumerate(outputs):
            token = idx      #TODO we don't need tokens in ROS
            for k, v in output.items():
                if k not in [
                    "metadata",
                ]:
                    output[k] = v.to(cpu_device)
            detections.update(
                {idx: output,}
            )
        
        if frames[i]['first']:   #TODO add the right condition in ROS (start of a ROSbag)
            tracker.reset()
            last_time_stamp = frames[i]['timestamp']

        time_lag = (frames[i]['timestamp'] - last_time_stamp)   #TODO get time stamp from ROSbag
        last_time_stamp = frames[i]['timestamp']
```

**Comment by tianweiy** [comment]
it is trying to combine dist_test.py and tracking scripts together to do the inference simultaneously.

**Comment by iamsiddhantsahu** [comment]
But in `pub_test.py` file, the `predictions` are read from the `infos_test_10sweeps_withvelo.json` file which in-turn is saved in this line `result_dict, _ = dataset.evaluation(copy.deepcopy(predictions), output_dir=args.work_dir, testset=args.testset)` in `dist_test.py`.

Is the `predictions.pkl` saved by the `dist_test.py` file used by the `pub_test.py`? I did not find this, hence asking. I am confused!

**Comment by tianweiy** [comment]
never use the prediction file here. it is for some debugging in the past.

**Comment by iamsiddhantsahu** [comment]
@tianweiy Then **tracking** does not use any of the following output generated from the detection `dist_test.py` file? Tracking `pub_test.py` directly takes as input the dataset?
```
output: {'box3d_lidar': tensor([[ 9.9622e+00, -1.5653e+01, -1.3735e+00,  1.8272e+00,  4.4392e+00,
          1.5047e+00,  3.5599e-04,  7.8504e-02,  3.1200e+00],
        [-3.7680e+00,  7.8447e+00, -8.2704e-02,  2.0590e+00,  5.0508e+00,
          1.9489e+00, -8.3359e-01,  6.9724e-01,  2.1452e+00],
        [ 9.3646e+00, -2.5846e+01, -1.3691e+00,  2.0195e+00,  4.9597e+00,
          1.8110e+00,  2.6763e-01,  2.9621e+00, -3.1260e+00],
        [-1.7989e+01,  1.7998e+01,  5.9649e-01,  6.6684e-01,  6.8670e-01,
          1.6805e+00, -2.7001e-04,  1.4420e-03,  6.4967e-01],
        [-1.2270e+01,  8.5350e+00,  1.5631e-01,  6.2731e-01,  6.3689e-01,
          1.7214e+00, -2.0684e-03,  3.3646e-03, -1.8001e+00],
        [-1.8881e+01,  1.3918e+01,  9.7650e-01,  6.6738e-01,  6.4197e-01,
          1.7872e+00, -3.4912e-03,  3.5000e-02,  1.8835e+00],
        [-1.7862e+01,  1.9430e+01,  4.9828e-01,  6.3351e-01,  6.5442e-01,
          1.6758e+00,  1.0614e-03,  1.9659e-03, -3.8113e-02],
        [ 1.3766e+01, -1.5658e+01, -3.6719e-01,  2.9548e+00,  1.2072e+01,
          3.6967e+00, -9.4899e-03, -1.0434e-01,  2.9855e-02],
        [-8.5540e+00,  1.7949e+01,  1.1463e+00,  3.0667e+00,  1.3574e+01,
          3.6558e+00, -5.2315e-02,  1.1627e+00,  3.1190e+00],
        [-1.1288e+00,  3.0740e+01,  1.0409e+00,  2.9851e+00,  1.1432e+01,
          3.6119e+00,  7.9563e-03, -8.1026e-01,  2.5238e-02],
        [ 3.2393e+00,  1.6580e+01, -8.5103e-01,  3.8145e-01,  3.9565e-01,
          8.9926e-01, -1.0882e-04, -2.5205e-04,  3.0865e+00],
        [-8.1991e+00,  4.8732e+00, -4.3984e-01,  3.5569e-01,  3.6195e-01,
          9.9219e-01,  4.0683e-04, -2.2539e-03, -2.3968e+00]], device='cuda:0'), 'scores': tensor([0.8888, 0.6593, 0.5230, 0.4013, 0.3509, 0.3183, 0.3071, 0.4742, 0.3239,
        0.3197, 0.4174, 0.3065], device='cuda:0'), 'label_preds': tensor([0., 0., 0., 8., 8., 8., 8., 3., 3., 3., 9., 9.], device='cuda:0')}
  predict boxes: (12, 9)
  total cost time: 0.1655569076538086
total callback time:  0.1669299602508545
```

**Comment by tianweiy** [comment]
I mean dist_test.py generate both prediction.pkl and XX.json files. The tracking takes the XX.json

**Comment by iamsiddhantsahu** [comment]
@YoushaaMurhij @tianweiy I think the `outputs` returned by the model in the `single_inference.py` file does not matches the format with the `outputs` returned by the `batch_processor()` function in the `dist_test.py` file. 

I am getting this error.
```
[ERROR] [1600080671.250302]: bad callback: <function rslidar_callback at 0x7feadc683950>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "single_inference2.py", line 248, in rslidar_callback
    scores, dt_box_lidar, types = proc_1.run(np_p)
  File "single_inference2.py", line 151, in run
    for k, v in output.items():
AttributeError: 'str' object has no attribute 'items'
```

**Comment by iamsiddhantsahu** [comment]
@tianweiy I am having trouble passing the [`outputs`](https://github.com/tianweiy/CenterPoint/blob/master/tools/single_infernece.py#L139) from the trained model inference into the [tracking](https://github.com/tianweiy/CenterPoint/issues/35#issuecomment-683940665) part added by @YoushaaMurhij.

Kindly help how can I format the [`outputs`](https://github.com/tianweiy/CenterPoint/blob/master/tools/single_infernece.py#L139) so that it can be passed to the [tracker.step_centertrack()](https://github.com/tianweiy/CenterPoint/blob/master/tools/tracking/pub_test.py#L112) function

**Comment by tianweiy** [comment]
https://github.com/tianweiy/CenterPoint/blob/e2fc27918a451f908bb4dd979326557b0dfa7c9a/det3d/datasets/nuscenes/nuscenes.py#L227 
https://github.com/tianweiy/CenterPoint/blob/e2fc27918a451f908bb4dd979326557b0dfa7c9a/det3d/datasets/nuscenes/nuscenes.py#L228 

These two methods contain all transformations from detection output to the required tracking input.

**Comment by iamsiddhantsahu** [comment]
@tianweiy Thanks a lot! But, what does this part of the code does?
```
for idx, output in enumerate(outputs):
            token = idx      #TODO we don't need tokens in ROS
            for k, v in output.items():
                if k not in [
                    "metadata",
                ]:
                    output[k] = v.to(cpu_device)
            detections.update(
                {idx: output,}
            )
```

**Comment by tianweiy** [comment]
move data from gpu to cpu

**Comment by iamsiddhantsahu** [comment]
@tianweiy What is the **units** of the [`time_lag`](https://github.com/tianweiy/CenterPoint/blob/e2fc27918a451f908bb4dd979326557b0dfa7c9a/tools/tracking/pub_test.py#L112) which is taken as input by the [`tracker.step_centertrack(preds, time_lag)`](https://github.com/tianweiy/CenterPoint/blob/e2fc27918a451f908bb4dd979326557b0dfa7c9a/tools/tracking/pub_test.py#L112) function?

**Comment by tianweiy** [comment]
second

**Comment by DeepakVellampalli** [comment]
@YoushaaMurhij , if you solved the   above can you    please provie the script so that   everybody can use... Kindly help

**Comment by YoushaaMurhij** [comment]
> @YoushaaMurhij , if you solved the above can you please provie the script so that everybody can use... Kindly help

I started working on that but, I didn't finish it. There was something not clear in the code.

**Comment by YoushaaMurhij** [comment]
@tianweiy , Do you know if it is possible to get the rotation and translation matrices between two successive sweeps ? Thanks

**Comment by tianweiy** [comment]
The calibration file should do the job?

**Comment by YoushaaMurhij** [comment]
I appreciate your super fast response and continuous help!
I found them in the ego_pose.json. Can I add them to the data-loader so I can use them with the detection results ?
Can you suggest me where to edit in the code or how?

**Comment by tianweiy** [comment]
check this link https://github.com/tianweiy/CenterPoint/blob/890e538afc95ee741f4c29b4c30b37251027e31c/det3d/datasets/nuscenes/nusc_common.py#L361

you can find how to compute [ref_from_car, car_from_global, global_from_car, car_from_current] in this file and then you can multiply them together to get the tranformation matrix. Maybe you want to precompute as you need to load the nuscenes devkit class if you want to add it into the dataloader.

**Comment by YoushaaMurhij** [comment]
@tianweiy , could you correct me please? I can use the matrix [ref_from_car](https://github.com/tianweiy/CenterPoint/blob/1ecebf980f75cfe7f53cc52032b184192891c9b9/det3d/datasets/nuscenes/nusc_common.py#L302) to get the transformation from car to a reference fixed point . so by using two successive values of this matrix I can get the transformation between two frames. Is that right?

**Comment by tianweiy** [comment]
you should use tm. ref_from_car means transform to lidar coordinates from car coordinates.

**Comment by joshphoo** [comment]
Hi @YoushaaMurhij @iamsiddhantsahu @tianweiy , is there any update on the tracking code in ROS? I have been trying to implement it myself using the steps told here https://github.com/tianweiy/CenterPoint/issues/35#issuecomment-683940665 but I have difficulty with obtaining the correct output function described here https://github.com/tianweiy/CenterPoint/issues/35#issuecomment-692908724 .

Kind regards,
Josh
