### ISSUE TITLE
min_points_in_gt

### ISSUE THREAD

**Issue by SakuraRiven** [tianweiy/CenterPoint#352]
https://github.com/tianweiy/CenterPoint/blob/master/det3d/datasets/pipelines/preprocess.py#L81

maybe ```min_points_in_gt``` in above line should change to ```self.min_points_in_gt```?

btw, does this variable affect the mAP on waymo?

**Comment by tianweiy** [comment]
1. yes

2. I never use this filtering in previous experiments so I am not sure
