### ISSUE TITLE
3D tracking on Waymo dataset

### ISSUE THREAD

**Issue by alanwanga** [tianweiy/CenterPoint#37]
Hi, thanks for the nice work.

I'm able to generate my_preds.bin by following the [instruction](https://github.com/tianweiy/CenterPoint/blob/master/docs/WAYMO.md). How about the tracking part? Is it possible to use the provided scripts? It'll be nice if you can also share some tracking results.

Best,

**Comment by tianweiy** [comment]
No, tracking requires a temporal model to predict the velocity. I don't have time for this in the near future. You can probably find a existing KF filter based tracker.

**Comment by alanwanga** [comment]
Thanks, seems feasible.
