### ISSUE TITLE
get "cudaGetLastError()->Error!" in iou3d_nms.cpp when I try to use "post_processing()" and "nms_gpu" in traning rather than evaluation

### ISSUE THREAD

**Issue by WangNeng0326** [tianweiy/CenterPoint#371]
Hi!, Mr.Yin, I get "cudaGetLastError()->Error!" in iou3d_nms.cpp when I try to use "post_processing()" and "nms_gpu" function in traning rather than evaluation .what it is means? Is there no way to use post_processing() during traning?

**Comment by WangNeng0326** [comment]
I means that I need 3d object detection result to next work in my network,so I must use NMS when training. But I find I can't use "post_processing()" function during training because "cudaGetLastError()" get Error! Is there something wrong with that or is there another way to us NMS when network training?

**Comment by YoushaaMurhij** [comment]
I am getting the same "Error!" msg from 
```
if ( cudaSuccess != cudaGetLastError() ) printf( "Error!\n" );
```
on aarch64 with cuda 11.4. The code works normally on x64 with cuda 10.2, 11.x and 12.1 and on aarch64 with cuda 10.2.
What could be the problem?
Could you please share the solution in case you manged to solve it?
Thanks
