### ISSUE TITLE
AMP automatic mixed precision training appears nan

### ISSUE THREAD

**Issue by SakuraRiven** [tianweiy/CenterPoint#385]
Does anyone successfully run the mixed precision training of CenterPoint? We use the ```autocast, GradScaler``` of ```torch.cuda.amp``` in multiple gpu training but  found that the values in centerhead often turn to __inf__, __nan__. However, the single gpu training successfully produces amp results.

Are there some more official ways to implement amp in this det3d framework?

Thanks : )

**Comment by SakuraRiven** [comment]
solved

**Comment by RaymondByc** [comment]
may i know how to solve this problem?
