### ISSUE TITLE
Semantic segmentation using CenterPoint

### ISSUE THREAD

**Issue by YoushaaMurhij** [tianweiy/CenterPoint#39]
[Question] Do you think it is possible to use CenterPoint for **semantic segmentation** in addition to detections and tracking? For example, by adding another head to your structure for this purpose and retrain the model if its necessary.

**Comment by tianweiy** [comment]
I thought about this in the past but semantic segmentation is not directly applicable here as we don't operate on the raw point cloud. 

Instance segmentation is possible but for 3d it is almost the same as getting the detection box and just output points inside the box so I haven't found datasets on this task for 3d yet. 

Like semantic segmentation, I don't know how to extend the voxel/pillar based model to panoptic segmentation for now. 

I suggest you take a look at those papers on the leaderboard of http://semantic-kitti.org/tasks.html

**Comment by YoushaaMurhij** [comment]
Thank you for your suggestion. I will check them!
