### ISSUE TITLE
How to visualize pred boxes on cam img of Nuscenes dataset?

### ISSUE THREAD

**Issue by Linkon87** [tianweiy/CenterPoint#395]
@tianweiy Thanks for the great work! I'm able to visualize pred boxes on BEV of Nuscenes dataset ,but how to realize it on cam img ? Is there an example ? Thank you in advance

**Comment by Byte247** [comment]
Did you find a solution? I would also be interested in this

**Comment by Linkon87** [comment]
> Did you find a solution? I would also be interested in this
Try https://github.com/nutonomy/nuscenes-devkit/issues/735
