### ISSUE TITLE
Question about pedestrian detection on waymo

### ISSUE THREAD

**Issue by s-ryosky** [tianweiy/CenterPoint#40]
Have you tried to train a model for pedestrian on waymo?

Though I'm trying to train a CenterPoint/PointPillars model for pedestrian on waymo, the model gets a poor result (about 20% AP).
Do you have any ideas to improve the result?

**Comment by tianweiy** [comment]
I haven't yet. 20 map sounds too low. Can you reproduce the car result?

**Comment by s-ryosky** [comment]
The car AP was about 60%.
It was lower than your result because I have changed the layer strides in rpn and total epochs.

**Comment by tianweiy** [comment]
well, then my only suggestion is to use the original network + number of epochs. Ped may be more sensitive to tthis.

**Comment by s-ryosky** [comment]
I have two questions.

1. What gpu do you use?
ds_layer_strides=[1, 2, 2] and us_layer_strides=[1, 2, 4] requires a lot of memory capacity.
Additionally, you set batch size=4.
So out of memory occurs in my gpu (1080ti).

2. How long did it take to train the model for 30 epochs.

**Comment by tianweiy** [comment]
1. We use V100. Yeah, I understand that it takes a lot of memory. I am not able to train Waymo models on Titan XP / V. If you use a larger stride, I guess you need to slightly decrease the voxel size. Otherwise, there will be some center collisions. 

2. On 4 V100, it takes about 2.5 days.

**Comment by s-ryosky** [comment]
Thank you for your reply.
I have reproduced the results.

**Comment by tianweiy** [comment]
Congrats!

**Comment by SakuraRiven** [comment]
@tianweiy 
Hi, the performances of Vehicle and Pedestrian in paper are trained using one model with two class or two separate model? I found 3% mAP drop of my reproduced results compared with the paper.

**Comment by tianweiy** [comment]
Hi, we trained a single model for veh / ped.

**Comment by SakuraRiven** [comment]
@tianweiy  Are there any other tricks that we should pay attention? There is always 3 mAP_L1 gap between our reproduced and paper, i.e., 73 vs 76 on vehicle : (

**Comment by tianweiy** [comment]
No tricks as far as I know. We use the same code as the one here. 

Actually, what result do you get for one stage model? Is it normal? 

Additionally, the result in paper is single frame

**Comment by SakuraRiven** [comment]
@tianweiy we train a model with two class. One stage model with 2-frame is 72.3 mAP, with 1-frame is only 70.9. Here is my config
```
import itertools
import logging
from det3d.utils.config_tool import get_downsample_factor

extra_tag = 'full-1_frame-nms07-input_5-2_cls-wo_velo'
DOUBLE_FLIP = False

tasks = [
    dict(num_class=2, class_names=['VEHICLE', 'PEDESTRIAN']),
]

class_names = list(itertools.chain(*[t["class_names"] for t in tasks]))

# training and testing settings
target_assigner = dict(
    tasks=tasks,
)

# model settings
model = dict(
    type="PointPillars",
    pretrained=None,
    reader=dict(
        type="PillarFeatureNet",
        num_filters=[64, 64],
        num_input_features=5,
        with_distance=False,
        voxel_size=(0.32, 0.32, 6.0),
        pc_range=(-74.88, -74.88, -2, 74.88, 74.88, 4.0),
    ),
    backbone=dict(type="PointPillarsScatter", ds_factor=1),
    neck=dict(
        type="RPN",
        layer_nums=[3, 5, 5],
        ds_layer_strides=[1, 2, 2],
        ds_num_filters=[64, 128, 256],
        us_layer_strides=[1, 2, 4],
        us_num_filters=[128, 128, 128],
        num_input_features=64,
        logger=logging.getLogger("RPN"),
    ),
    bbox_head=dict(
        type="CenterHead",
        in_channels=128*3,
        tasks=tasks,
        dataset='waymo',
        weight=2,
        code_weights=[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
        common_heads={'reg': (2, 2), 'height': (1, 2), 'dim':(3, 2), 'rot':(2, 2)}, # (output_channel, num_conv)
        share_conv_channel=64,
    ),
)

assigner = dict(
    target_assigner=target_assigner,
    out_size_factor=get_downsample_factor(model),
    dense_reg=1,
    gaussian_overlap=0.1,
    max_objs=500,
    min_radius=2,
)


train_cfg = dict(assigner=assigner)

test_cfg = dict(
    post_center_limit_range=[-80, -80, -10.0, 80, 80, 10.0],
    nms=dict(
        nms_pre_max_size=4096,
        nms_post_max_size=500,
        nms_iou_threshold=0.7,
    ),
    score_threshold=0.1,
    pc_range=[-74.88, -74.88],
    out_size_factor=get_downsample_factor(model),
    voxel_size=[0.32, 0.32],
    double_flip=DOUBLE_FLIP
)


# dataset settings
dataset_type = "WaymoDataset"
nsweeps = 1
data_root = 

db_sampler = dict(
    type="GT-AUG",
    enable=False,
    db_info_path=
    sample_groups=[
        dict(VEHICLE=15),
        dict(PEDESTRIAN=10),
        dict(CYCLIST=10),
    ],
    db_prep_steps=[
        dict(
            filter_by_min_num_points=dict(
                VEHICLE=5,
                PEDESTRIAN=5,
                CYCLIST=5,
            )
        ),
        dict(filter_by_difficulty=[-1],),
    ],
    global_random_rotation_range_per_object=[0, 0],
    rate=1.0,
) 

train_preprocessor = dict(
    mode="train",
    shuffle_points=True,
    global_rot_noise=[-0.78539816, 0.78539816],
    global_scale_noise=[0.95, 1.05],
    db_sampler=None,
    class_names=class_names,
)

val_preprocessor = dict(
    mode="val",
    shuffle_points=False,
)

voxel_generator = dict(
    range=[-74.88, -74.88, -2, 74.88, 74.88, 4.0],
    voxel_size=[0.32, 0.32, 6.0],
    max_points_in_voxel=20,
    max_voxel_num=[32000, 60000],
    double_flip=DOUBLE_FLIP
)

train_pipeline = [
    dict(type="LoadPointCloudFromFile", dataset=dataset_type),
    dict(type="LoadPointCloudAnnotations", with_bbox=True),
    dict(type="Preprocess", cfg=train_preprocessor),
    dict(type="Voxelization", cfg=voxel_generator),
    dict(type="AssignLabel", cfg=train_cfg["assigner"]),
    dict(type="Reformat"),
]
test_pipeline = [
    dict(type="LoadPointCloudFromFile", dataset=dataset_type),
    dict(type="LoadPointCloudAnnotations", with_bbox=True),
    dict(type="Preprocess", cfg=val_preprocessor),
    dict(type="DoubleFlip") if DOUBLE_FLIP else dict(type="Empty"),
    dict(type="Voxelization", cfg=voxel_generator),
    dict(type="AssignLabel", cfg=train_cfg["assigner"]),
    dict(type="Reformat", double_flip=DOUBLE_FLIP),
]

train_anno = 
val_anno = 
test_anno = None

data = dict(
    samples_per_gpu=4,
    workers_per_gpu=8,
    train=dict(
        type=dataset_type,
        root_path=data_root,
        info_path=train_anno,
        ann_file=train_anno,
        nsweeps=nsweeps,
        load_interval=1,
        class_names=class_names,
        pipeline=train_pipeline,
    ),
    val=dict(
        type=dataset_type,
        root_path=data_root,
        info_path=val_anno,
        test_mode=True,
        ann_file=val_anno,
        nsweeps=nsweeps,
        class_names=class_names,
        pipeline=test_pipeline,
    ),
    test=dict(
        type=dataset_type,
        root_path=data_root,
        info_path=test_anno,
        ann_file=test_anno,
        nsweeps=nsweeps,
        test_mode=True,
        class_names=class_names,
        pipeline=test_pipeline,
    ),
)



optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))

# optimizer
optimizer = dict(
    type="adam", amsgrad=0.0, wd=0.01, fixed_wd=True, moving_average=False,
)
lr_config = dict(
    type="one_cycle", lr_max=0.003, moms=[0.95, 0.85], div_factor=10.0, pct_start=0.4,
)

checkpoint_config = dict(interval=1)
# yapf:disable
log_config = dict(
    interval=5,
    hooks=[
        dict(type="TextLoggerHook"),
        # dict(type='TensorboardLoggerHook')
    ],
)
# yapf:enable
# runtime settings
total_epochs = 36
device_ids = range(8)
dist_params = dict(backend="nccl", init_method="env://")
log_level = "INFO"
work_dir = './work_dirs/{}/{}/'.format(__file__[__file__.rfind('/') + 1:-3], extra_tag)
load_from = None 
resume_from = None
workflow = [('train', 36), ('val', 1)]
```

**Comment by tianweiy** [comment]
that sounds weird and I don't have much clue at the moment (the config looks right). 

Have you tried the three class config  (single frame) https://github.com/tianweiy/CenterPoint/blob/master/configs/waymo/pp/waymo_centerpoint_pp_two_pfn_stride1_3x.py 
The main difference is that we use gt sampling once we also need to detect cyclist. 

This one already gets much higher performance in comparison to yours . Various other papers can also reproduce this results e.g. https://arxiv.org/abs/2110.06049

**Comment by SakuraRiven** [comment]
@tianweiy  Hi, we still have 3% gap... Would you mind sharing the training log with us? For instance, the single-frame two-cls point-pillar on waymo datasets

**Comment by tianweiy** [comment]
I only back up pretrained models and detection prediction when I left ut (for 3 class pp). You can send me an email if you need them. Unfortunately, I don't have the log anymore

**Comment by SakuraRiven** [comment]
@tianweiy  Hi, we found another validation gt.bin in [this](https://console.cloud.google.com/storage/browser/waymo_open_dataset_v_1_2_0/validation/ground_truth_objects?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false). With this bin, we could perfectly reproduce the mAP in your paper.

Is the above bin that used in your paper? 

We also confuse that why our own step-by-step generated bin following your doc has 3% gap ...

**Comment by tianweiy** [comment]
Oh interesting. I used the gt bin generated in this repo. I guess there were some code changes in the waymo devkit that may cause the problem? 

To be 100 percent sure, you can use the online server for evaluation which is what I did for paper numbers.
