### ISSUE TITLE
CenterTrack on waymo

### ISSUE THREAD

**Issue by s-ryosky** [tianweiy/CenterPoint#41]
Does it support nsweeps > 1 and CenterTrack on Waymo dataset?
https://github.com/tianweiy/CenterPoint/blob/e2fc27918a451f908bb4dd979326557b0dfa7c9a/configs/centerpoint/waymo_centerpoint_pp_car_large.py#L93

**Comment by tianweiy** [comment]
Not yet. I plan to do this in a few months.

**Comment by tianweiy** [comment]
You can follow the nuScenes code to generate the transform matrices to aggregate points and add a velocity target.

**Comment by DeepakVellampalli** [comment]
@tianweiy , CentreTrack replication on PointCloud on wamo/Nuscenes/Argoverse is too good
