### ISSUE TITLE
Why accumulating sweeps from key frame instead of the non-key frames?

### ISSUE THREAD

**Issue by eriche2016** [tianweiy/CenterPoint#44]
Hi, very nice work. 
I am confused about the data preparation code.   
According to my understanding, the **samples/LIDAR_TOP** contains the annotated key-frame, while **sweeps/LIDAR_TOP** contains non-key frames which are un-annotated. Acoording to CBGS paper, they accumulates non-key-frames to the key-frame to form the dense point cloud. However, in your code (actually also in the [OpenPCDet](https://github.com/open-mmlab/OpenPCDet/blob/master/pcdet/datasets/nuscenes/nuscenes_utils.py#L329) repository), they accumulate the key-frames to the key frame([your code is here](https://github.com/tianweiy/CenterPoint/blob/master/det3d/datasets/nuscenes/nusc_common.py#L467)).  Is there any explanations for doing so? Thanks!

**Comment by tianweiy** [comment]
Hi, I think this is a misunderstanding. We are accumulating non-key frames. Why do think it is the opposite?

**Comment by eriche2016** [comment]
Hi, thanks for your quick reply. 
I have generated the file and show the data path for the sweeps, here is the snapshot, 
![image](https://user-images.githubusercontent.com/11784910/95537143-849bd080-0a1f-11eb-991e-7bdba43118d9.png)

**Comment by tianweiy** [comment]
@eriche2016  hi, this is only true for the first few frames which doesn't have ten previous frames in which case we repeat the reference frame. For other frames, you can see that we accumulate non-key frame data (from sweeps folder) 
for example, try train_info[10]

**Comment by eriche2016** [comment]
Thanks, bro., you are correct！

**Comment by tianweiy** [comment]
Np, happy to help
