### ISSUE TITLE
logic behind code_weights=[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.2, 0.2, 1.0, 1.0]

### ISSUE THREAD

**Issue by chowkamlee81** [tianweiy/CenterPoint#45]
@tianweiy 

Would like to know logic behind the line 
https://github.com/tianweiy/CenterPoint/blob/master/configs/centerpoint/nusc_centerpoint_pp_02voxel_circle_nms.py#L60

Also sample_groups below:

https://github.com/tianweiy/CenterPoint/blob/master/configs/centerpoint/nusc_centerpoint_pp_02voxel_circle_nms.py#L104

Kindly help

**Comment by tianweiy** [comment]
code_weights: velocity loss is a little large at the beginning so I choose 0.2 to stabilize the training.

sample_group: I copied from https://github.com/poodarchu/det3d I never tune this

**Comment by chowkamlee81** [comment]
Thanks @tianweiy closing the issue
