### ISSUE TITLE
Help to install dcn

### ISSUE THREAD

**Issue by anuj-sharma-19** [tianweiy/CenterPoint#46]
Hi,

Thanks for your clarifications earlier on the code. I am now trying to use the deformable convolution kernels with the VoxelNet version. But am having issues in installing it and importing it further. I installed it by:

`cd CenterPoint/det3d/ops/dcn`
`python setup.py bdist_wheel`
`pip install dist/*.whl`

It says its installing, but when trying to import e.g. `from det3d.ops.dcn import DeformConv, ModulatedDeformConvPack`, it fails with following error:

`ImportError: cannot import name 'deform_conv_cuda'`

I am not sure what I am missing here. Could you please share the setup steps for this?

Thanks !!
Anuj

**Comment by tianweiy** [comment]
Can you try

python setup.py build_ext --inplace

I haven't tried your way yet.

**Comment by anuj-sharma-19** [comment]
Wow, amazing, that works. Thank you very much for the quick response !! :+1: 

I will close this issue in a while once everything is good :grinning: 

Thanks again !!

**Comment by tianweiy** [comment]
close for now due to inactivity

**Comment by YoushaaMurhij** [comment]
Do you remember how much GPU-memory to I need to train **_voxelnet_0075voxel_dcn_flip_** ?

**Comment by tianweiy** [comment]
yeah, you need to change the batch_size if using 2 GPU. I suggest you just compare with our 0.1 voxel size model (additionally with flipping). This model is faster, consumes less memory, and only marginally lower (64.9 vs. 65.5) than 0075_dcn

**Comment by tianweiy** [comment]
https://github.com/tianweiy/CenterPoint/blob/890e538afc95ee741f4c29b4c30b37251027e31c/configs/nusc/voxelnet/nusc_centerpoint_voxelnet_01voxel.py#L165 

For 0.1 voxel size model, you can double this batch size and it should fit in a V100. For 0.075, you can use as large a batch size as it can fit into your gpu.

**Comment by ZhangYu1ing** [comment]
> Can you try
> 
> python setup.py build_ext --inplace
> 
> I haven't tried your way yet.

Hi,
I met the same ImportError for 'cannot import name 'deform_conv_cuda''. However, I tried to follow the provided method to solve the problem. After running 'python setup.py build_ext --inplace', it returns the 'error: command 'x86_64-linux-gnu-gcc' failed with exit status 1'.  Do you have any ideas for what causing this error?

Thanks!

**Comment by tianweiy** [comment]
@ZhangYu1ing  is the problem solved?

**Comment by ZhangYu1ing** [comment]
> @ZhangYu1ing is the problem solved?

Yes, I noticed that my torch version is 1.7.1, which could not be used to define AT_CHECK. After replacing all the AT_CHECK to TORCH_CHECK in both deform_conv_cuda.cpp and deform_pool_cuda.cpp files, then the setup.py could successfully build and create the deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so file. Finally, the ImportError for 'cannot import name 'deform_conv_cuda'' does not exist anymore~

**Comment by tianweiy** [comment]
sounds good. I just finished ICCV submission and I am now working on a refactoring of the codebase. Hopefully, I can make the codebase easier to tune and tweak in one to two weeks.

**Comment by ZhangYu1ing** [comment]
Awesome! We are looking forward to the update~

**Comment by ktro2828** [comment]
```
running build_ext
building 'deform_conv_cuda' extension
Emitting ninja build file /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.8/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] c++ -MMD -MF /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.8/src/deform_conv_cuda.o.d -pthread -B /home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include -I/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/TH -I/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/include/python3.8 -c -c /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp -o /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.8/src/deform_conv_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.8/src/deform_conv_cuda.o 
c++ -MMD -MF /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.8/src/deform_conv_cuda.o.d -pthread -B /home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include -I/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/TH -I/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/include/python3.8 -c -c /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp -o /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.8/src/deform_conv_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/ATen/Parallel.h:149:0,
                 from /home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:12,
                 from /home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:4:
/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/ATen/ParallelOpenMP.h:84:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for if ((end - begin) >= grain_size)
 
/home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp: In function ‘void shape_check(at::Tensor, at::Tensor, at::Tensor*, at::Tensor, int, int, int, int, int, int, int, int, int, int)’:
/home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:66:3: error: ‘AT_CHECK’ was not declared in this scope
   AT_CHECK(weight.ndimension() == 4,
   ^~~~~~~~
/home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:66:3: note: suggested alternative: ‘DCHECK’
   AT_CHECK(weight.ndimension() == 4,
   ^~~~~~~~
   DCHECK
/home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp: In function ‘int deform_conv_forward_cuda(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, int)’:
/home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:194:3: error: ‘AT_CHECK’ was not declared in this scope
   AT_CHECK((offset.size(0) == batchSize), "invalid batch size of offset");
   ^~~~~~~~
/home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:194:3: note: suggested alternative: ‘DCHECK’
   AT_CHECK((offset.size(0) == batchSize), "invalid batch size of offset");
   ^~~~~~~~
   DCHECK
/home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp: In function ‘int deform_conv_backward_input_cuda(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, int)’:
/home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:301:3: error: ‘AT_CHECK’ was not declared in this scope
   AT_CHECK((offset.size(0) == batchSize), 3, "invalid batch size of offset");
   ^~~~~~~~
/home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:301:3: note: suggested alternative: ‘DCHECK’
   AT_CHECK((offset.size(0) == batchSize), 3, "invalid batch size of offset");
   ^~~~~~~~
   DCHECK
/home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp: In function ‘int deform_conv_backward_parameters_cuda(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, float, int)’:
/home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:417:3: error: ‘AT_CHECK’ was not declared in this scope
   AT_CHECK((offset.size(0) == batchSize), "invalid batch size of offset");
   ^~~~~~~~
/home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:417:3: note: suggested alternative: ‘DCHECK’
   AT_CHECK((offset.size(0) == batchSize), "invalid batch size of offset");
   ^~~~~~~~
   DCHECK
/home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp: In function ‘void modulated_deform_conv_cuda_forward(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, bool)’:
/home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:497:3: error: ‘AT_CHECK’ was not declared in this scope
   AT_CHECK(input.is_contiguous(), "input tensor has to be contiguous");
   ^~~~~~~~
/home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:497:3: note: suggested alternative: ‘DCHECK’
   AT_CHECK(input.is_contiguous(), "input tensor has to be contiguous");
   ^~~~~~~~
   DCHECK
/home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp: In function ‘void modulated_deform_conv_cuda_backward(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, bool)’:
/home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:579:3: error: ‘AT_CHECK’ was not declared in this scope
   AT_CHECK(input.is_contiguous(), "input tensor has to be contiguous");
   ^~~~~~~~
/home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:579:3: note: suggested alternative: ‘DCHECK’
   AT_CHECK(input.is_contiguous(), "input tensor has to be contiguous");
   ^~~~~~~~
   DCHECK
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1533, in _run_ninja_build
    subprocess.run(
  File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    setup(
  File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 491, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1250, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

```

hi, I got this error when I run `bash ./setup.sh`
can anyone help?

**Comment by ZhangYu1ing** [comment]
> ```
> running build_ext
> building 'deform_conv_cuda' extension
> Emitting ninja build file /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.8/build.ninja...
> Compiling objects...
> Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
> [1/1] c++ -MMD -MF /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.8/src/deform_conv_cuda.o.d -pthread -B /home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include -I/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/TH -I/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/include/python3.8 -c -c /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp -o /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.8/src/deform_conv_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
> FAILED: /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.8/src/deform_conv_cuda.o 
> c++ -MMD -MF /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.8/src/deform_conv_cuda.o.d -pthread -B /home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include -I/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/TH -I/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/include/python3.8 -c -c /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp -o /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.8/src/deform_conv_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
> cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
> In file included from /home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/ATen/Parallel.h:149:0,
>                  from /home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
>                  from /home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
>                  from /home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
>                  from /home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:12,
>                  from /home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
>                  from /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:4:
> /home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/include/ATen/ParallelOpenMP.h:84:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
>  #pragma omp parallel for if ((end - begin) >= grain_size)
>  
> /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp: In function ‘void shape_check(at::Tensor, at::Tensor, at::Tensor*, at::Tensor, int, int, int, int, int, int, int, int, int, int)’:
> /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:66:3: error: ‘AT_CHECK’ was not declared in this scope
>    AT_CHECK(weight.ndimension() == 4,
>    ^~~~~~~~
> /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:66:3: note: suggested alternative: ‘DCHECK’
>    AT_CHECK(weight.ndimension() == 4,
>    ^~~~~~~~
>    DCHECK
> /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp: In function ‘int deform_conv_forward_cuda(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, int)’:
> /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:194:3: error: ‘AT_CHECK’ was not declared in this scope
>    AT_CHECK((offset.size(0) == batchSize), "invalid batch size of offset");
>    ^~~~~~~~
> /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:194:3: note: suggested alternative: ‘DCHECK’
>    AT_CHECK((offset.size(0) == batchSize), "invalid batch size of offset");
>    ^~~~~~~~
>    DCHECK
> /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp: In function ‘int deform_conv_backward_input_cuda(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, int)’:
> /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:301:3: error: ‘AT_CHECK’ was not declared in this scope
>    AT_CHECK((offset.size(0) == batchSize), 3, "invalid batch size of offset");
>    ^~~~~~~~
> /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:301:3: note: suggested alternative: ‘DCHECK’
>    AT_CHECK((offset.size(0) == batchSize), 3, "invalid batch size of offset");
>    ^~~~~~~~
>    DCHECK
> /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp: In function ‘int deform_conv_backward_parameters_cuda(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, float, int)’:
> /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:417:3: error: ‘AT_CHECK’ was not declared in this scope
>    AT_CHECK((offset.size(0) == batchSize), "invalid batch size of offset");
>    ^~~~~~~~
> /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:417:3: note: suggested alternative: ‘DCHECK’
>    AT_CHECK((offset.size(0) == batchSize), "invalid batch size of offset");
>    ^~~~~~~~
>    DCHECK
> /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp: In function ‘void modulated_deform_conv_cuda_forward(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, bool)’:
> /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:497:3: error: ‘AT_CHECK’ was not declared in this scope
>    AT_CHECK(input.is_contiguous(), "input tensor has to be contiguous");
>    ^~~~~~~~
> /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:497:3: note: suggested alternative: ‘DCHECK’
>    AT_CHECK(input.is_contiguous(), "input tensor has to be contiguous");
>    ^~~~~~~~
>    DCHECK
> /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp: In function ‘void modulated_deform_conv_cuda_backward(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, bool)’:
> /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:579:3: error: ‘AT_CHECK’ was not declared in this scope
>    AT_CHECK(input.is_contiguous(), "input tensor has to be contiguous");
>    ^~~~~~~~
> /home/leus/autoware/detection_3D/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:579:3: note: suggested alternative: ‘DCHECK’
>    AT_CHECK(input.is_contiguous(), "input tensor has to be contiguous");
>    ^~~~~~~~
>    DCHECK
> ninja: build stopped: subcommand failed.
> Traceback (most recent call last):
>   File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1533, in _run_ninja_build
>     subprocess.run(
>   File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/subprocess.py", line 516, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "setup.py", line 4, in <module>
>     setup(
>   File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
>     return distutils.core.setup(**attrs)
>   File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/distutils/dist.py", line 966, in run_commands
>     self.run_command(cmd)
>   File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
>     _build_ext.run(self)
>   File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
>     _build_ext.build_ext.run(self)
>   File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/distutils/command/build_ext.py", line 340, in run
>     self.build_extensions()
>   File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
>     build_ext.build_extensions(self)
>   File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
>     _build_ext.build_ext.build_extensions(self)
>   File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
>     self._build_extensions_serial()
>   File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
>     self.build_extension(ext)
>   File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
>     _build_ext.build_extension(self, ext)
>   File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
>     objects = self.compiler.compile(sources,
>   File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 491, in unix_wrap_ninja_compile
>     _write_ninja_file_and_compile_objects(
>   File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1250, in _write_ninja_file_and_compile_objects
>     _run_ninja_build(
>   File "/home/leus/.pyenv/versions/anaconda3-5.1.0/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1555, in _run_ninja_build
>     raise RuntimeError(message) from e
> RuntimeError: Error compiling objects for extension
> ```
> 
> hi, I got this error when I run `bash ./setup.sh`
> can anyone help?

maybe you have the latest version of torch. Please try to replace all the "AT_CHECK" to "TORCH _CHECK " in both deform_conv_cuda.cpp and deform_pool_cuda.cpp files

**Comment by ktro2828** [comment]
@ZhangYu1ing Thanks for your replying!! also I need to replace `TORCH_ERROR` to `TORCH_WARN` and fix it!!
