### ISSUE TITLE
Detection of a specific point on PR curve

### ISSUE THREAD

**Issue by alanwanga** [tianweiy/CenterPoint#47]
Hey, thanks for your nice work.

After inference on NuScenes, we can get the detection and summary below.
<img width="613" alt=" " src="https://user-images.githubusercontent.com/3997703/96366879-11136500-117d-11eb-8614-7c640783257c.png">

The PR curve are from the points of different threshold. What is the point of threshold for the generated detection? And how to determine or set the threshold value for the detection? I've tried 
to change score_threshold in the [configs](https://github.com/tianweiy/CenterPoint/blob/master/configs/centerpoint/nusc_centerpoint_voxelnet_dcn_0075voxel_flip.py#L90) but the whole curve changed instead.

Since the FP is too high for our application, I'd like to modify the policy to make the precision higher. Please correct me if there's a better approach.

Besides, I found the detection seems to become better after tracking. What can I do if I also want to plot the PR curve for the tracking result?

Best,

**Comment by tianweiy** [comment]
Thanks for the interest. This is a good question. I will do some research and get back to you tomorrow.

**Comment by tianweiy** [comment]
The PR curve are from the points of different threshold. What is the point of threshold for the generated detection? And how to determine or set the threshold value for the detection? <- I am not quire sure for this. I guess you need to try a few values and do some binary search. 

> I've tried
to change score_threshold in the configs but the whole curve changed instead

I think you should not change the threshold value as it is used before the NMS. So changing this value will affect the whole curve. If you want to tune this, it should be after the NMS at some places like [here](https://github.com/tianweiy/CenterPoint/blob/e2fc27918a451f908bb4dd979326557b0dfa7c9a/det3d/models/bbox_heads/mg_head.py#L1770). I guess you can also tune the number of objects. To be more efficient, I suggest you to first generate the prediction json file and then operate on the boxes inside the prediction. 

Besides, I found the detection seems to become better after tracking. What can I do if I also want to plot the PR curve for the tracking result?

I don't remember I get any special handling for detection during the tracking. I will look into this. I guess some KF Filtering based tracking method should be able to improve the detection a little bit like [URL](https://arxiv.org/abs/1907.03961)

**Comment by alanwanga** [comment]
> I guess you can also tune the number of objects. To be more efficient, I suggest you to first generate the prediction json file and then operate on the boxes inside the prediction.

Thanks for your reply. Can you also share or suggest some tricks to post-process the generated predictions?

**Comment by tianweiy** [comment]
not really sure. Probably just decrease the IoU threshold to 0.02 in the nms? I guess you will get slightly fewer boxes.

**Comment by muzi2045** [comment]
the score threshold should be in the metrics_details.json when you using Nuscenes evaluation code
with different distance threshold and class, there should be there items value to plot P-R Curve.
1. Recall 2. precision 3. confidence.
@alanwanga

**Comment by tianweiy** [comment]
close due to inactivity
