### ISSUE TITLE
sorry, but i cannot understand how the model is built

### ISSUE THREAD

**Issue by hughlee815** [tianweiy/CenterPoint#50]
I've been studying this for a long time, but i really cannot understand how Det3D build a model.
i am sure that the model is built by class 'Register', but when i look into the class 'Register', i cannot find any line of code which has contributions to build a Model.
could you please give any help to clarify the problem?
thanks so much and always waiting for your reply

**Comment by chowkamlee81** [comment]
Analyze how datasets like Nuscenes/Waymo has been added to the registry. Accordingly you can add codes to create own datasets

**Comment by tianweiy** [comment]
Check out this initializer https://github.com/tianweiy/CenterPoint/blob/e2fc27918a451f908bb4dd979326557b0dfa7c9a/det3d/models/detectors/single_stage.py#L21 

The registry only registers classes and then there is a builder that can build a model from those classes
