### ISSUE TITLE
Waymo  model acuracy leser in SOTA

### ISSUE THREAD

**Issue by chowkamlee81** [tianweiy/CenterPoint#51]
@tianweiy 

Did you got any chance to improve waymo models using centrepoint pointpillar since i found GT-AUG is misssing in your config file?
https://github.com/tianweiy/CenterPoint/blob/master/configs/centerpoint/waymo_centerpoint_pp_car_large.py#L114

Kindly suggest

**Comment by tianweiy** [comment]
GT Aug doesn't matter much. We are working on a revision with new techniques and we get really good number now. However, it will probably take me months to finish all revision, update the paper, clean up and merge the code.

**Comment by chowkamlee81** [comment]
Thanks for your reply and awaiting

**Comment by tianweiy** [comment]
stay tuned, it will be out in a few weeks depending on my other coursework XD

**Comment by chowkamlee81** [comment]
Thanks tianwei. Awaiting
