### ISSUE TITLE
Waymo point cloud decoding bug

### ISSUE THREAD

**Issue by eerensener** [tianweiy/CenterPoint#52]
After decoding two segments from Waymo dataset, I visualized the point clouds. And I think there is a decoding error in the code. At screenshots below, you can see that the return of the side lidars (+ part of the top lidar) and the return of the top lidar are not int the same level. 
Is there anyone experiencing the same issue? 

![ss_waymo_open3d_2](https://user-images.githubusercontent.com/37368032/98508391-789a6d00-2270-11eb-966a-b56568253a55.png)
![ss_waymo_open3d_1](https://user-images.githubusercontent.com/37368032/98508396-79cb9a00-2270-11eb-910b-6d6979664bc1.png)

segment-1022527355599519580_4866_960_4886_960_with_camera_labels
segment-10231929575853664160_1160_000_1180_000_with_camera_labels

**Comment by tianweiy** [comment]
can you explain a bit what this means "the return of the side lidars (+ part of the top lidar) and the return of the top lidar are not int the same level"

**Comment by eerensener** [comment]
Thank you for fast reply :D
The light blue points in the ss are the returns coming from side lidars. (It seems so)
The yellow and orange points in the ss are the returns from top lidars. 
These points sits above the dark blue points in terms of z-axis.

**Comment by tianweiy** [comment]
Hi, I don't think there are problems with this. Firstly they are mounted at different locations. Secondly, there is a field of view in z axis for both lidar. Are you claiming that they are not in the same coordinate or so in the decoded lidar?

**Comment by eerensener** [comment]
I know they are mounted in different locations. However, ground plane returns from all lidars have to be in the same level in order to have consistency in the lidar returns to train a model? 

I just put two tfrecords into a folder. Then run your Waymo converter code. I just visualized pcds from the decoded Waymo segments. I saw this issue. In order to be sure that there is a problem, I get the preprocessed lidar data from "det3d/datasets/pipelines/preprocess.py at line 280" in debug mode while training a dummy model with these two segments.

**Comment by tianweiy** [comment]
I see, so the issue is that side lidar produces higher ground plane than top lidar? Thanks for the issue, I will take a look tomorrow

**Comment by tianweiy** [comment]
I am recently working on a submission and it will probably take me one week to find time for this. For the performance side, I can already get really good numbers on Waymo. Good if this bug fix(if it is) can bring some more improvements.

**Comment by tianweiy** [comment]
@eerensener Can you attach your pkl file for the converted results. I take a quick pass and mine doesn't seem to have the issue, 
I use the following code to visualize the frames I attach below. 

```
import os
import numpy as np
import open3d as o3d

import pickle 

def get_obj(path):
    with open(path, 'rb') as f:
            obj = pickle.load(f)
    return obj 

def main():
    # draw

    fnames = list(os.listdir('visual'))
    for fname in fnames: 
        obj = get_obj("visual/"+fname)

        point_cloud = obj['lidars']["points_xyz"]

        pcd = o3d.geometry.PointCloud()
        pcd.points = o3d.utility.Vector3dVector(point_cloud[:, :3])

        visual = [pcd]

        o3d.visualization.draw_geometries(visual)


if __name__ == '__main__':
    main()

```

[visual.zip](https://github.com/tianweiy/CenterPoint/files/5551556/visual.zip)

**Comment by eerensener** [comment]
I use the very same code that you use to visualize. Can you convert following tfrecord and visualize it? I attached some pkls from this segment. 
"Training/training_0000/segment-1022527355599519580_4866_960_4886_960
_with_camera_labels.tfrecord" 

[visual.zip](https://github.com/tianweiy/CenterPoint/files/5551688/visual.zip)

**Comment by tianweiy** [comment]
Hi, can you check your waymo devkit version? I found that your generated lidar points are really different from mine. For example, please see the attached pkl file for the frame 48.


[seq_0_frame_48.zip](https://github.com/tianweiy/CenterPoint/files/5551838/seq_0_frame_48.zip)

**Comment by eerensener** [comment]
My devkit version: waymo-open-dataset-tf-1-15-0==1.2.0
I double checked everything but it still produces the same result. I will update the conversion codes for my needs. (I had some conversion codes for the first version of Waymo data. I will fine-tune them.) 
You can close the issue if you don't have additional thoughts. Thank you for your help. :)

**Comment by tianweiy** [comment]
ok, it seems quite weird then. good luck with your project. My conversion code is taken from https://github.com/WangYueFt/pillar-od which only uses function in the official devkit so I am not quite sure the difference. 

I will actually support a really good waymo model (not just sota, should be near the top of the leaderboard) in a few weeks.

**Comment by vikyzeng** [comment]
> After decoding two segments from Waymo dataset, I visualized the point clouds. And I think there is a decoding error in the code. At screenshots below, you can see that the return of the side lidars (+ part of the top lidar) and the return of the top lidar are not int the same level.
> Is there anyone experiencing the same issue?
> 
> ![ss_waymo_open3d_2](https://user-images.githubusercontent.com/37368032/98508391-789a6d00-2270-11eb-966a-b56568253a55.png)
> ![ss_waymo_open3d_1](https://user-images.githubusercontent.com/37368032/98508396-79cb9a00-2270-11eb-910b-6d6979664bc1.png)
> 
> segment-1022527355599519580_4866_960_4886_960_with_camera_labels
> segment-10231929575853664160_1160_000_1180_000_with_camera_labels

I met the same problem with you . Have you solved that？

**Comment by eerensener** [comment]
I didn't use the repository decoding codes. I had some conversion codes (based on this [repo](https://github.com/gdlg/simple-waymo-open-dataset-reader)) for the first version of Waymo data. I just fine-tuned them and created pickle files.

**Comment by tianweiy** [comment]
Thanks for the report. I will check again tomorrow.

**Comment by tianweiy** [comment]
@vikyzeng  Unfortunately I still can't reproduce this error. Could you send me a link of your raw data (a tfrecord segment)?  A google drive / dropbox / Baidu link is fine.  I want to check if there are any problems with them. 

My decoded result of segment segment-1022527355599519580_4866_960_4886_960_with_camera_labels.tfrecord is available [here](https://drive.google.com/file/d/1Tt9z49nOdCnjDY7tjX5ef0aOSSY7aimT/view?usp=sharing)

Or probably just let me know what is the size of this segment by
 ```
stat segment-1022527355599519580_4866_960_4886_960_with_camera_labels.tfrecord 
```

Mine is 930269746.

**Comment by tianweiy** [comment]
@eerensener  Are yours v1.2 data? Not sure if this makes much difference. Probably you can try one segment here https://console.cloud.google.com/storage/browser/_details/waymo_open_dataset_v_1_2_0_individual_files/training/segment-1005081002024129653_5313_150_5333_150_with_camera_labels.tfrecord ?

**Comment by eerensener** [comment]
Mine was v1.1 data

**Comment by tianweiy** [comment]
Thanks. I guess this may be the difference then.

**Comment by tianweiy** [comment]
I tried v1.0 / v1.1 / v1.2, still can't reproduce the error. Let me know if you provide some script / colab / jupyter-notebook that can reproduce the error with a segment file

**Comment by tianweiy** [comment]
close due to inactivity
