### ISSUE TITLE
Tracking inference code

### ISSUE THREAD

**Issue by shreyas1998** [tianweiy/CenterPoint#53]
Hi, Thank you for the code. The documentation is excellent and I have been able to reproduce most of the results. I have an issue with the tracking code (pub_test.py)
![image](https://user-images.githubusercontent.com/34686465/99518356-75ad2400-29b6-11eb-925e-0d610e08e13d.png)

I'm using the 'centerpoint_pp_512_circle_nms_tracking' from model zoo.
I understand that this folder contains infos_val_10sweeps_withvelo_filter_True.json file that has the precalculated output of CenterPoint network (velocity predictions etc), using which you perform tracking.

If I want to perform end-to-end tracking, i.e I want to generate the infos_val_10sweeps_withvelo_filter_True.json file , how do I do it?

(Correct me if I'm wrong, the infos_val_10sweeps_withvelo_filter_True.json file is not the same as infos_val_10sweeps_withvelo_filter_True.pkl in detection case, where it refers to annotations for validation set)

**Comment by tianweiy** [comment]
```
If I want to perform end-to-end tracking, i.e I want to generate the infos_val_10sweeps_withvelo_filter_True.json file , how do I do it?
```
It is from nuScenes 3D detection part of this [page](https://github.com/tianweiy/CenterPoint/blob/master/docs/MODEL_ZOO.md). You can generate them using [dist_test.py](tools/dist_test.py) with the corresponding config file. 

 ```
(Correct me if I'm wrong, the infos_val_10sweeps_withvelo_filter_True.json file is not the same as infos_val_10sweeps_withvelo_filter_True.pkl in detection case, where it refers to annotations for validation set)
```
Yeah, one is "json" for detection and one is "pkl" for annotations

**Comment by shreyas1998** [comment]
Thanks for the quick response @tianweiy  :)  . I got it :)
