### ISSUE TITLE
use kitti

### ISSUE THREAD

**Issue by Robert-Hopkins** [tianweiy/CenterPoint#55]
how to use centerpoint in kitti? thank you

**Comment by tianweiy** [comment]
I haven't tried CenterPoint KITTI in this codebase. Using (PCDet)[https://github.com/open-mmlab/OpenPCDet], I can get some improvements when combined CenterPoint with PVRCNN.

Currently, I am focusing on more performance improvements on Waymo and nuScenes. So you may need to refer to other codebases for the KITTI dataset.

**Comment by Robert-Hopkins** [comment]
I want to use centerpoint to detect kitti point cloud.Can I do this with the  model trained on Nuscenes？Or do I need to train centerpoint on kitti first? thank you

**Comment by tianweiy** [comment]
you need to train a kitti model. The inter dataset transfer is pretty bad yet for 3d detection methods.

**Comment by yustaub** [comment]
Hi, sir. Can you use centerpoint on kitti? @Robert-Hopkins

**Comment by tianweiy** [comment]
close due to inactivity. You can use Waymo model on Waymo but I haven't test the performance.
