### ISSUE TITLE
multi-gpus training error

### ISSUE THREAD

**Issue by z393** [tianweiy/CenterPoint#59]
When i run 'python -m torch.distributed.launch --nproc_per_node=4 ./tools/train.py configs/cbgs/nusc_cbgs_01voxel.py',  I met the error like this:
  File "./tools/train.py", line 133, in <module>
    main()
  File "./tools/train.py", line 128, in main
    logger=logger,
  File "/media/hy/DATA3/z393/CenterPoint-master/det3d/torchie/apis/train.py", line 344, in train_detector
    find_unused_parameters=True,
TypeError: __init__() got an unexpected keyword argument 'find_unused_parameters'

and when I run 'python tools/train.py configs/cbgs/nusc_cbgs_01voxel.py',the error is ：
pure virtual method called
terminate called without an active exception
Aborted (core dumped)

My environment is cuda9.0 torch1.0.0

**Comment by tianweiy** [comment]
Please update to torch >=1.1. 1.0 is not supported
