### ISSUE TITLE
SpMiddleResNetFHD is not in the backbone registry 

### ISSUE THREAD

**Issue by huster-wugj** [tianweiy/CenterPoint#62]
i got an error when i use voxelnet:
    "{} is not in the {} registry".format(obj_type, registry.name)
KeyError: 'SpMiddleResNetFHD is not in the backbone registry'

**Comment by tianweiy** [comment]
I guess you didn't install spconv successfully.

Is there a line like "import spconv fail" when you run the program?

**Comment by tianweiy** [comment]
close due to inactivity
