### ISSUE TITLE
Domain adaptation from Nuscenes model

### ISSUE THREAD

**Issue by pratikkayal** [tianweiy/CenterPoint#64]
Really phenomenal work with the codebase. 

Please see if you can answer this question: What changes do I need to make to inference the Nuscenes model on the Waymo dataset?

**Comment by tianweiy** [comment]
Hi,  

Basically, the nuScenes data format is a little diffrent. 
1> it gets an extra timestamp be default 
2> it gets a slightly different reflectance value (between 0-255 while Waymo is between 0 -1 after tanh transform)

For 1, I guess you can set it to zero. For 2, I guess you can multiple Waymo reflectance value by 255. You only need to change https://github.com/tianweiy/CenterPoint/blob/master/det3d/datasets/pipelines/loading.py

**Comment by pratikkayal** [comment]
Hi Tianwei,
Great! Can you tell similar changes that I can make to infer waymo model on the nuscenes test dataset?

**Comment by tianweiy** [comment]
1> divide the nuscenes reflectance value by 255
2> Waymo model gets an extra elongation value input in the fifth channel. I am not sure if you can set this to zero. You need to see the data range first I guess

**Comment by pratikai** [comment]
Thank you for the insights :)

**Comment by pratikkayal** [comment]
Thank you for the insights :)

**Comment by pratikkayal** [comment]
Hi Tianwei,

I tested the nusc_centerpoint_voxelnet_0075voxel_dcn on Waymo, but I was getting 0.075 mAP compared to 0.724 mAP for Native Waymo model. 

I tested both 2 sweep Waymo dataset and 10 sweep one.
I also made the following changes in the files:
In loading.py:
def read_single_waymo(obj):
    points_feature = (np.tanh(points_feature[:, 0])*255.)[..., np.newaxis] #Removed the last axis (Before it was points_feature[:, 0=) and multiplied by 255
Did the same for read_single_waymo_sweep

In waymo_common: changed LABEL_TO_TYPE = {0: 1, 1:1, 2:1, 3:1, 4:1, 5:0, 6:1, 7:4, 8:2, 9:0} to map 
    'Pedestrian' to Pedestrian
    'Bicycle' to Cyclist
    'Bus', to Vehicle
    'Car' to Vehicle
    'Trailer' to Vehicle
    'Truck to Vehicle
    'Motorcycle' to Vehicle

Do you have any suggestions for me? According to this paper https://arxiv.org/abs/2005.08139 , the domain gap should be around 15% to 20%.

**Comment by tianweiy** [comment]
I will try this when I get time (probably may take a few days).

**Comment by pratikkayal** [comment]
Sure, thanks

**Comment by pratikkayal** [comment]
Hi Tianwei,

Did you get a chance to look at this?

**Comment by tianweiy** [comment]
sorry, too many meetings and deadlines recently. I will look at it tonight.

**Comment by tianweiy** [comment]
I played with this just now and I also get about 10 mAP by transferring from nuScenes to Waymo. I am not sure what is the problem here. I guess you can check the Bev mAP? It should be much higher according to the paper https://arxiv.org/abs/2005.08139 

Another part is that nuScenes doesn't use the IoU for mAP calculation. Instead, they use center-distance based mAP, which is quite loose so even if it is 84 mAP on nuScenes, it is about 40~50 mAP using KITTI style metric (iou 70), so the gap is not that large 

For the paper you referenced, they only do object detection in front view so it may be easier. Though they didn't opensource code so I am not sure what exactly they do for the results ... 

I guess you can try evaluate Waymo model on nuScenes using KITTI metrics and class definition.

**Comment by pratikkayal** [comment]
Yeah, this confirms my experience. 

Actually, if you reduce the threshold for Waymo detection from 0.7IOU to 0.3IOU you get mAP of 48.45. 

Closing this now.

**Comment by pratikai** [comment]
Hi Tianwei,

I was trying to adapt the models to the KITTI dataset too.

I have successfully integrated the Det3d Kitti loaders into Centerpoint pipeline. 

Suppose I want to infer the Nuscenes model for Kitti data, what changes to the kitti loading pipeline do I have to make?

**Comment by pratikkayal** [comment]
Hi Tianwei,

I was trying to adapt the models to the KITTI dataset too.

I have successfully integrated the Det3d Kitti loaders into Centerpoint pipeline.

Suppose I want to infer the Nuscenes model for Kitti data, what changes to the kitti loading pipeline do I have to make? (I have interchanged X and Y and reversed the orientation and was not getting results)
