### ISSUE TITLE
Convert Tracking Results to Lidar Coordinate Frame

### ISSUE THREAD

**Issue by saadhana** [tianweiy/CenterPoint#67]
I could finally get the Detection and Tracking work together for a rosbag file.
I use [this](https://github.com/clynamen/nuscenes2bag) library to generate rosbag files from raw data.

Bounding box visualizations of tracker results look fine.

But the tracker produces the final detections in the global frame.
I am trying to transform them back to the Lidar frame, but haven't succeeded yet.

The following dictionary is produced by the tracker:

> nusc_anno = {
>                 "sample_token": token,
>                 "translation": item['translation'],
>                 "size": item['size'],
>                 "rotation": item['rotation'],
>                 "velocity": item['velocity'],
>                 "tracking_id": str(item['tracking_id']),
>                 "tracking_name": item['detection_name'],
>                 "tracking_score": item['detection_score'],
>             }

I need the the translation, rotation and velocities in the Lidar reference frame.

I think the answer is somewhere is the following tf transformations:

 
>
>    header: 
>       seq: 0
>       stamp: 
>         secs: 1533151604
>         nsecs: 870827000
>       frame_id: "base_link"
>     child_frame_id: "lidar_top"
>     transform: 
>       translation: 
>         x: 0.985793
>         y: 0.0
>         z: 1.84019
>       rotation: 
>         x: -0.015300993788500868
>         y: 0.01739745181256607
>         z: -0.7070846669051719
>         w: 0.706749235646644

> 
>     header: 
>       seq: 0
>       stamp: 
>         secs: 1533151604
>         nsecs: 870827000
>       frame_id: "odom"
>     child_frame_id: "base_link"
>     transform: 
>       translation: 
>         x: 609.7458798427281
>         y: 1641.7771228181596
>         z: 0.0
>       rotation: 
>         x: -0.00831271916169915
>         y: -0.013503519005442664
>         z: 0.2786974021989419
>         w: -0.9602480469556655

Pose in Global coordinates -> Baselink  -> Lidar_top
But  I haven't been successful yet.

Any help with this is really appreciated.

**Comment by tianweiy** [comment]
please refer to this function https://github.com/tianweiy/CenterPoint/blob/fc9c9eef5534486c8a3b9e35c4682822bddc3498/det3d/datasets/nuscenes/nusc_common.py#L227 

Basically, two translations and rotations.  The first is from global to reference frame. The second is from the reference frame to Lidar top.

**Comment by tianweiy** [comment]
If you don't want to do transformation manually, you can just store the tracking id for each objects and then reassign these ids to the objects in the lidar top frame. This is what I do for the Waymo tracking. You can see the implementation here https://github.com/tianweiy/CenterPoint/blob/fc9c9eef5534486c8a3b9e35c4682822bddc3498/tools/waymo_tracking/test.py#L73

**Comment by saadhana** [comment]
> please refer to this function
> 
> https://github.com/tianweiy/CenterPoint/blob/fc9c9eef5534486c8a3b9e35c4682822bddc3498/det3d/datasets/nuscenes/nusc_common.py#L227
> 
> Basically, two translations and rotations. The first is from global to reference frame. The second is from the reference frame to Lidar top.

Thanks for lot for the quick response.
I tried this and now the detections are closer to the targets.

But, there still seems to be an angle error. 
I'm not sure what I'm missing, will post code and a screen grab shortly.

Meanwhile, I didn't really get what this line does:
[_second_det_to_nusc_box](https://github.com/tianweiy/CenterPoint/blob/fc9c9eef5534486c8a3b9e35c4682822bddc3498/det3d/datasets/nuscenes/nusc_common.py#L163) 

Why is the angle changed this way?

**Comment by tianweiy** [comment]
Yes, I guess this line may cause the angle error. 

Basically, the angle in Waymo and nuScenes are defined so that it is rotating clockwise from positive x-axis(forward) to the negative y-axis (right) while KITTI coordinate and this codebase uses the angle definition so that it is rotating from the negative y-axis (right) to the positive x-axis(forward). So there is a negative and minus np.pi/2

**Comment by saadhana** [comment]
So I have annotations like this in the global coordinate system:

> {'timestamp': 1533151603.54759, 
>   'translation': [582.3830289064119, 1661.0225810316042, 1.7149814278722955], 
>   'size': [1.918236255645752, 4.5219197273254395, 1.6624819040298462], 
>   'rotation': [0.9683229174572654, 0.011565557058294587, 0.0298475760421649, -0.24764104591401734], 
>   'velocity': [3.177390902324514, -1.8509666293867735], 
>   'tracking_id': '1', 
>   'tracking_name': 'car', 
>   'tracking_score': 0.7432782053947449}


To translate it to Lidar frame, I do the following:

```
            translation = np.array(annotation["translation"])
            rotation = annotation["rotation"]
            velocity = annotation["velocity"]
            velocity = (velocity[0], velocity[1], 0.0)
            rotation = Quaternion(rotation)

            # odom to baselink transformation
            q = msg_tf.transforms[0].transform.rotation
            q = [q.w, q.x, q.y, q.z]
            t = msg_tf.transforms[0].transform.translation
            q = Quaternion(q).inverse
            t = np.array([t.x, t.y, t.z])
            translation -= t
            orientation = q * rotation
            velocity = np.dot(q.rotation_matrix, velocity)


            # Baselink to lidar top
            q = msg_tf.transforms[9].transform.rotation
            q = [q.w, q.x, q.y, q.z]
            t = msg_tf.transforms[9].transform.translation
            t = np.array([t.x, t.y, t.z])
            q = Quaternion(q).inverse
            translation -= t
            orientation = q * orientation
            velocity = np.dot(q.rotation_matrix, velocity)

            annotation["translation"] = translation
            annotation["rotation"] = orientation
            annotation["velocity"] = np.array(velocity)
```

The results look like the following:

![Screenshot from 2021-01-16 00-19-02](https://user-images.githubusercontent.com/6457628/104768074-12135d00-5793-11eb-8422-4e710341c035.png)

We can kinda see the patterns of parked vehicles.

I tried adding a transformation similar to [here](https://github.com/tianweiy/CenterPoint/blob/fc9c9eef5534486c8a3b9e35c4682822bddc3498/det3d/datasets/nuscenes/nusc_common.py#L404) before bese_link to lidar_top, but that didn't work either.

Thanks in advance.

**Comment by tianweiy** [comment]
I will check later today

**Comment by saadhana** [comment]
> I will check later today

@tianweiy Did you get to check this by any chance? 
Thanks a lot for your helpful responses so far.

**Comment by tianweiy** [comment]
sorry, I am busy with some other projects. The code looks right to me. How do you visualize the detections? It seems that all boxes are off by np.pi / 2 

> I tried adding a transformation similar to here before bese_link to lidar_top, but that didn't work either.

Don't need this if you use nuscenes coordinate. 

I guess you will first get some detections in the lidar frame before converting to global frame for tracking so could you compare if the transformed tracking results matches original detections?

**Comment by tianweiy** [comment]
close due to inactivity.
