### ISSUE TITLE
derivation for gaussian_radius()

### ISSUE THREAD

**Issue by johnwlambert** [tianweiy/CenterPoint#68]
Hi Tianwei or Xingyi, would either of yall mind explaining the math/equations below in [gaussian_radius()](https://github.com/tianweiy/CenterPoint/blob/e26ea577c64825bfdab6598d1ff7a58438ee996b/det3d/core/utils/center_utils.py#L17) a bit more? 

```python
def gaussian_radius(det_size, min_overlap=0.5):
    height, width = det_size

    a1  = 1
    b1  = (height + width)
    c1  = width * height * (1 - min_overlap) / (1 + min_overlap)
    sq1 = np.sqrt(b1 ** 2 - 4 * a1 * c1)
    r1  = (b1 + sq1) / 2

    a2  = 4
    b2  = 2 * (height + width)
    c2  = (1 - min_overlap) * width * height
    sq2 = np.sqrt(b2 ** 2 - 4 * a2 * c2)
    r2  = (b2 + sq2) / 2

    a3  = 4 * min_overlap
    b3  = -2 * min_overlap * (height + width)
    c3  = (min_overlap - 1) * width * height
    sq3 = np.sqrt(b3 ** 2 - 4 * a3 * c3)
    r3  = (b3 + sq3) / 2
    return min(r1, r2, r3)
```

**Comment by tianweiy** [comment]
We just copied from CornerNet https://github.com/princeton-vl/CornerNet/blob/e5c39a31a8abef5841976c8eab18da86d6ee5f9a/sample/utils.py#L27 It is basically the solution of three quadratic equations. More discussions here https://github.com/princeton-vl/CornerNet/issues/110

It is not important. Anything works. Also, we now get a min_radius parameter and set this to two which means that nearly every radius is 2 or 3.
