### ISSUE TITLE
load annotations instead of lidar point cloud pkl to get objects?

### ISSUE THREAD

**Issue by abahnasy** [tianweiy/CenterPoint#71]
https://github.com/tianweiy/CenterPoint/blob/fc9c9eef5534486c8a3b9e35c4682822bddc3498/det3d/datasets/waymo/waymo_common.py#L61

in the above line, I believe it's loading the decoded frame instead of the decoded annotaions to get the object list. so it turns out to key not found error  when running 
```
python det3d/datasets/waymo/waymo_common.py --info_path data/Waymo/infos_val_01sweeps_filter_zero_gt.pkl --result_path data/Waymo/ --gt 
```
 to get Ground truth annotations

should we change that to `obj = get_obj(info['anno_path'])` instead?

**Comment by tianweiy** [comment]
Thanks for the bug report. You are right, it should be anno_path. I will fix this
