### ISSUE TITLE
The temporal sequence prediction

### ISSUE THREAD

**Issue by muzi2045** [tianweiy/CenterPoint#72]
this paper has a pre-work about lidar bev grid map on sequence lidar sweeps.
https://arxiv.org/pdf/2003.06754.pdf

Maybe it can extent anchor-free feature map into temporal sequence.
![image](https://user-images.githubusercontent.com/12984898/105606422-5b3b6080-5dd4-11eb-8903-75d6fc197a93.png)

**Comment by tianweiy** [comment]
yeah.. There seems to be multiple works on this direction. I would wait to see the cvpr results for these. It should be quite natural to enable better tracking, forecasting with better temporal components.

**Comment by tianweiy** [comment]
this also looks interesting https://arxiv.org/abs/2103.16054 with all these attention / transformer stuff ...
