### ISSUE TITLE
bad callback of ROS inference on latest Model and Config

### ISSUE THREAD

**Issue by hz3014** [tianweiy/CenterPoint#74]
Hey @tianweiy. After successfully built the environment for CenterPoint and ROS workspace. I changed the model and config in multi_sweep_inference.py to the latest. And the following error occurs:

> input points shape: (34720, 5)
> [ERROR] [1612365884.326025]: bad callback: <function rslidar_callback at 0x7feb92975710>
> Traceback (most recent call last):
>   File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
>     cb(msg)
>   File "/media/2TB/centerpoint_ros/src/centerpoint_ros_node/scripts/single_infernece.py", line 197, in rslidar_callback
>     scores, dt_box_lidar, types = proc_1.run(np_p)
>   File "/media/2TB/centerpoint_ros/src/centerpoint_ros_node/scripts/single_infernece.py", line 111, in run
>     voxels, coords, num_points = self.voxel_generator.generate(self.points)
>   File "/media/2TB/centerpoint_ros/src/centerpoint_ros_node/CenterPoint/det3d/core/input/voxel_generator.py", line 29, in generate
>     max_voxels,
>   File "/media/2TB/centerpoint_ros/src/centerpoint_ros_node/CenterPoint/det3d/ops/point_cloud/point_cloud_ops.py", line 149, in points_to_voxel
>     num_points_per_voxel = np.zeros(shape=(max_voxels,), dtype=np.int32)
> TypeError: 'list' object cannot be interpreted as an integer

Not sure if there's still problem in the environment or its bug in the code. Would you help to look at it?

**Comment by tianweiy** [comment]
Hi, I didn't update the ros related scripts. You can change 

https://github.com/tianweiy/CenterPoint/blob/7b665af85735725f372d051cc4f235c59a8037a8/tools/multi_sweep_inference.py#L149

to 

```
            max_voxels=self.max_voxel_num[1],
```

Let me know if you face other problems

**Comment by hz3014** [comment]
Thank you @tianweiy for your prompt reply. However, I dont think that's where the problem is. In fact, the modification max_voxels=self.max_voxel_num[1],  brings early error at read_config:

> Use HM Bias:  -2.19
> Traceback (most recent call last):
>   File "/media/hz3014/2TB/centerpoint_ros/src/centerpoint_ros_node/CenterPoint/tools/multi_sweep_inference.py", line 389, in <module>
>     proc_1.initialize()
>   File "/media/hz3014/2TB/centerpoint_ros/src/centerpoint_ros_node/CenterPoint/tools/multi_sweep_inference.py", line 130, in initialize
>     self.read_config()
>   File "/media/hz3014/2TB/centerpoint_ros/src/centerpoint_ros_node/CenterPoint/tools/multi_sweep_inference.py", line 149, in read_config
>     max_num_points=self.max_points_in_voxel[1],
> TypeError: 'int' object is not subscriptable

**Comment by tianweiy** [comment]
you should change max_voxels not max_num_points

**Comment by joshphoo** [comment]
Hi @tianweiy , thank you a lot for the great paper and detailed documentation. I am following the same steps as the steps of OP and came to the same errors. Here is what I have done so far:

Config file: nusc_centerpoint_pp_02voxel_two_pfn_10sweep_demo.py
Model file: latest.pth (from nusc_02_pp folder, Modelzoo)
ROS file: single_infernece_ros.py

I used my own rosbag file and it works really good. I then wanted to try to do the same with the **nusc_centerpoint_voxelnet_0075voxel_fix_bn_z.py** config file (as you mentioned https://github.com/tianweiy/CenterPoint/issues/19#issuecomment-664484576 here to use a better model) and the model file from the **nusc_centerpoint_voxelnet_0075voxel_fix_bn_z** folder (retrieved from model zoo). I retrieved the same error as OP and fixed it accordingly to https://github.com/tianweiy/CenterPoint/issues/74#issuecomment-772946948 . I then changed   `max_voxels=self.max_voxel_num` to  `max_voxels=self.max_voxel_num[1]` and it gave me the following error:

> input points shape: (18239, 5)
[ERROR] [1667991179.823226]: bad callback: <function rslidar_callback at 0x7fed820e7598>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "single_infernece_ros.py", line 200, in rslidar_callback
    scores, dt_box_lidar, types = proc_1.run(np_p)
  File "single_infernece_ros.py", line 135, in run
    outputs = self.net(self.inputs, return_loss=False)[0]
  File "/home/flavia/anaconda3/envs/centerpoint_ros/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/flavia/josh/CenterPoint/det3d/models/detectors/voxelnet.py", line 56, in forward
    x, _ = self.extract_feat(example)
  File "/home/flavia/josh/CenterPoint/det3d/models/detectors/voxelnet.py", line 41, in extract_feat
    batch_size=len(data['points']),
KeyError: 'points'

Do you perhaps know how to fix this?

Kind regards,
Josh

**Comment by huihui123dd** [comment]
> Hi [@tianweiy](https://github.com/tianweiy) , thank you a lot for the great paper and detailed documentation. I am following the same steps as the steps of OP and came to the same errors. Here is what I have done so far:
> 
> Config file: nusc_centerpoint_pp_02voxel_two_pfn_10sweep_demo.py Model file: latest.pth (from nusc_02_pp folder, Modelzoo) ROS file: single_infernece_ros.py
> 
> I used my own rosbag file and it works really good. I then wanted to try to do the same with the **nusc_centerpoint_voxelnet_0075voxel_fix_bn_z.py** config file (as you mentioned [#19 (comment)](https://github.com/tianweiy/CenterPoint/issues/19#issuecomment-664484576) here to use a better model) and the model file from the **nusc_centerpoint_voxelnet_0075voxel_fix_bn_z** folder (retrieved from model zoo). I retrieved the same error as OP and fixed it accordingly to [#74 (comment)](https://github.com/tianweiy/CenterPoint/issues/74#issuecomment-772946948) . I then changed to and it gave me the following error:`max_voxels=self.max_voxel_num``max_voxels=self.max_voxel_num[1]`
> 
> > input points shape: (18239, 5)
> > [ERROR] [1667991179.823226]: bad callback: <function rslidar_callback at 0x7fed820e7598>
> > Traceback (most recent call last):
> > File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
> > cb(msg)
> > File "single_infernece_ros.py", line 200, in rslidar_callback
> > scores, dt_box_lidar, types = proc_1.run(np_p)
> > File "single_infernece_ros.py", line 135, in run
> > outputs = self.net(self.inputs, return_loss=False)[0]
> > File "/home/flavia/anaconda3/envs/centerpoint_ros/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in **call**
> > result = self.forward(*input, **kwargs)
> > File "/home/flavia/josh/CenterPoint/det3d/models/detectors/voxelnet.py", line 56, in forward
> > x, _ = self.extract_feat(example)
> > File "/home/flavia/josh/CenterPoint/det3d/models/detectors/voxelnet.py", line 41, in extract_feat
> > batch_size=len(data['points']),
> > KeyError: 'points'
> 
> Do you perhaps know how to fix this?
> 
> Kind regards, Josh
