### ISSUE TITLE
Is there any published detection result data?

### ISSUE THREAD

**Issue by tndus5497** [tianweiy/CenterPoint#75]
Hello, thank you for the publication of your work.

I tried to use this algorithm for the Nuscene dataset, but it takes too much time in the create data part (More than 5 days).

Do I have to perform the create data part to get the detection result?

Are there any public detection results for train, val, and test like megvii and pointpillars released in the nuscene dataset?

**Comment by tianweiy** [comment]
Firstly, why will it take that long(it is a few minutes for me after downloading)?

**Comment by tianweiy** [comment]
Do I have to perform the create data part to get the detection result? You need to generate info files. Gt database is not required.

**Comment by tianweiy** [comment]
I release detection files on val for all nuScenes model. And detection file for test for our test set submission. Generating training detections for all models will take some time which I don't have recently.

**Comment by tianweiy** [comment]
If you only need one specific model, I can generate the training / testing file this weekend.

**Comment by tndus5497** [comment]
Hi tianweiy,

Can i get a detection result based on centerpoint_pillar?

I'm going to test my tracking algorithm using this detection result.

**Comment by tianweiy** [comment]
Ok, I will generate those files tomorrow.

**Comment by tianweiy** [comment]
A bit busy today, I will send you the file tomorrow morning

**Comment by tianweiy** [comment]
done, all files are in this folder https://drive.google.com/drive/folders/1K_wHrBo6yRSG7H7UUjKI4rPnyEA8HvOp?usp=sharing
