### ISSUE TITLE
Did you use the nsweeps ==2,3,4,5, I use the 5,the result become bed.

### ISSUE THREAD

**Issue by alsun-oven** [tianweiy/CenterPoint#76]

**Comment by tianweiy** [comment]
which dataset?

**Comment by alsun-oven** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Tianwei&amp;nbsp;Yin&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月8日(星期一) 凌晨0:40
收件人:&nbsp;&quot;tianweiy/CenterPoint&quot;<CenterPoint@noreply.github.com&gt;;
抄送:&nbsp;&quot;SemanticSegmentationModel&quot;<1209857774@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tianweiy/CenterPoint] Did you use the nsweeps ==2,3,4,5, I use the 5,the result become bed. (#76)

**Comment by tianweiy** [comment]
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;Tianwei&amp;nbsp;Yin&quot;<notifications@github.com&gt; 发送时间:&nbsp;2021年2月8日(星期一) 凌晨0:40 收件人:&nbsp;&quot;tianweiy/CenterPoint&quot;<CenterPoint@noreply.github.com&gt;; 抄送:&nbsp;&quot;SemanticSegmentationModel&quot;<1209857774@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;; 主题:&nbsp;Re: [tianweiy/CenterPoint] Did you use the nsweeps ==2,3,4,5, I use the 5,the result become bed. (#76)

Could you send your reply again?
