### ISSUE TITLE
Spconv Installation issue

### ISSUE THREAD

**Issue by swetapriyadarshi** [tianweiy/CenterPoint#77]
May I know what could be the possible reason for the below error, when I try setting up spconv:

Command Ran: python setup.py bdist_wheel
Error: 
![image](https://user-images.githubusercontent.com/37204536/107256918-1c2e2180-6a08-11eb-9a42-da284f25e33d.png)

**Comment by tianweiy** [comment]
Don't have much clues. You could search in spconv's issues. It is not related to our codebase.

**Comment by DeclK** [comment]
I met the same problem, and I solved this by changing g++ & gcc version to 7.5.0
Reference link https://github.com/traveller59/spconv/issues/241
