### ISSUE TITLE
Detections (or config/checkpoint) for KITTI?

### ISSUE THREAD

**Issue by aydoo** [tianweiy/CenterPoint#78]
Hi,
I would like to apply CenterPoint (detector) on the KITTI dataset. I saw in a previous issue that you mentioned that perhaps there might be support in the future. Any news on this? Simply having detections for KITTI test or a common val split would already be great. In any case, thanks for the great work! :)

**Comment by tianweiy** [comment]
Hi, there won't be updates for this in the near future. KITTI benchmark is a little saturating and I don't have time to tune the model on KITTI recently. It performs similarly to the baselines in my previous attempts. I guess anchor-based methods are fine for KITTI as the main evaluations are about detecting the axis-aligned vehicles, which center-based methods don't have an edge (See Table 7/8 of our paper).

**Comment by hz3014** [comment]
> 
> 
> Hi, there won't be updates for this in the near future. KITTI benchmark is a little saturating and I don't have time to tune the model on KITTI recently. It performs similarly to the baselines in my previous attempts. I guess anchor-based methods are fine for KITTI as the main evaluations are about detecting the axis-aligned vehicles, which center-based methods don't have an edge (See Table 7/8 of our paper).

Hi, tianweiy. I agree that KITTI dataset is less meaningful to challenge, BUT I think it's meaningful to have the KITTI support for those who want to train custom dataset. Building custom dataset in NuScenes or Waymo format is very hard for individuals, if theres KITTI support, Centerpoint can be applied further beyond NuScenes and Waymo. KITTI support without model tuning is also appreciated from people want to use custom dataset.

**Comment by tianweiy** [comment]
I agree. I just don't get time to merge and test code recently. I will see if I have some capacity after ICCV deadline.

**Comment by abhigoku10** [comment]
@tianweiy  any updates on merging of the code !!!

**Comment by tianweiy** [comment]
Get two papers to write for ICCV. I will support custom dataset training/testing after the deadline.

**Comment by abhigoku10** [comment]
@tianweiy oh no issues please conc on ur current activities thanks for the response

**Comment by tianweiy** [comment]
@abhigoku10  by next weekend XD

**Comment by tianweiy** [comment]
sorry, I am too busy than I thought. I originally planned to write a custom dataset wrapper but I don't get time due to  a few projects that have really tight deadlines. I believe the current model should be in a good shape to do custom dataset training with minimum modifications. 

Basically, here is the thing you need to do. Let's pretend you are doing single frame detection (following KITTI), you can prepare your dataset following our Waymo format. 

You need the following files in a folder 

- train 
           - lidars 
                        - multiple pickle or numpy files with points in it (shape N x 4/5/6)
           - annos
                         - multiple pickle files with objects key in it 
                         - labels (M x1) one of ['UNKNOWN', 'VEHICLE', 'PEDESTRIAN', 'SIGN', 'CYCLIST'] 
                         - boxes (M x 7) annotations will follow KITTI LiDAR coordinate we use throughout this repo. basically  x, y, z, width, length, height, rotation from negative y axis counterclockwisely

then you can pretend that this is the Waymo dataset, and generate infos and gt database and use existing configs to train the model. you can visualize it with https://github.com/tianweiy/CenterPoint/blob/master/tools/visual.py 

I understand there are still maybe 50 lines to change to work on the custom dataset. This is one limitation that I will try to fix in the future (if I get time ...).

**Comment by mrqrs** [comment]
> Hi, there won't be updates for this in the near future. KITTI benchmark is a little saturating and I don't have time to tune the model on KITTI recently. It performs similarly to the baselines in my previous attempts. I guess anchor-based methods are fine for KITTI as the main evaluations are about detecting the axis-aligned vehicles, which center-based methods don't have an edge (See Table 7/8 of our paper).

Thanks for your nice work. Can you tell us CenterPoint in kitti result?("similarly to the baselines", how it performs in car moderate?)

**Comment by tianweiy** [comment]
78-79 (recall 11) a few months ago if you use stride 4

**Comment by mrqrs** [comment]
> 78-79 (recall 11) if you use stride 4

Thanks for your reply. The CenterPoint is a really great work.

**Comment by tianweiy** [comment]
One implementation is available here https://github.com/tianweiy/CenterPoint-KITTI For some unknown reasons the single-stage performance is a little lower than my implementation in mmdet3d (77-78 vs 78 - 79 11 recall) but it seems that combining CenterPoint with PVRCNN works quite well (~~84.95 40 recall).
