### ISSUE TITLE
Where can I find CONFIG_PATH

### ISSUE THREAD

**Issue by varunvv** [tianweiy/CenterPoint#79]
In "python -m torch.distributed.launch --nproc_per_node=4 ./tools/train.py CONFIG_PATH"
Where or how is the config file created

**Comment by tianweiy** [comment]
https://github.com/tianweiy/CenterPoint/tree/master/configs/nusc

**Comment by tianweiy** [comment]
find the config of the model you want to use in the above link and the name is linked to a file
