### ISSUE TITLE
About the contribution of multi-frames data

### ISSUE THREAD

**Issue by muzi2045** [tianweiy/CenterPoint#8]
Hi, I have tried to inference the network with nuscene_dataset_mini rosbag, and have some reasonable results
![2020-06-29-15-27-41](https://user-images.githubusercontent.com/12984898/85986154-5ec55f80-ba1e-11ea-87b9-c6917b5d13e2.gif)

this results is inference with single sweep data, 
so there look like some detections are not stable when in a real-time system.
will it be better when concate past 5 or 10 sweep lidar data ?
the detections results will be more stable or boost the mAP result?

Another problem is the multiclass score filter threshold, 
the core problem is that how to distinguish some small obstacles such as pedestrian and cyclist.
these small object normally have lower score than big cars, 
if set the all class threshold to 0.1,
the FP results will be too much.
here is a example, some people together to be detect as one car.
![image](https://user-images.githubusercontent.com/12984898/85989619-57548500-ba23-11ea-91d8-e0ecb11c1510.png)

here is my personal setting when deal with the raw predicts from network:
```
    car_indices =                  get_annotations_indices(0, 0.4, label_preds_, scores_)
    truck_indices =                get_annotations_indices(1, 0.4, label_preds_, scores_)
    construction_vehicle_indices = get_annotations_indices(2, 0.4, label_preds_, scores_)
    bus_indices =                  get_annotations_indices(3, 0.3, label_preds_, scores_)
    trailer_indices =              get_annotations_indices(4, 0.4, label_preds_, scores_)
    barrier_indices =              get_annotations_indices(5, 0.4, label_preds_, scores_)
    motorcycle_indices =           get_annotations_indices(6, 0.15, label_preds_, scores_)
    bicycle_indices =              get_annotations_indices(7, 0.15, label_preds_, scores_)
    pedestrain_indices =           get_annotations_indices(8, 0.12, label_preds_, scores_)
    traffic_cone_indices =         get_annotations_indices(9, 0.1, label_preds_, scores_)
```
 @tianweiy

**Comment by tianweiy** [comment]
```
the detections results will be more stable or boost the mAP result?
```

The most important thing I think is that it is only reasonable to do velocity estimation using multiple sweeps of lidar data which is required by the nuScenes benchmark.   

Though there are evidences that both Waymo / nuScenes will get a 4~5 map boost using 5 sweeps / 10 sweeps respectively. I guess it will also be more stable. 

```
Another problem is the multiclass score filter threshold,
the core problem is that how to distinguish some small obstacles such as pedestrian and cyclist.
these small object normally have lower score than big cars,
if set the all class threshold to 0.1,
the FP results will be too much.
here is a example, some people together to be detect as one car.
```

Yes, the same 0.1 threshold is not optimal to use in real scenarios because of the large amount of FP. I have tuned this but it seems this doesn't matter much for map so I didn't spend too much time. Probably tune the threshold to get objects of each class to a reasonable number. 

```some people together to be detect as one car ``` One reason is that we do multiple class nms so car prediction won't suppress small objects, and vice versa. You can change this to a single NMS though not very sure if this works well.

**Comment by muzi2045** [comment]
> One reason is that we do multiple class nms so car prediction won't suppress small objects, and vice versa. You can change this to a single NMS though not very sure if this works well.
here is the point, are the predict scores between classes are "comparable"?
if using single NMS func among all classes, you must order the boxes by scores.
Suppose that here exist one FP car detect box (0.4~0.5 score), and the car box contain several TP pedestrian box(0.1~0.3 score).
which box should be suppress? 
@tianweiy

**Comment by tianweiy** [comment]
> here is the point, are the predict scores between classes are "comparable"?
No, they are not comparable. But, there is a prior that there are fewer construction vehicles or trailers than cars. 

>  Suppose that here exist one FP car detect box (0.4 ~ 0.5 score), and the car box contain several TP pedestrian box(0.1~0.3 score).  which box should be suppress?
Not sure for that, I guess still using multi-calss nms is fine given that you choose a good threshold for each class

**Comment by muzi2045** [comment]
the ros inference scripts will open pull request.
it's a simple tool to vis the real output results on real world data.
not just run the dataset evaluation scripts.
@tianweiy
