### ISSUE TITLE
num_lidar_points_in_box is all 0

### ISSUE THREAD

**Issue by nuoloveheng** [tianweiy/CenterPoint#81]
I use create_data.py to parse the labels of waymo-dataset. The parsed data num_lidar_points_in_box is all 0, and then I try to enter the waymo_open_dataset/Label_pd2.py, but I don't know how to modify it. Can you help me?

**Comment by tianweiy** [comment]
Could you attach your infos file? I think there are some empty boxes but most num_lidar_points_in_box are not zero.

**Comment by nuoloveheng** [comment]
hello, thank you for replying, it also started with this line 

det3d/datasets/waymo/waymo_common.py 270 line'
mask_not_zero = (num_points_in_gt > 0).reshape(-1)
it only take the gt bbox whose points inside bbox greater than zeros.  That makes sense. but after I ran this script, there was no gt bbox that I can extract from original label. So that I debug this, found out this line

'det3d/datasets/waymo/waymo_decoder.py 171 ' num_lidar_points_in_box was always being zero. I think this issue is the waymo_open_dataset/label_pd2.py, but I checked it there was the field named num_lidar_points_in_box. do you know how to fix it? I usewaymo-open-dataset-tf-1-15-0  version is 1.2.0

**Comment by tianweiy** [comment]
sorry, I never encountered this. Could you attach a link to the generated info files after running create_data.py. I can take a look into the file and see
