### ISSUE TITLE
Mismatching between the paper results and leaderboard results 

### ISSUE THREAD

**Issue by Son-Goku-gpu** [tianweiy/CenterPoint#82]
@tianweiy Really wonderful work, simple and effective! I only wonder why your nuScenes leaderboard results are higher than your paper v2 results (mAP: 58.0 ?), could you help to clarify it? Thank you!

**Comment by tianweiy** [comment]
Leaderboard is challenge number with ensemble, test time augmentation, and ppintpainting. 58 is single model result without bells and whistles. The ablations to go from 58 to challenge number are in the appendix

**Comment by Son-Goku-gpu** [comment]
Thanks for you clarification.
