### ISSUE TITLE
Implementation of two sweep for velocity estimation

### ISSUE THREAD

**Issue by you4ever** [tianweiy/CenterPoint#83]
Hi Tianwei,

Could you please clarify the implementation of the two-sweep based velocity estimation? According to your paper Section 4 "**Velocity head and tracking**" :  _The velocity estimate is special, as it requires two input map-views the current and previous time-step. It predicts the difference in object position between the current and the past frame._ 

I wonder how is it actually implemented in the repo. Here is my understanding -- please comment if I'm correct:  Instead of taking two "map-views" you are actually taking two frames of point cloud data and attach timestamp as an additional feature at the input of the network as in CenterPoint/det3d/datasets/pipelines/loading.py
`            if nsweeps > 1: 
                sweep_points_list = [points]
                sweep_times_list = [np.zeros((points.shape[0], 1))]

                assert (nsweeps - 1) == len(
                    info["sweeps"]
                ), "nsweeps {} should be equal to the list length {}.".format(
                    nsweeps, len(info["sweeps"])
                )

                for i in range(nsweeps - 1):
                    sweep = info["sweeps"][i]
                    points_sweep, times_sweep = read_single_waymo_sweep(sweep)
                    sweep_points_list.append(points_sweep)
                    sweep_times_list.append(times_sweep)

                points = np.concatenate(sweep_points_list, axis=0)
                times = np.concatenate(sweep_times_list, axis=0).astype(points.dtype)

                res["lidar"]["points"] = points
                res["lidar"]["times"] = times
                res["lidar"]["combined"] = np.hstack([points, times])
`
And in both single-sweep and two-sweep cases, the dataflows are essentially the same except in two-sweep case, the input channel is extended to 6 to accommodate the time feature.

**Comment by tianweiy** [comment]
You are right. We will clarify this better in the next version

**Comment by you4ever** [comment]
> You are right. We will clarify this better in the next version

Thanks for your prompt response!

**Comment by you4ever** [comment]
> You are right. We will clarify this better in the next version

BTW, I'm curious. Will the way described in your paper (take BEV feature output from two frames then feed to head) be more efficient / better performance? Have you tried that?

**Comment by tianweiy** [comment]
I never tried this for 3d case. But I guess it should improve a bit (aggregating temporal feature). This may be useful for other tracking / prediction tasks that requires temporal reasoning. You can check out this https://github.com/tianweiy/CenterPoint/issues/72 and any video detection papers.
