### ISSUE TITLE
why not regress to relative velocity?

### ISSUE THREAD

**Issue by you4ever** [tianweiy/CenterPoint#86]
If I understand correctly, the bounding box velocity is converted to the sensor's coordinate and used as the regression target. But I wonder if it's better to predict the relative velocity of the bb to ego since the relative bb translation is the regression target. 

```
def global_vel_to_ref(vel, global_from_ref_rotation):
  # inverse means ref_from_global, rotation_matrix for normalization
  vel = [vel[0], vel[1], 0]
  ref = np.dot(Quaternion(matrix=global_from_ref_rotation).inverse.rotation_matrix, vel) 
  ref = [ref[0], ref[1], 0.0]

  return ref

```

**Comment by tianweiy** [comment]
I haven't tried this but it sounds reasonable
