### ISSUE TITLE
How to train on multiple gpus using slurm commands?

### ISSUE THREAD

**Issue by tianqi-wang1996** [tianweiy/CenterPoint#88]
Hello, seems like the instruction in Nusc.md only says how to run on your local machine.

But I need to submit the task to a server using slurm commands,  can you give me an instruction on how to achieve this? I think there needs some changes in tools/train.py regarding the distributed initialization.

**Comment by tianweiy** [comment]
srun -p [MACHINE_NAME] --gres=gpu:4 --mem=[MEM]G -c [CPU_NUM]  python -m torch.distributed.launch --nproc_per_node 4  --master_port 3812  tools/train.py configs/nusc/voxelnet/xx.py

**Comment by poodarchu** [comment]
@tianweiy it's wrong. it requires more work to make slurm mode ready for Det3D.

**Comment by tianweiy** [comment]
For instance? I can use this command in my school's slurm system

**Comment by poodarchu** [comment]
https://github.com/Megvii-BaseDetection/cvpods/issues/64

sth like this.

**Comment by tianweiy** [comment]
thanks. I haven't met this issue with slurm yet. I will take a deeper look if someone met this in this repo.

**Comment by tianweiy** [comment]
I guess you can use as much memory as you have in the server? The memory seems to relate to the number of data loader workers, voxelization, dataset, and gt sampling. I think it needs maybe 300 - 400 gb in my case with 8 v100.
