### ISSUE TITLE
Bounding box drawing and value representation

### ISSUE THREAD

**Issue by abhigoku10** [tianweiy/CenterPoint#94]
@tianweiy, when i run the model on the nusc/ custom data  the predictions consists of  "box3d_lidar", the values obtained from them, are the centerxyz , wlh which when i use to draw on the point cloud is not exactly on the object is there any conversion we should be doing for drawing the prediction bounding box to visualization 

![image](https://user-images.githubusercontent.com/22094053/110404989-dff0ee00-80a5-11eb-9ae2-e342ed9abe3f.png)

**Comment by tianweiy** [comment]
I don't have time to check any code before next Wednesday. But you can check if the rotation is off by 1/2 np.pi or if the w and l need to be transposed.

**Comment by abhigoku10** [comment]
@tianweiy  thanks for the support was able to solve it will close this issue

**Comment by MohamedElhadidy0019** [comment]
@abhigoku10 
can you please explain how you solved the problem
