### ISSUE TITLE
Tracking on custom dataset 

### ISSUE THREAD

**Issue by abhigoku10** [tianweiy/CenterPoint#95]
@tianweiy  thanksf or sharing the code , can we apply online tracking for the 3d bounding boxes as soon as the model prediction happens ? which code to run for this operation

**Comment by tianweiy** [comment]
No code for this at the moment. But this sounds a good idea. I will start implementing this soon

**Comment by abhigoku10** [comment]
@tianweiy  can we modify the existing tracking script ??

**Comment by tianweiy** [comment]
Yes, existing script should work. You just need to also run it with the detection

**Comment by tianweiy** [comment]
by custom dataset, do you still have the lidar pose data (transform matrix from top lidar to a global coordinate). If not, our tracking algorithm probably doesn't work well as we need to do the tracking in the global frame. You can probably look at AB3D if you don't have pose data.

**Comment by tianweiy** [comment]
closed due to inactivity. Reopen if you get any questions
