### ISSUE TITLE
Can you provide all metric result of waymo dataset?

### ISSUE THREAD

**Issue by MengAaron** [tianweiy/CenterPoint#98]
Hi! Thanks for wonderful code!
I am trying to reimplement your code on OpenPCDet. However, my result is lower than you about 6 percent, on whole waymo dataset with 12 epochs. So I want to compare other metric result with yours, such as Veh, Ped or Cyc L1/L2 AP/APH. Can you provide that result?

**Comment by tianweiy** [comment]
https://waymo.com/open/challenges/entry/?timestamp=1608450374734314&challenge=DETECTION_3D&email=yintianwei@utexas.edu&submissionType=VALIDATION

**Comment by MengAaron** [comment]
thx!

> https://waymo.com/open/challenges/entry/?timestamp=1608450374734314&challenge=DETECTION_3D&email=yintianwei@utexas.edu&submissionType=VALIDATION
